### ISSUE TITLE
你好 我很喜欢这个哔哩美化插件 为了未来更新更好的插件 我想提几个建议

### ISSUE THREAD

**Issue by sixiansheng** [hakadao/BewlyBewly#101]
可以增加一个弹出播放器的窗口吗 例如
![image](https://github.com/hakadao/BewlyBewly/assets/35787924/54cb59f3-1b2d-4026-abb1-d51dff9c0ce3)
另外可以显示搜索栏的关键词吗 例如
![image](https://github.com/hakadao/BewlyBewly/assets/35787924/d185609e-4a76-445b-a193-2207520be96f)
还有 可以增加一个去除ui发光的开关吗 因为发光的ui会吸引我看视频的眼球,不由自主的看着发光ui

**Comment by hakadao** [comment]
你用的是哪個插件，可以給出來參考一下嗎

**Comment by sixiansheng** [comment]
> 你用的是哪個插件，可以給出來參考一下嗎

你好 这是 我自己写的 其实是让chatgpt帮我写的 
这是chatgpt帮我写的弹出小窗油猴脚本:

// ==UserScript==
// @name         Open Bilibili Links in Popup Window
// @namespace    http://yournamespace.com
// @version      0.7
// @description  Open Bilibili links in a popup window centered on the screen with a slight left shift
// @author       Your Name
// @match        https://www.bilibili.com/*
// @match        https://search.bilibili.com/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    function openPopupWindow(targetUrl) {
        var popupWidth = 906;
        var popupHeight = 510;

        // 将 left 减去 50px，你可以根据需要调整这个值
        var left = (window.innerWidth - popupWidth) / 2 - 69;
        var top = (window.innerHeight - popupHeight) / 2 - 50;

        window.open(targetUrl, '_blank', 'width=' + popupWidth + ',height=' + popupHeight + ',left=' + left + ',top=' + top);
    }

    function handleClick(event) {
        var targetLink = event.target.closest('a');
        if (targetLink) {
            event.preventDefault();
            var targetUrl = targetLink.href;
            openPopupWindow(targetUrl);
        }
    }

    // 将事件委托添加到更具体的父元素上
    document.body.addEventListener('click', handleClick);
})();

下面这个是小窗打开后自动网页全屏 的脚本 
https://greasyfork.org/zh-CN/scripts/415804-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9-bilibili-com-%E6%92%AD%E6%94%BE%E9%A1%B5%E8%B0%83%E6%95%B4

然后下面这个是
我让chatgpt参考其他脚本写的高斯模糊首页 脚本
// ==UserScript==
// @name         Bilibili Style Customization
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Customize Bilibili styles
// @author       You
// @match        https://www.bilibili.com/
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // Your CSS styles
    var customStyles = `
     .bili-dyn-ads,
.vcd,
.eva-banner,
.gg-floor-module,
.bili-header__channel,
.fixed-reply-box,
.adpos,
.ad-f,
.ad,
.video-top-ad,
.video-bottom-ad,
.bilibili-player-promote-wrap,
.video-page-game-card-small,
#bannerAd,
#slide_ad,
.left-entry>*:nth-of-type(1n + 2),
.ad-report,
.video-page-game-card-small,
.right-entry-item,
.vip-wrap,
.trending,
.channel-items__right,
.channel-icons,
.palette-button-wrap,
.header-banner__inner,
.video-toolbar-right,
.video-share-wrap,
.new-charge-btn,
.old-charge-btn,
.fixed-sidenav-storage,
#right-bottom-banner,
.pop-live-small-mode,
#activity_vote,
.act-end,
.bili-link,
.bili-show,
.bpx-player-top-wrap,
.vip-entry-containter,
.links-item>.v-popover-wrap,
.reply-decorate,
.fan-badge,
.video-page-special-card-small,
.live-status,
.user-label,
.card-user-vip,
.card-bg,
.bili-avatar-pendent-dom,
.avatar-panel-popover>.links-item>.single-link-item>svg,
.icon.search-word,
.icon.normal,
.adblock-tips,
.bpx-player-dm-hint,
#v_tag,
.bpx-player-contextmenu>*:nth-of-type(1n + 5),
.level-item>.v-popover,
.bpx-player-ending-wrap,
.reply-notice,
.mini-header .left-entry .mini-header__title,
.v-popover.is-bottom-start,
.bili-header .slide-down .left-entry .mini-header__title
{
    display:none!important
}
.user-card .card-bgm,
.user-card-m-exp .bg{
    height: 4px!important;
    background-image: none!important;
}
.right-entry>li:nth-of-type(3)>.v-popover{
    margin-left: -50px!important
}
.right-entry>li:nth-of-type(4)>.v-popover{
    margin-left: -175px!important
}
.right-entry>li:nth-of-type(5)>.v-popover{
    margin-left: -150px!important
}
.center-search__bar{
    margin:0px!important;
    max-width:9000px!important
}
.channel-items__left{
    border-right:none!important
}
.jump-link.search-word,
.jump-link.normal{
    pointer-events: none!important;
    color: var(--text1)!important;
    cursor: text!important;
}
.card-user-name,.sub-user-name,.user-name{
    color:var(--text1)!important;
}
.w_title{
    min-height:58.4px!important
}
.bili-header .bili-header__channel .channel-items__left{
    padding-left:30px;
}
input::placeholder,
textarea::placeholder{
    color:transparent!important
}
}


     .harmony-font,.win{
    background-attachment: fixed;
    background-size: cover;
    background-color:rgb(255, 255, 255)!important
}

::-webkit-scrollbar-thumb{
    background:rgba(164, 164, 164, .79)!important;
    border-radius:10px!important;
}

.reply-box .box-normal .reply-box-warp .reply-box-textarea.focus[data-v-572457cb],
.reply-box .box-normal .reply-box-warp .reply-box-textarea[data-v-572457cb]:hover,
.reply-box .box-normal .reply-box-warp .reply-box-textarea{
    background:rgba(180, 180, 180, .19)!important
}
.bili-header .avatar-panel-popover,
.bili-header .bili-header__channel,#w_body,#header-v3, #app,
.bili-header .center-search-container .center-search__bar #nav-searchform.is-actived .nav-search-content,
.bili-header .center-search-container .center-search__bar #nav-searchform.is-focus .nav-search-content,
.bili-header .center-search-container .center-search__bar .nav-search-content .nav-search-input:active,
.bili-header .center-search-container .center-search__bar .nav-search-content .nav-search-input:focus,
.bili-comment.browser-pc{
    background:transparent;
}
.bpx-player-auxiliary .bpx-player-dm,
.bpx-player-auxiliary .bpx-player-collapse .bpx-player-wraplist,
.bui-collapse .bui-collapse-wrap,
.bui-collapse,
.bpx-player-auxiliary,
.bpx-docker-minor,
.video-container-v1 .danmaku-box .danmaku-wrap,
.bpx-player-auxiliary .bpx-player-collapse .bui-collapse-body,
.bpx-player-auxiliary .bpx-player-dm-wrap,
.bpx-player-auxiliary .bpx-player-dm-function,
.bui-collapse .bui-collapse-header,
.video-container-v1 .danmaku-box .danmaku-wrap,
.bpx-player-auxiliary .bpx-player-dm-btn-history,
.base-video-sections-v1,
.base-video-sections-v1 .video-section-list .video-episode-card__info-playing,
.membersinfo-normal .header,
.bpx-docker-minor:not(:empty){
    background:transparent!important;
    box-shadow:none!important;
    border-radius:19px!important
}
#nav-searchform,
.bili-header .center-search-container .center-search__bar .nav-search-content,
.bili-header .center-search-container .center-search__bar .nav-search-btn,
.bili-header .histories .history-item,
.avatar-panel-popover>.links-item>.single-link-item,
.bili-header-channel-panel>.channel-panel__column>.channel-panel__item,
.v-popover-content,
.detail-channel-popup,
.detail-channel-popup-bottom .btn-panel .channel-entry-btn,
.toggle-sub-btn,
.channel-cancel-pop>*,
.top-icon,
.operation-list,
.user-card,
.card-btn-warp>*,
.reply-tag-item,
.btn-box>*,
.default-btn,
.second-line_right,
.video-episode-card__info,
.bpx-player-video-inputbar,
.bpx-player-dm-btn-send,
.channel-link,
.bpx-player-container,
#channel-entry-more,
.w_control_item>label,
.w_video_type_control_item>label,
.more-channel-popover__wrap>div>.name,
.bui-collapse-header,
.bpx-player-dm-btn-history,
.dm-info-report-btn,
.dm-info-block-btn,
.bpx-player-contextmenu,
.reply-box-textarea,
.reply-box .box-normal .reply-box-send::after,
.user-card-m-exp .layout,
.card-loaded,
.recommend-list-v1 .rec-footer,
.reply-content-container .reply-content .note-prefix,
.sub-item>.name,
.honor,
.logout-item{
    border-radius:19px!important
}
.detail-channel-popup-top .bg-mask{
    background:none!important
}
.detail-channel-popup-top .channel-cover{
    border-radius:100%!important
}
#nav-searchform.is-focus,
.menu_block,
.detail-channel-popup-top .bg-image,
.operation-list>.operation-option:nth-of-type(1){
    border-radius:19px 19px 0 0!important
}
.bili-header .search-panel,
.menu_child,
.operation-list>.operation-option:nth-of-type(2){
    border-radius:0 0 19px 19px!important
}
#w_control,
#w_video_type_control{
    border-radius:0 19px 19px 0!important
}
.bili-header .center-search-container .center-search__bar.is-focus{
    box-shadow:none!important
}
.bottom-line{
    display:none!important
}
.bili-header .center-search-container .center-search__bar #nav-searchform{
    border:none!important
}
.video-page-operator-card-small:hover,
.video-page-card-small:hover,
.video-episode-card:hover,
.bui-long-list-item:hover,
.w_control_item:hover,
.history-item
{
    -webkit-transform: scale(1.01);
    transform: scale(1.01);
    box-shadow: 1px 1px 5px #88888829!important;
    border-radius:19px!important
}
.w_control_item > input:checked + label,
.w_control_item > label:hover{
    border-color:#8080808c;
    color:#434343e0
}
.w_title{
    padding-left:10px;
    padding-right:10px;
}
.view-more{
    padding-top: 10px;
    padding-bottom: 16px;
}
.up-panel-container{
    padding-bottom:18px;
}
#w_control{
    background-color:rgba(255, 255, 255, .4)!important;
    backdrop-filter:blur(10px)!important;
    box-shadow: 1px 1px 5px #7272721f!important;
    border-radius:0px 19px 19px 0px!important;
    border-color:transparent;
}
.bili-feed4 .bili-header .slide-down{
    background-color:rgba(255, 255, 255, .8)!important;
    box-shadow: 1px 1px 5px #7272721f!important;
    border-radius:0px 0px 19px 19px!important;
}
.v-popover_bottom-enter-active.v-popover_bottom-enter-to,
.v-popover_bottom-leave-active.v-popover_bottom-leave-to{
    transition:none
}
.mini-header .center-search-container .center-search__bar .search-panel,
.slide-down .center-search-container .center-search__bar.is-focus .search-panel,
.bili-header .search-panel{
    background-color:rgba(255, 255, 255, .4)!important;
    backdrop-filter:blur(10px)!important;
    box-shadow: 1px 1px 5px #7272721f!important;
    border-radius:0px 0px 19px 19px!important;
    border-color:transparent;
}
.center-search__bar.is-focus #nav-searchform{
    background-color:rgba(255, 255, 255, .4)!important;
    backdrop-filter:blur(10px)!important;
    box-shadow: 1px 1px 5px #7272721f!important;
    border-radius:19px 19px 0px 0px!important;
    border-color:transparent;
}
.v-popover-content{
    background-color:rgba(255, 255, 255, .4)!important;
    backdrop-filter:blur(10px)!important;
    box-shadow: 1px 1px 5px #7272721f!important;
    border-radius:19px!important
}
.bili-header .message-entry-popover .message-inner-list__item:hover,
.bili-header .header-fav-card:hover,
.bili-header .header-history-video:hover,
.bili-header .header-history-live:hover,
.bili-header .header-history-article:hover,
.bili-header .header-dynamic-list-item:hover {
    background-color: #e3e5e752;
}
.video-info-container{
    margin-bottom:18px!important
}
.w_item,
.danmaku-box,
.base-video-sections-v1,
.rec-list,
.up-info-container,
.video-info-container,
.reply-item,
.sub-reply-item,
.history-item,
.bili-header .center-search-container .center-search__bar #nav-searchform[class=""],
.recommend-list-v1 .rec-footer{
    background-color:rgba(255, 255, 255, .2)!important;
    backdrop-filter:blur(10px)!important;
    box-shadow: 1px 1px 5px #7272721f!important;
    border-radius:19px!important
}
.members-info-container,
.user-card-m-exp,
.user-card{
    background-color:rgba(255, 255, 255, .7)!important;
    backdrop-filter:blur(10px)!important;
    box-shadow: 1px 1px 5px #7272721f!important;
    border-radius:19px!important
}
.header-v3 #biliMainHeader .mini-header{
    background-color:rgba(229, 229, 229, .83)!important;
}
.video-page-card-small .card-box{
    margin-top:10px;
}
.rec-list{
    padding:6px;
}
div.comment-container {
  background-color: #242526;
}
}
    `;

    // Create a style element and append it to the head
    var styleElement = document.createElement('style');
    styleElement.type = 'text/css';
    styleElement.innerHTML = customStyles;
    document.head.appendChild(styleElement);
})();

我自己完全不会写脚本 都是chatgpt帮我写的脚本,谢谢作者这么晚还回复我,爱你

**Comment by hakadao** [comment]
好吧，小窗那個不打算做因為這功能對up主很不尊重
ui問題，到時候選中項也會加上發光或其他效果確保主次分明

**Comment by hakadao** [comment]
去除ui发光的开关是指dock那邊嗎，dock可以隱藏的
搜尋結果關鍵字高亮在pr已經有人實現並合併了
窗口功能那個我會再考慮吧，抱歉最近都再試合併過來的功能和重構當時回覆時沒有認真看

**Comment by sixiansheng** [comment]
> 去除ui发光的开关是指dock那邊嗎，dock可以隱藏的 搜尋結果關鍵字高亮在pr已經有人實現並合併了 窗口功能那個我會再考慮吧，抱歉最近都再試合併過來的功能和重構當時回覆時沒有認真看

谢谢你的回复,就是这两个地方的发光部分,
![image](https://github.com/hakadao/BewlyBewly/assets/35787924/c7d636e9-1d3b-40a7-9b37-36e1d3332bda)

希望作者大大能加一个发光开关,感谢,就像这样子不会发光的状态
![image](https://github.com/hakadao/BewlyBewly/assets/35787924/4975c038-b4de-40cc-a091-e7287d313e48)

**Comment by hakadao** [comment]
謝謝你的建議，但是發光這裏不怎麼考慮做個開關，因為發光我真的憑感覺加的，也不一定是所有地方有發光效果
或許考慮下在滑過影片卡時也加入相應的效果防止注意力分散？或者看看這兩個地方有沒有更好的調整？
