### ISSUE TITLE
topbar videos 的稍后再看按钮颜色太暗

### ISSUE THREAD

**Issue by cuiko** [hakadao/BewlyBewly#104]
首页的是白色的，动态里的是黑色的
videos
![image](https://github.com/hakadao/BewlyBewly/assets/33982919/cabb1388-5399-43f0-b854-419bb3df72f1)
homepage
![image](https://github.com/hakadao/BewlyBewly/assets/33982919/97099b52-d938-45af-ac99-8beda8f5d30a)

**Comment by hakadao** [comment]
這個樣式問題

**Comment by cuiko** [comment]
> 這個樣式問題

恩，样式不一致

**Comment by hakadao** [comment]
v0.13.3已修正
