### ISSUE TITLE
希望正在关注页面能有时间轴布局，纵向布局更能聚焦最新稿件

### ISSUE THREAD

**Issue by sanchendumeng** [hakadao/BewlyBewly#107]
希望正在关注页面能有时间轴布局，纵向布局更能聚焦最新稿件

**Comment by hakadao** [comment]
你是想用這種嗎
<img width="1920" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/3329fb6b-80a9-49d8-b4b1-a8ce4ac25cc2">

**Comment by sanchendumeng** [comment]
对的

**Comment by hakadao** [comment]
我想做成左邊是up主列表可以切換up主或全部，右邊是條狀的影片卡片，這樣可以嗎

**Comment by hakadao** [comment]
新版本首頁你可以在有上角切換佈局
<img width="283" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/22101fa2-ebb2-4f61-92c6-fc9583b3d8e5">
