### ISSUE TITLE
希望首页能增加可选的播放按钮，或者延迟1至2秒再自动播放

### ISSUE THREAD

**Issue by L1102** [hakadao/BewlyBewly#160]
无意间发现这个插件，真的不错👍，但还是有一点小建议或者说希望有的功能。
当鼠标划过卡片时，能否延迟1到2秒再自动播放，或者有一个可选的播放按钮。
![image](https://github.com/hakadao/BewlyBewly/assets/75559619/40ad8f2f-b18a-4dba-8eb2-6e87bf7e7fdd)

**Comment by hakadao** [comment]
谢谢你的提议，过后添加延迟播放功能或直接禁止预览播放

**Comment by hakadao** [comment]
v0.14.0 加了延遲預覽功能可選
<img width="974" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/cb1eacc6-62c9-44dd-90e0-7a91849a2526">
