### ISSUE TITLE
[Docs] 纂写 `CONTRIBUTING.MD`

### ISSUE THREAD

**Issue by F-park** [hakadao/BewlyBewly#164]
`Readme.md` 缺少对贡献流程（具体一点的，介绍项目的编码风格， commit 规范等）的描述。应该纂写 `CONTRIBUTING.MD`，让大家更好的参与贡献。

**Comment by hakadao** [comment]
其實插件關於也能看到的，編碼風格我自己也很難説，我覺得自己之前寫的東西也是一坨屎，但又不知道怎麼改
<img width="651" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/92496445-bb75-4759-8e1d-0d6bdf5d5ad8">

**Comment by MengNianxiaoyao** [comment]
> `Readme.md` 缺少对贡献流程（具体一点的，介绍项目的编码风格， commit 规范等）的描述。应该纂写 `CONTRIBUTING.MD`，让大家更好的参与贡献。

commit规范参考`./github/workflows/changelog.yml`内的`type`

**Comment by hakadao** [comment]
已實現
