### ISSUE TITLE
网页链接打开无法跳转到视频页，并且主题失效

### ISSUE THREAD

**Issue by kokojacket** [hakadao/BewlyBewly#166]
https://www.bilibili.com/video/BV1be41127ft/
比如打开这个链接，会进入首页，不会跳转到视频页面，并且主题效果消失
![image](https://github.com/hakadao/BewlyBewly/assets/74887370/ec153310-f245-4c37-bbfb-24c5852c68c0)

**Comment by starknt** [comment]
未能复现该现象，能检查你的控制台并上传到这里？

**Comment by kokojacket** [comment]
我应该怎么做

**Comment by starknt** [comment]
> 我应该怎么做

能稳定复现该现象？如果你的插件版本不是最新的，建议你先升级一下插件，如果升级完后还是出现该现象，请提供你的详细信息？

- 浏览器版本
- 浏览器插件列表（如果你是安装新的插件后，出现该现象的）
- 提供浏览器的控制台相关信息，通常情况下，打开控制台的键盘快捷键为 `F12` 或者 `Ctrl + Shift + I`，打开后找到下图箭头类似的 `Tab`，并截图上传

![image](https://github.com/hakadao/BewlyBewly/assets/64941905/2f06fe13-92d7-4396-b56e-fda3f2eb46de)

**Comment by kokojacket** [comment]
@starknt BewlyBewly是最新版本

浏览器版本是Edge版本 120.0.2210.121 (正式版本) 

插件
![image](https://github.com/hakadao/BewlyBewly/assets/74887370/b281af17-8ede-463c-ba09-f9a587563f22)
![image](https://github.com/hakadao/BewlyBewly/assets/74887370/0ec58369-7937-49f8-be94-8a7cc7db57bc)

控制台
![image](https://github.com/hakadao/BewlyBewly/assets/74887370/59ae0f7e-d126-4b17-8a91-bbe0610dd639)

**Comment by hakadao** [comment]
能簡單描述下是怎麼觸發的嗎？是直接輸入網址還是跳轉？

**Comment by kokojacket** [comment]
鼠标单机跳转和地址直接输入网址都是这样。

**Comment by hakadao** [comment]
另外這裏能看到版本
<img width="1034" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/01129a8e-915f-4194-ad1b-00c3157050aa">

**Comment by kokojacket** [comment]
![image](https://github.com/hakadao/BewlyBewly/assets/74887370/cedb68b6-7fab-440d-a5b5-fc3bddd2d49b)

**Comment by hakadao** [comment]
> 鼠标单机跳转和地址直接输入网址都是这样。

這是在哪裏下的？chrome web store還是自己pnpm build編譯的

**Comment by kokojacket** [comment]
chrome web store

**Comment by hakadao** [comment]
我發現你這邊的地址已經和描述的不一致了，這個地址是如何打開的，可否描述下過程？
<img width="1420" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/420f353c-a8ab-4336-b16f-2330c6fd5da1">

**Comment by kokojacket** [comment]
![recording](https://github.com/hakadao/BewlyBewly/assets/74887370/2711c4dc-69b6-4667-9bc7-66779972920c)

**Comment by starknt** [comment]
可以尝试先禁用其他的插件试试

**Comment by hakadao** [comment]
https://github.com/hakadao/BewlyBewly/assets/33394391/af39fe6a-40fb-4ff0-b26a-eb3ddc837e10

**Comment by kokojacket** [comment]
我已经尝试过禁用全部插件，只留BewlyBewly，还是出现

**Comment by MengNianxiaoyao** [comment]
你这感觉还是哪个插件起冲突了

**Comment by hakadao** [comment]
能否將你最終打開的地址，不是https://www.bilibili.com/video/BV1be41127ft/ 
意思截圖中的地址發出來？

**Comment by kokojacket** [comment]
https://www.bilibili.com/?bvid=BV1be41127ft&spm_id_from=333.788.seo.out

**Comment by kokojacket** [comment]
录屏暂时保留了两个插件，Proxy SwitchyOmega，BewlyBewly
已经尝试过只保留本插件，还是会跳转到刚首页。并且插件失效

![recording](https://github.com/hakadao/BewlyBewly/assets/74887370/fa3714dc-430d-4c8d-baa7-250eac596c77)

**Comment by hakadao** [comment]
> https://www.bilibili.com/?bvid=BV1be41127ft&spm_id_from=333.788.seo.out

這個連結我就算禁用了bewlybewly純b站都無法打開

**Comment by hakadao** [comment]
你試試不用任何插件直接打開 https://www.bilibili.com/video/BV1be41127ft/ b站那邊能不能跳轉

**Comment by kokojacket** [comment]
奇怪了，还真不行。看来不是插件问题。。。。。。

**Comment by kokojacket** [comment]
无痕浏览可以打开

**Comment by hakadao** [comment]
> 无痕浏览可以打开

你是打開  https://www.bilibili.com/video/BV1be41127ft/ 嗎 ？有沒有自動跳轉到 https://www.bilibili.com/?bvid=BV1be41127ft&spm_id_from=333.788.seo.out 在打開影片頁還是其他？

**Comment by kokojacket** [comment]
无痕页面打开 https://www.bilibili.com/video/BV1be41127ft/可以跳转正常播放。懵了，家里和公司的这个edge都是这个问题。。

**Comment by starknt** [comment]
> 无痕页面打开 [https://www.bilibili.com/video/BV1be41127ft/可以跳转正常播放。懵了，家里和公司的这个edge都是这个问题。。](https://www.bilibili.com/video/BV1be41127ft/%E5%8F%AF%E4%BB%A5%E8%B7%B3%E8%BD%AC%E6%AD%A3%E5%B8%B8%E6%92%AD%E6%94%BE%E3%80%82%E6%87%B5%E4%BA%86%EF%BC%8C%E5%AE%B6%E9%87%8C%E5%92%8C%E5%85%AC%E5%8F%B8%E7%9A%84%E8%BF%99%E4%B8%AAedge%E9%83%BD%E6%98%AF%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%E3%80%82%E3%80%82)

看来 edge 真的越来越垃圾了

**Comment by kokojacket** [comment]
非常非常奇怪，我选择了重置edge之后，可以打开了，然后开启咱这个插件，一开始可以打开，过个一两分钟后，就又出现这个情况。

**Comment by MengNianxiaoyao** [comment]
> 非常非常奇怪，我选择了重置edge之后，可以打开了，然后开启咱这个插件，一开始可以打开，过个一两分钟后，就又出现这个情况。

打开`edge://flags/`，重置里面的设置试试

**Comment by kokojacket** [comment]
也重置了，我发现，即使不开任何扩展，重置之后，过一段时间也会失效。。。。看来是账户同步了某种配置。。。。

**Comment by MengNianxiaoyao** [comment]
> 也重置了，我发现，即使不开任何扩展，重置之后，过一段时间也会失效。。。。看来是账户同步了某种配置。。。。

尝试清除云同步数据，或者关闭云同步

**Comment by kokojacket** [comment]
彻底整不明白了。。。。。。。，我退出了账号，重置了浏览器，关闭所有扩展。然后打开重开浏览器。。，打开链接，进入，然后手动登录bilibili账号。关闭网页，再次打开链接，又出现了。。，太离谱了

**Comment by hakadao** [comment]
> 彻底整不明白了。。。。。。。，我退出了账号，重置了浏览器，关闭所有扩展。然后打开重开浏览器。。，打开链接，进入，然后手动登录bilibili账号。关闭网页，再次打开链接，又出现了。。，太离谱了

https://www.bilibili.com/?bvid=BV1be41127ft&spm_id_from=333.788.seo.out
我猜是b站那边的问题，后面参数spm_id_from=333.788.seo.out确实b站跳转经常会带

**Comment by kokojacket** [comment]
也清空了历史记录，cookies

**Comment by L1102** [comment]
https://www.bilibili.com/?bvid=BV1be41127ft&spm_id_from=333.788.seo.out
https://www.bilibili.com/?bvid=BV1be41127ft
我查看这两个网址插件也失效了。。。

**Comment by hakadao** [comment]
> https://www.bilibili.com/?bvid=BV1be41127ft&spm_id_from=333.788.seo.out https://www.bilibili.com/?bvid=BV1be41127ft 我查看这两个网址插件也失效了。。。

你们先确定一下不用插件是否有这个问题，这个很明显是b站问题，我下版本临时处理一下

**Comment by kokojacket** [comment]
相当于复现了吗？

**Comment by hakadao** [comment]
> 相当于复现了吗？

没有

**Comment by kokojacket** [comment]
我也觉得应该不是插件问题

**Comment by MengNianxiaoyao** [comment]
大概是b站seo有问题

**Comment by hakadao** [comment]
v0.14.0已解決

**Comment by kokojacket** [comment]
> v0.14.0已解決

不行啊。。。我还是一样

**Comment by hakadao** [comment]
> > v0.14.0已解決
> 
> 不行啊。。。我还是一样

直接訪問這個 https://www.bilibili.com/?bvid=BV1be41127ft 應該是可以的

**Comment by kokojacket** [comment]
@hakadao 无限刷新
https://file.kokojy.top:3000/share/F-fv5ZHR

**Comment by hakadao** [comment]
> @hakadao 无限刷新 https://file.kokojy.top:3000/share/F-fv5ZHR

好吧這個我沒有重現，我先把這處理去掉算了

**Comment by hakadao** [comment]
你試試把idm插件禁用一下或試試只用bewlybewly的情況

**Comment by hakadao** [comment]
我這邊真的無法重現你的問題，試試禁用其他插件再看看
https://github.com/hakadao/BewlyBewly/assets/33394391/93a0b2e4-6ca0-49c2-b3da-bac6cc245833

**Comment by hakadao** [comment]
應該是這個問題，不過我這邊又真的無法重現，更沒有無限reload問題
https://github.com/the1812/Bilibili-Evolved/discussions/4404

**Comment by MrPinku** [comment]
我的edge也有这个问题，能不能添加bilibili-evolved里面的网址参数清理功能？

**Comment by MrPinku** [comment]
> 我的edge也有这个问题，能不能添加bilibili-evolved里面的网址参数清理功能？

据说那些后缀是追踪分析用户用，我装了ClearURLs就好了，不过对性能有所影响，如果bewlybewly能内置这个功能就好了。

**Comment by hakadao** [comment]
> 我的edge也有这个问题，能不能添加bilibili-evolved里面的网址参数清理功能？

對b站功能調整的特性現在不考慮做

**Comment by MengNianxiaoyao** [comment]
> 我的edge也有这个问题，能不能添加bilibili-evolved里面的网址参数清理功能？

 可以下载bilibili-evolved并使用这个功能，不冲突的
