### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by 22Frederic** [hakadao/BewlyBewly#17]
①可以像原来的css一样设置背景吗，搜索页保持原来的，其它页面可以高斯模糊加调暗亮度处理，像这样
![屏幕截图 2023-05-02 225655](https://user-images.githubusercontent.com/105597335/235706746-e540f216-ae79-4466-8122-172a5f4e6d7a.png)

②头像打开显示等级好像不能显示出硬核会员，可以像原版一样加闪电标识

③希望悬浮视频封面可以显示预览（给一个选项开关），以及稍后再看的按钮能加回来

**Comment by hakadao** [comment]
感謝閣下的提議
1. 可以移植舊樣式的部分功能，令外高斯模糊+全背景設定有點損耗效能
2. 硬核會員標飾，這裏可能會考慮減少原版b站過多無用累積的設計，但會考慮配合插件主題調整設計顯示
3. 瀏覽和稍後再看這兩個功能會考慮製作，感謝閣下提醒

最後b站的电脑客户端不考慮美化，和製作這個插件的目的不合，還有就是改別人寫好的CSS我有ptsd

**Comment by 22Frederic** [comment]
性能我觉得还好，顶多切换过渡时会有个峰值，搞美化的多多少少应该会考虑到这点

当然，也可以提前以原图渲染好模糊图缓存给性能不好的设备使用，就是这样过渡肯定做不了了

**Comment by hakadao** [comment]
報歉這邊拖太久才實現，目前chrome上版本已經更新了，edge還在審覈
v0.2.0 已經實現的功能
- 背景設定和遮罩，模糊效果
- 頭像添加閃電標識標示硬核會員
- 稍候再看功能

暫未實現的功能
- 影片滑過預覽

另外我調整了部分寫法，應該比上一個版本流暢一點

**Comment by hakadao** [comment]
之後只剩動態頁面功能，我已經記下了，其它而實現close了
