### ISSUE TITLE
从稍后再看打开视频时自动跳转

### ISSUE THREAD

**Issue by Acidwits** [hakadao/BewlyBewly#180]
https://www.bilibili.com/list/watchlater?bvid=xxx会替换为https://www.bilibili.com/video/xxx，导致视频页面右侧无法展示稍后再看列表

**Comment by hakadao** [comment]
這個之前是處理 #166 問題加的，下版本先不處理這個先了

**Comment by cuiko** [comment]
很影响体验

**Comment by hakadao** [comment]
在改了在改了

**Comment by hakadao** [comment]
v0.14.1 已修正
