### ISSUE TITLE
v0.15.0 新功能預計實現

### ISSUE THREAD

**Issue by hakadao** [hakadao/BewlyBewly#192]
- [x] #73 
- [x] b站淨化功能
- [x] #178 
- [x] #204 
- [x] #203 
- [x] #107 
- [x] #207
- [ ] #164 
- [ ] 不喜歡推介影片功能
- [x] 視乎情況合併 #167
- [x] #314 
- [x] #362
- [x] #219
- [x] 取消消息和動態提示點（雖然在b站那邊可以關閉的但是我想還是做一個吧）
- [x] Maybe: add performance settings
- [ ] Maybe: 添加是否在當前頁面開啓連結設定
- [ ] Maybe: customized css

**Comment by silentred** [comment]
Good job bro

**Comment by hakadao** [comment]
> 顶栏加稍后就是我想要的nice静等更新。
> 
> 1. 另外顶栏能自定义项目吗？那个创作中心和投稿你懂得对我们来说多余了。
> 
> 2. 还有在首页搜索栏下面那栏。不知道叫什么栏。就是个性推荐、正在关注什么的希望也能自定义然后在里面再塞个直播
> 
> 。讲道理直播跟这几个应该一个等级的。但是每次都要从哔哩哔哩图标里面跳转。不是很合理。加一个跳转应该不费事吧。
> 
> 3. 然后就是为啥鼠标放视频上会触发不了"浮图秀"呀？不知道作者用不用这个插件。用了方便扒封面也能快速浏览封面细节。这个不改也没事啦。
> 
> 
> 
> 

1. 這個之後做
2. 我覺得這個放回頂欄比較好，暫時不改
3. 這個擴充功能我暫時沒有用過
