### ISSUE TITLE
顶栏的历史记录，跳转视频时仅up主制作视频可以跳转成功，其余皆跳转主页

### ISSUE THREAD

**Issue by Qianqianyuya** [hakadao/BewlyBewly#193]
如题，除了up制作的视频外，在顶栏历史记录中打开番剧、国创、综艺、纪录片、电影、电视剧都会跳转主页。
打开新标签页历史记录再选择点击番剧等视频不会有此问题。dock栏同理，都是打开了一个新的标签页。
附视频（二倍速略快）

https://github.com/hakadao/BewlyBewly/assets/119490911/8f24c535-8045-4cdd-bcc5-6c16f89c2e14

**Comment by hakadao** [comment]
v0.14.2已修復
