### ISSUE TITLE
【功能建议】增加首页推荐视频卡片的背景遮罩常驻功能

### ISSUE THREAD

**Issue by Seameee** [hakadao/BewlyBewly#194]
从bilibili-simple-home项目一路用过来的，这个新项目感觉性能好了很多，就是自定义项感觉比之前的项目少一点，不知道是不是并非迭代的项目。
希望可以增加首页推荐视频卡片的背景遮罩常驻功能，现在的默认字体在浅色或者深色背景下，文字可读性不太行，如果可以让背景遮罩常驻应该可以解决
![image](https://github.com/hakadao/BewlyBewly/assets/31821836/4cb27834-fada-477f-abf8-8f1d9e458ff5
![PixPin_2024-01-18_22-07-35](https://github.com/hakadao/BewlyBewly/assets/31821836/82b6f4c7-878b-4ce0-8de7-49ca2a18fac2)

**Comment by hakadao** [comment]
這裏可以選擇添加遮罩
<img width="992" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/211e324c-ae59-4548-8420-22920761b701">

**Comment by Seameee** [comment]
> 這裏可以選擇添加遮罩 <img alt="image" width="992" src="https://private-user-images.githubusercontent.com/33394391/297819000-211e324c-ae59-4548-8420-22920761b701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzQwNDksIm5iZiI6MTcwNTYzMzc0OSwicGF0aCI6Ii8zMzM5NDM5MS8yOTc4MTkwMDAtMjExZTMyNGMtYWU1OS00NTQ4LTg0MjAtMjI5MjA3NjFiNzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZDhjMjVhM2M1ZTM3NzRmNDEzZTdkZWMzYjBjZTNiZTZjZWVmZTIzOWRlZWRlODE3ZTA1NTJlN2EwY2Q0YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zq7lWLevE99IUEcXCxoQE5nwQH5wlHeTV4czeeI9viA">

这个我晓得，我的意思是首页推荐的卡片可以固定显示这个选中后的背景遮罩么
![image](https://github.com/hakadao/BewlyBewly/assets/31821836/7526e381-4352-4659-b9be-634cc26049d4)

**Comment by hakadao** [comment]
沒別要，改過後對效能影響還是有點大的
