### ISSUE TITLE
网上冲浪看到这个美妙的插件，想问下能否支援火狐

### ISSUE THREAD

**Issue by eric2788** [hakadao/BewlyBewly#2]
火狐可以直接透过 API sign extension 而无需上传到商店就可以直接安装xpi，不过 chrome 扩展和火狐扩展是不兼容的，可能需要 webextension-polyfill 之类的 library 协助

如果觉得太麻烦就算了

**Comment by hakadao** [comment]
其實應該是可以支援 Firefox 的，因為此專案所用的模板就是有兼容的 https://github.com/antfu/vitesse-webext

不過 Firefox 好像不能顯示毛玻璃效果

**Comment by eric2788** [comment]
那....你愿意签署成xpi吗？因为火狐安装未封装的扩展下次打开浏览器就没了

**Comment by hakadao** [comment]
可以，不過我一次都沒有用過 Firefox 測試，看看多不多bug先 orz

**Comment by eric2788** [comment]
![image](https://user-images.githubusercontent.com/6276840/162456471-9da6be52-321d-42ec-b0b4-4500c401ae06.png)
效果如上（github图）
就这么看是没问题
有什么想让我测试的？可以说一下

**Comment by eric2788** [comment]
我发现没有对这个视频没有兴趣的按钮，不知道本身有没有这个东西，但我觉得有会比较好（像油管一样）

**Comment by hakadao** [comment]
要取得access key授權先，這用的是app的API首頁接口。
今日我用Firefox測了半天都是莫名奇妙的Referrer Policy: Less restricted policies錯誤

**Comment by hakadao** [comment]
推介API用的是，獲取accesskey的方法也是~~抄~~ 參考這個的https://github.com/SocialSisterYi/bilibili-API-collect

**Comment by eric2788** [comment]
![image](https://user-images.githubusercontent.com/6276840/162459731-4f68afa6-bcfb-4058-be63-74936f261e07.png)

**Comment by hakadao** [comment]
@eric2788 是呀，chrome，edge沒有此問題

**Comment by eric2788** [comment]
> @eric2788 是呀，chrome，edge沒有此問題

是指这个截图报错，还是没有不感兴趣的按钮

**Comment by hakadao** [comment]
@eric2788 暫時沒做不感興趣，這個錯誤chrome沒有遇到過，我也不知道甚麼原因orz

**Comment by hakadao** [comment]
現在授權accesskey的按鈕判斷有點問題，解決了這個bug後會做這個功能

**Comment by eric2788** [comment]
移除扩展后就没看到那个错误了，不过那个错误是会影响什么的？
![image](https://user-images.githubusercontent.com/6276840/162466787-7cedbac4-3d19-4e46-b449-fc77d03eb745.png)

**Comment by hakadao** [comment]
@eric2788 這是原本主站的腳本，對這個插件應該沒有甚麼影響

**Comment by hakadao** [comment]
修正了 #3

**Comment by eric2788** [comment]
好的謝謝了，剩下應該沒啥問題了，就等你提供xpi了
不感興趣按鈕那會放todo list麼

**Comment by hakadao** [comment]
不感興趣功能是一定會做的
另外這個bug你這裏有沒有出現，現在都在煩這個問題
<img width="670" alt="image" src="https://user-images.githubusercontent.com/33394391/162554259-52282239-1687-4c93-a257-674a465087ca.png">

**Comment by eric2788** [comment]
> 不感興趣功能是一定會做的
> 另外這個bug你這裏有沒有出現，現在都在煩這個問題
> <img width="670" alt="image" src="https://user-images.githubusercontent.com/33394391/162554259-52282239-1687-4c93-a257-674a465087ca.png">
> 

開首頁沒有 是什麼情況下會出現？

**Comment by clover-yan** [comment]
請問對 Firefox 的支援現在進度如何了？

**Comment by hakadao** [comment]
> 請問對 Firefox 的支援現在進度如何了？

dev-firefox 分支自己可以自己編譯用，但是還是有點問題沒有處理並且沒有精力研究目前

**Comment by clover-yan** [comment]
> > 請問對 Firefox 的支援現在進度如何了？
> 
> dev-firefox 分支自己可以自己編譯用，但是還是有點問題沒有處理並且沒有精力研究目前

@hakadao 我不是 NPM 開發人員，開了個 Codespace，嘗試按照 README 編譯成功，但是打包 extension 資料夾之後置入 Firefox 之後提示附加組件損壞，想問一下是需要什麼額外步驟嗎？

**Comment by hakadao** [comment]
> > > 請問對 Firefox 的支援現在進度如何了？
> 
> > 
> 
> > dev-firefox 分支自己可以自己編譯用，但是還是有點問題沒有處理並且沒有精力研究目前
> 
> 
> 
> @hakadao 我不是 NPM 開發人員，開了個 Codespace，嘗試按照 README 編譯成功，但是打包 extension 資料夾置入 Firefox 之後提示附加組件損壞，想問一下是需要什麼額外步驟嗎？

firefox的話要執行 npm run build-firefox 指令，再打包 extension-firefox

**Comment by clover-yan** [comment]
@hakadao 感谢极快的回复！编译成功了，打包如下供大家参考，需要解压缩之后安装 xpi 档。

[bewly@khyan.top.zip](https://github.com/hakadao/BewlyBewly/files/14291397/bewly%40khyan.top.zip)

**Comment by jqtmviyu** [comment]
基于commit  a7c60e65b99b40ebc8d359ba246c31086e5a1e66 打包, 安装失败, 初步发现 缺少了 `META-INF` 文件夹, 
从 [bewly@khyan.top.zip](https://github.com/hakadao/BewlyBewly/files/14291397/bewly%40khyan.top.zip) 拷贝一份就可以装上了

**Comment by hakadao** [comment]
已經上傳到firefox商店了,等待審覈,介面上可能還有些問題要調整,後續慢慢改

**Comment by hakadao** [comment]
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/c4a4c34d-b0a0-487b-839e-859638ae20f5)

**Comment by hakadao** [comment]
下一版本將正式支援firefox,之前千年老問題解決了...

**Comment by hakadao** [comment]
firefox 版本正式上架，十分抱歉拖太久這個問題，目前 var() and calc() 混用在 firefox 好像有點問題導致部分樣式變位的情況，暫時不知如何處理
https://addons.mozilla.org/en-US/firefox/addon/bewlybewly/

**Comment by clover-yan** [comment]
@Lightmarey, @lsh7d1, @desktop4025, @product-think2049, @Mark24Code, @AlphaCatMeow, @6gdfg, @ChenXiaoming233, @jqtmviyu, and @xxt115,

各位好，因为你们有点赞我发布预打包 BewlyBewly 的[评论](https://github.com/hakadao/BewlyBewly/issues/2#issuecomment-1945339582)，所以打扰一下。

正式版的 BewlyBewly 已经上架，请参看本议题里上面的内容。如果要换用最新版，请先打开哔哩哔哩首页，然后在 BewlyBewly 设置界面的关于栏目导出配置，卸载当前版本并安装商店版本之后再导入。**正式版本仍然还需要在扩展管理页面把开关都打开才能正常使用。**

**Comment by ChenXiaoming233** [comment]
好的捏 已经开始用了
________________________________
发件人: ***@***.*** ***@***.***> 代表 clover_yan ***@***.***>
发送时间: 2024年4月20日 20:56
收件人: hakadao/BewlyBewly ***@***.***>
抄送: Chen Xiaoming ***@***.***>; Mention ***@***.***>
主题: Re: [hakadao/BewlyBewly] 网上冲浪看到这个美妙的插件，想问下能否支援火狐 (Issue #2)


@Lightmarey<https://github.com/Lightmarey>, @lsh7d1<https://github.com/lsh7d1>, @desktop4025<https://github.com/desktop4025>, @product-think2049<https://github.com/product-think2049>, @Mark24Code<https://github.com/Mark24Code>, @AlphaCatMeow<https://github.com/AlphaCatMeow>, @6gdfg<https://github.com/6gdfg>, @ChenXiaoming233<https://github.com/ChenXiaoming233>, @jqtmviyu<https://github.com/jqtmviyu>, and @xxt115<https://github.com/xxt115>,

各位好，因为你们有点赞我发布预打包 BewlyBewly 的评论<https://github.com/hakadao/BewlyBewly/issues/2#issuecomment-1945339582>，所以打扰一下。

正式版的 BewlyBewly 已经上架，请参看本议题里上面的内容。如果要换用最新版，请先打开哔哩哔哩首页，然后在 BewlyBewly 设置界面的关于栏目导出配置，卸载当前版本并安装商店版本之后再导入。正式版本仍然还需要在扩展管理页面把开关都打开才能正常使用。

―
