### ISSUE TITLE
vimium C插件识别不到网页中的按钮

### ISSUE THREAD

**Issue by iKineticate** [hakadao/BewlyBewly#20]
问题：vimium C扩展插件的功能（点击网页中的链接和按钮）识别不到B站网页的按钮
疑问：是因为按钮格式跟平常按钮不一样引起的吗？@_@

**Comment by hakadao** [comment]
我記得頁面的按鈕這裏是直接用div實現的，不知道是不是這個引起的

**Comment by iKineticate** [comment]
好像是因为这个原因吧，感谢回答



> 我記得頁面的按鈕這裏是直接用div實現的，不知道是不是這個引起的
