### ISSUE TITLE
建议：暗色模式下，视频播放页面下滑后，用户评论处有一圈白框能否去掉（强迫症患者。。）

### ISSUE THREAD

**Issue by WTusFF** [hakadao/BewlyBewly#200]
建议：暗色模式下，视频播放页面下滑后，用户评论处有一圈白框能否去掉（强迫症患者。。）
![微信图片_20240119150652](https://github.com/hakadao/BewlyBewly/assets/157100147/4b37609c-e2c9-4464-9120-1dc2d1ead3e6)

**Comment by hakadao** [comment]
早修復了，edge那邊是慢點的，用chrome的那邊下載吧
