### ISSUE TITLE
[建议]希望增强HTML标签的规范性

### ISSUE THREAD

**Issue by lainbo** [hakadao/BewlyBewly#204]
期望优化视频卡片的<a>标签包裹范围和添加属性。

我发现视频卡片多是div, a标签只包含了视频卡片的图片部分, 这导致了无法使用鼠标中键点击整个卡片在后台打开标签页。如果使用 window.open 的方式，但是没有传noreferrer或noopener的参数，就会导致新页面会复用父页面的渲染进程, 也就意味着将共用同一主线程，包括页面渲染流程，JavaScript执行，用户交互事件响应等所有页面任务都会在同一个主线程上执行。

官方把这个默认策略叫 process-per-site-instance。打开新页面其实有一个技巧。使用 `<a target="_blank" rel="noopener noreferrer">文字</a >` 或 `window.open(url, target, "noopener,noreferrer")` 的方式新开窗口, 此时，对应的 Tab 页面会开启独立进程。

期望可以对a标签进行优化

**Comment by hakadao** [comment]
在bugfixes分支實現了，過後放個小版本更新

**Comment by hakadao** [comment]
v0.14.6 已修正
