### ISSUE TITLE
[BUG] 在动态页面使用「顶部」按钮回到最上方时「顶栏」无法正确显示

### ISSUE THREAD

**Issue by CCBP** [hakadao/BewlyBewly#205]
在设置种开启「自动隐藏顶栏」选项并向下滚动一段距离顶栏自动隐藏后，使用页面右下角的「顶部」按钮回到最上方时「顶栏」无法正确显示，重新滚动页面后可恢复。
![0](https://github.com/hakadao/BewlyBewly/assets/22212160/1c03fd85-53ad-4f91-993d-72e8580ae528)
![1](https://github.com/hakadao/BewlyBewly/assets/22212160/1ce892d6-4133-4e98-a9df-00feba381d01)

**Comment by hakadao** [comment]
v0.14.3 已修正
