### ISSUE TITLE
夜间模式下，部分页面的字符颜色显示异常

### ISSUE THREAD

**Issue by miracomangomanchuria** [hakadao/BewlyBewly#206]
https://www.bilibili.com/v/popular/weekly/?num=251

<img width="1272" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/18415539/bec0f259-5f36-41a3-8a2c-1b4c72c68c40">

**Comment by hakadao** [comment]
這個頁面我不太想適配其實，之後寫個正則過濾掉防止影響

**Comment by hakadao** [comment]
暫時先過濾了這頁面。。。過後適配
