### ISSUE TITLE
消息ui显示bug

### ISSUE THREAD

**Issue by lxdklp** [hakadao/BewlyBewly#21]
不稳定触发，我也不知道该贴什么日志💦大大可以提一下下次遇到了就贴上
![屏幕截图 2023-07-16 021123](https://github.com/hakadao/BewlyBewly/assets/69453767/1b0ef983-60bb-4405-8d24-f75bd5799ac1)

**Comment by hakadao** [comment]
沒事我之前也遇到過，但是總是忘記這個問題，之後看看

**Comment by lxdklp** [comment]
> 沒事我之前也遇到過，但是總是忘記這個問題，之後看看
> 
> 這是哪個版本的

0.2.0

**Comment by lxdklp** [comment]
> 沒事我之前也遇到過，但是總是忘記這個問題，之後看看
> 
> 這是哪個版本的

不好意思没注意，应该是0.2.0或者0.1.1

**Comment by hakadao** [comment]
我已經知道問題了，下版本會修復

**Comment by hakadao** [comment]
v0.3.0已修正

**Comment by lxdklp** [comment]
似乎依旧未修复
![屏幕截图 2023-07-28 195745](https://github.com/hakadao/BewlyBewly/assets/69453767/4d6b4de7-1e27-47f4-bf75-daa853b56094)
![屏幕截图 2023-07-28 195759](https://github.com/hakadao/BewlyBewly/assets/69453767/188acab9-9899-41c5-bff6-5051bbe4b7c0)

**Comment by hakadao** [comment]
uhhhh，我暫時不知道怎麼解決，先記一記吧

**Comment by hakadao** [comment]
0.4.0版本調了一下，chrome web store那邊已經更新了，github中午更新一下版本說明
