### ISSUE TITLE
控制栏

### ISSUE THREAD

**Issue by izvvv** [hakadao/BewlyBewly#212]
视频卡片的控制栏打开后，只在推荐页的视频卡片中显示，在关注页及关键字搜索后的视频页中的视频卡片中不显示
![image](https://github.com/hakadao/BewlyBewly/assets/78134574/79a86700-1328-4b27-ac98-56a153058555)
![image](https://github.com/hakadao/BewlyBewly/assets/78134574/4dc11d88-9aae-454d-a692-b5f7dfdcbb78)

**Comment by izvvv** [comment]
![image](https://github.com/hakadao/BewlyBewly/assets/78134574/14fd4020-bf20-4751-82ff-6fbf7a01047c)
以及该页面无法加载

**Comment by hakadao** [comment]
因為只是bewlybewly頁面生效，b站原本的頁面不會做特殊處理

**Comment by izvvv** [comment]
> 因為只是bewlybewly頁面生效，b站原本的頁面不會做特殊處理

是否可以实现搜索页面中的视频卡片含有控制栏

**Comment by hakadao** [comment]
> > 因為只是bewlybewly頁面生效，b站原本的頁面不會做特殊處理
> 
> 是否可以实现搜索页面中的视频卡片含有控制栏

這個暫時不會考慮實現
