### ISSUE TITLE
[建议] 希望在“搜索页模式” 下加入“分区”功能

### ISSUE THREAD

**Issue by xtwu9** [hakadao/BewlyBewly#219]
**1. 遇到的问题：**

> (1) 当开启“搜索页模式”时，首页顶部的“BiliBili”标签消失，无法点击并选择分区。

![搜索页顶部](https://github.com/hakadao/BewlyBewly/assets/44873243/e5eb84c2-9b11-4b10-b614-5b4d3ec0608a)

> (2) 只有当向下滑动至首页内容页，再向上滑动时，“BiliBili”分区功能才会出现。

![其他情况](https://github.com/hakadao/BewlyBewly/assets/44873243/596ff649-81dc-4300-9438-cf30f7ddb4ac)

 **2. 我的建议：**

希望可以在开启“搜索页模式”下，在中间的“BiliBili” logo中或其他位置（例如Dock栏或顶栏），加入“分区”模块。

_**很抱歉打扰到作者，BewlyBewly是我用过最好的插件，希望它会变得更好！**_

**Comment by hakadao** [comment]
這是故意做成這樣的，爲了簡潔。後面加個開關設定吧
