### ISSUE TITLE
增加开关搜索历史的功能，以及一些其他建议

### ISSUE THREAD

**Issue by huanfe1** [hakadao/BewlyBewly#221]
1. 增加开关搜索历史的功能
2. 右上角按钮栏在新窗口打开
3. 增加开关消息按钮上的小红点
4. 配置同步可以考虑浏览器同步和 WebDAV
![image](https://github.com/hakadao/BewlyBewly/assets/41602338/29d5c5b3-c6d4-43ad-8ed2-bed589674825)

最后，项目很棒！

**Comment by hakadao** [comment]
1. 感覺沒有必要，反正只是存本地的
2. 首頁點擊右上按鈕欄就已經是新窗口打開，其他頁面打開是當前頁面，防止開太多tab
3. 可以，之後加這開關
4. 是指雲端同步嗎？暫時沒有打算
