### ISSUE TITLE
首页电脑端和手机端推荐切换

### ISSUE THREAD

**Issue by 1553209099** [hakadao/BewlyBewly#222]
![QQ截图20240125110254](https://github.com/hakadao/BewlyBewly/assets/85204300/e75dcf95-18b4-4afc-8a6d-5fd3a3b97b63)
![QQ截图20240125110520](https://github.com/hakadao/BewlyBewly/assets/85204300/fe1e673e-1bb0-463f-bbd8-56746390b789)
可以在首页添加电脑端和手机端的推荐切换吗？类似于bilibili-app-recommend脚本这样，因为用了之后，bilibili-app-recommend这个脚本就失效了

**Comment by MengNianxiaoyao** [comment]
可以使用原版b站首页功能搭配bilibili-app-recommend

**Comment by hakadao** [comment]
我感覺做切換的意義不大，單獨開一個tab沒有必要
