### ISSUE TITLE
顶栏的历史记录，无法正确跳转到对应分p 

### ISSUE THREAD

**Issue by douseful** [hakadao/BewlyBewly#223]
https://github.com/hakadao/BewlyBewly/assets/52767905/29ac7ddb-ead9-41de-a759-887db04a2fad

如视频所示，从顶栏历史记录入口点击视频 直接跳转到了视频合集的最开始。

**Comment by douseful** [comment]
如果视频没有合集（仅有单个视频），顶栏的历史记录可以正常工作。

**Comment by douseful** [comment]
https://github.com/hakadao/BewlyBewly/assets/52767905/7834ec33-c838-4085-88c7-84997cc4d2ed

禁用插件后，功能正常。

**Comment by hakadao** [comment]
0.14.4已修正，如果你是chrome那邊下的話過後就能收到更新
