### ISSUE TITLE
中键新开页面的疑问

### ISSUE THREAD

**Issue by bjy20070709** [hakadao/BewlyBewly#227]
个人浏览B站的习惯是中键后台新标签点开感兴趣的视频逐一浏览，使用本插件后无法实现这一操作。
请问是个人设置问题还是可以增加的功能特性？

**Comment by hakadao** [comment]
目前首頁內容是可以中鍵新開頁面的

**Comment by bjy20070709** [comment]
> 目前首頁內容是可以中鍵新開頁面的

的确是的，谢谢回复~
