### ISSUE TITLE
[BUG?]右上角动态中，视频发布时间似乎存在问题

### ISSUE THREAD

**Issue by ishkong** [hakadao/BewlyBewly#237]
使用的是chrome商店版本
版本
0.14.3
chrome版本 121.0.6167.86（正式版本） （64 位）
这是主题的显示<img width="1039" alt="{6C39E348-D07B-4017-B78A-B143E8878CAE}" src="https://github.com/hakadao/BewlyBewly/assets/19740260/bf0b091a-fabf-4864-a1d3-fe8037eb86bd">
这是B站原版的显示<img width="1143" alt="{3055AB6A-9AC7-4db9-95CC-E9E20DB3C1DF}" src="https://github.com/hakadao/BewlyBewly/assets/19740260/e8717f04-bf55-4fec-8bfb-25aa22e293bc">

**Comment by hakadao** [comment]
errrrr，這個問題之後解決

**Comment by hakadao** [comment]
測了一下好像沒有甚麼問題這裡
<img width="855" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/724d1858-a98f-4063-aa9e-36016776fc27">

**Comment by ishkong** [comment]
<img width="1088" alt="{0D1E59D5-9E65-4212-902F-2DC51D55BC1C}" src="https://github.com/hakadao/BewlyBewly/assets/19740260/399afcaa-4f6a-423e-b53e-21be595d1eb8">
<img width="1033" alt="{E98FC228-6FAB-4cc1-97B6-67BE3924C126}" src="https://github.com/hakadao/BewlyBewly/assets/19740260/cbbd2366-405e-4d95-8d34-a00943bb1822">
也不是所有视频都是异常的，也有正常显示的
我还能提供哪些额外信息帮助你判断吗？

**Comment by hakadao** [comment]
到時候我換新的動態接口吧，之前用的是舊的之後應該就沒有這個問題了

**Comment by ishkong** [comment]
> 到時候我換新的動態接口吧，之前用的是舊的之後應該就沒有這個問題了

好的，谢谢

**Comment by hakadao** [comment]
已修復
