### ISSUE TITLE
视频下方按钮被遮挡

### ISSUE THREAD

**Issue by begierde** [hakadao/BewlyBewly#240]
<img width="763" alt="截屏2024-01-29 上午10 53 36" src="https://github.com/hakadao/BewlyBewly/assets/54112668/81c34c3b-c720-4aaa-a3a9-906da00c7088">

视频下方控制条的 网页全屏按钮被遮挡
macos-chrome

**Comment by hakadao** [comment]
有對應的bv號可以給出嗎

**Comment by begierde** [comment]
BV1ye411m72Q

**Comment by hakadao** [comment]
<img width="1201" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/bb31d0aa-9ac9-43d4-b2ac-19cf17588de8">
我這裡沒有hi-res無損標識啊

**Comment by MengNianxiaoyao** [comment]
有没有使用其它插件或者脚本？
