### ISSUE TITLE
添加直播页面

### ISSUE THREAD

**Issue by suyeshuye** [hakadao/BewlyBewly#242]

**Comment by hakadao** [comment]
不打算適配，平時很少用或不用直播，也不知道改些甚麼

**Comment by suyeshuye** [comment]
> 不打算適配，平時很少用或不用直播，也不知道改些甚麼不打算适配，平时很少用或不用直播，也不知道改些什么

哈哈好的 或许可以添加一个关注的up正在直播的页面 类似下图这种
![PixPin_2024-01-30_17-48-45](https://github.com/hakadao/BewlyBewly/assets/120745619/ef5d4e5d-80fa-454b-88bd-4850214eb437)

**Comment by suyeshuye** [comment]
另外我在首页滚动页面的时候有些卡顿不是很丝滑，不知道是我电脑的原因还是脚本自身的问题

**Comment by hakadao** [comment]
> 另外我在首页滚动页面的时候有些卡顿不是很丝滑，不知道是我电脑的原因还是脚本自身的问题

正常如果沒有設定背景和遮罩和模糊和搜尋頁模式應該不會太卡

**Comment by hakadao** [comment]
> > 不打算適配，平時很少用或不用直播，也不知道改些甚麼不打算适配，平时很少用或不用直播，也不知道改些什么
> 
> 哈哈好的 或许可以添加一个关注的up正在直播的页面 类似下图这种 ![PixPin_2024-01-30_17-48-45](https://private-user-images.githubusercontent.com/120745619/300756795-ef5d4e5d-80fa-454b-88bd-4850214eb437.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDkyMDYsIm5iZiI6MTcwNjYwODkwNiwicGF0aCI6Ii8xMjA3NDU2MTkvMzAwNzU2Nzk1LWVmNWQ0ZTVkLTgwZmEtNDU0Yi04OGJkLTQ4NTAyMTRlYjQzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMDAxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzlhNmYxMTY5ODkxZjgzZWIyZDQ0YzJjYjMxZmExNWExOTJiNzBkYjliYzFkYWQwYWQ2MzA1YTgzNjQ1ZGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kqe_qKNRQUfaYICmj01KYmE4mcncmhwE80wg3anAsGM)

之後我把首頁的關注選項卡調整一下加個提示或其他東西展現吧

**Comment by suyeshuye** [comment]
> > 另外我在首页滚动页面的时候有些卡顿不是很丝滑，不知道是我电脑的原因还是脚本自身的问题
> 
> 正常如果沒有設定背景和遮罩和模糊和搜尋頁模式應該不會太卡正常如果没有设定背景和遮罩和模糊和搜寻页模式应该不会太卡

这些我都没有设置欸 但是还是卡顿 很奇怪

**Comment by suyeshuye** [comment]
> > > 不打算適配，平時很少用或不用直播，也不知道改些甚麼不打算适配，平时很少用或不用直播，也不知道改些什么不打算适配，平时很少用或不用直播，也不知道改些什么不打算适配，平时很少用或不用直播，也不知道改些什么
> > 
> > 
> > 哈哈好的 或许可以添加一个关注的up正在直播的页面 类似下图这种 <img alt="PixPin_2024-01-30_17-48-45" width="192.4875030517578" height="21" src="https://private-user-images.githubusercontent.com/120745619/300756795-ef5d4e5d-80fa-454b-88bd-4850214eb437.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDkyMDYsIm5iZiI6MTcwNjYwODkwNiwicGF0aCI6Ii8xMjA3NDU2MTkvMzAwNzU2Nzk1LWVmNWQ0ZTVkLTgwZmEtNDU0Yi04OGJkLTQ4NTAyMTRlYjQzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMDAxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzlhNmYxMTY5ODkxZjgzZWIyZDQ0YzJjYjMxZmExNWExOTJiNzBkYjliYzFkYWQwYWQ2MzA1YTgzNjQ1ZGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kqe_qKNRQUfaYICmj01KYmE4mcncmhwE80wg3anAsGM">
> 
> 之後我把首頁的關注選項卡調整一下加個提示或其他東西展現吧之后我把首页的关注选项卡调整一下加个提示或其他东西展现吧

感谢 麻烦大神了

**Comment by suyeshuye** [comment]
> > > 另外我在首页滚动页面的时候有些卡顿不是很丝滑，不知道是我电脑的原因还是脚本自身的问题
> > 
> > 
> > 正常如果沒有設定背景和遮罩和模糊和搜尋頁模式應該不會太卡正常如果没有设定背景和遮罩和模糊和搜寻页模式应该不会太卡
> 
> 这些我都没有设置欸 但是还是卡顿 很奇怪

更新了浏览器的版本，现在不卡了，应该是我之前的浏览器版本过低的原因
