### ISSUE TITLE
首页推介点击番剧卡片时跳转到主页

### ISSUE THREAD

**Issue by xiaojiejieouo** [hakadao/BewlyBewly#247]
我发现在主站内推送的番剧无法直接打开,[
![image](https://github.com/hakadao/BewlyBewly/assets/78160136/fddafcfc-42f0-4999-a161-21a9e590adba)
](url)
如果点击图片会重新打开一个b站的主页

**Comment by hakadao** [comment]
我這邊暫時無法推送番劇首頁，暫時不知道怎麼改

**Comment by demonsaidhelloworld** [comment]
不只是番剧，纪录片、剧集等点击后也会直接新标签页打开b站主页

**Comment by L33Z22L11** [comment]
我遇到了相同问题。
本来打算新建issue，经搜索发现 #193 是类似问题，但已解决。建议修改issue标题为故障名称，便于查找，同时减少他人提出重复issue的概率。

**Comment by hakadao** [comment]
> 我遇到了相同问题。
> 
> 本来打算新建issue，经搜索发现 #193 是类似问题，但已解决。建议修改issue标题为故障名称，便于查找，同时减少他人提出重复issue的概率。

這不是同一問題，頂欄和首頁是不同的

**Comment by xiaojiejieouo** [comment]
qwq辛苦了

**Comment by L33Z22L11** [comment]
> > 我遇到了相同问题。
> > 本来打算新建issue，经搜索发现 #193 是类似问题，但已解决。建议修改issue标题为故障名称，便于查找，同时减少他人提出重复issue的概率。
> 
> 這不是同一問題，頂欄和首頁是不同的

我遇到的`相同`问题是这个issue指出的问题，即主页推送流中，插件生成的番剧类视频卡片的`<a>`标签`href`属性为空，点击会跳转到主页。
`类似`指这个故障的表现与 #193 类似，都是点击番剧等链接后，跳转到主页。

**Comment by hakadao** [comment]
> > > 我遇到了相同问题。
> > > 本来打算新建issue，经搜索发现 #193 是类似问题，但已解决。建议修改issue标题为故障名称，便于查找，同时减少他人提出重复issue的概率。
> > 
> > 
> > 這不是同一問題，頂欄和首頁是不同的
> 
> 我遇到的`相同`问题是这个issue指出的问题，即主页推送流中，插件生成的番剧类视频卡片的`<a>`标签`href`属性为空，点击会跳转到主页。 `类似`指这个故障的表现与 #193 类似，都是点击番剧等链接后，跳转到主页。

這裏處理的部分完全不同，也不算重複

**Comment by L33Z22L11** [comment]
> 這裏處理的部分完全不同，也不算重複

抱歉，我是想表达自己差点建立了一个重复的issue。

我已修改自己之前的表述，感谢你的热心解答。
