### ISSUE TITLE
单独为搜索页设置背景无法使用

### ISSUE THREAD

**Issue by 22Frederic** [hakadao/BewlyBewly#25]
0.5.0，使用URL设置无法生效，内置背景正常
![屏幕截图 2023-08-17 125949](https://github.com/hakadao/BewlyBewly/assets/105597335/ccc406bf-78cc-47db-9ec1-d2fa5310fe53)

**Comment by hakadao** [comment]
好像確實是這樣,今晚看看

**Comment by hakadao** [comment]
好，今晚一起调整一下

**Comment by hakadao** [comment]
v0.6.0版本以上問題已處理
