### ISSUE TITLE
[BUG] 使用暗色模式下，个人收藏管理页视频移动收藏界面渲染错误

### ISSUE THREAD

**Issue by Reptilelizard** [hakadao/BewlyBewly#259]
# 亮色模式: 
![6Y%1P49 MSE7W~B I1`YO0F](https://github.com/hakadao/BewlyBewly/assets/90090388/aacedc73-62b0-4207-bd18-a948e0ff1a47)

# 暗色模式:
![HCV_~_ X)J8E%J1FTLM~U}4](https://github.com/hakadao/BewlyBewly/assets/90090388/80a4d529-77ba-4373-97da-ba73951db1e6)
下图为鼠标放在"待整理"收藏夹上的效果
![LBH)_3B~BJYYAX$ WJAE}X4](https://github.com/hakadao/BewlyBewly/assets/90090388/8b366b6c-c589-44aa-81c1-65762389b0f1)

**Comment by hakadao** [comment]
v0.14.5已修復
