### ISSUE TITLE
暗色模式下，笔记页面异常

### ISSUE THREAD

**Issue by xy770** [hakadao/BewlyBewly#262]
### 暗色模式
![image](https://github.com/hakadao/BewlyBewly/assets/120915856/01706e85-aa11-43c6-ad36-2e8121019a8a)
### 亮色模式
![image](https://github.com/hakadao/BewlyBewly/assets/120915856/812fd752-230b-471e-a76a-daa535a31489)

**Comment by hakadao** [comment]
方便放一個筆記頁面嗎？

**Comment by xy770** [comment]
https://www.bilibili.com/video/BV1B7411A7M1
![image](https://github.com/hakadao/BewlyBewly/assets/120915856/9213c083-0512-4ac1-ac2d-b378cb42c6bc)

**Comment by hakadao** [comment]
v0.14.5已修復
