### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by xiaorandada5** [hakadao/BewlyBewly#264]
1.在搜索栏的放大镜左侧，可以放一个×吗，用来清除搜索栏里的内容，有时候回到主页手不在键盘上放着就习惯用那个键按钮了。
2.背景可以调用电脑里的图片自定义吗。
还有您的这个插件真的真的很漂亮，圆角矩形和毛玻璃让我有一种手机系统的感觉，比原生好看太多了。

**Comment by hakadao** [comment]
1. 已經加了，後續中版本更新會有
2. 之後研究一下這個
