### ISSUE TITLE
右上角胶囊跳转问题

### ISSUE THREAD

**Issue by xiaofeiTM233** [hakadao/BewlyBewly#265]
右上角胶囊跳转设置错误，应为打开新标签页跳转，而不是将本页面跳转
由于B站跳转无确认，易丢失当前页面信息

**Comment by hakadao** [comment]
故意做成這樣的，防止總是新開標籤頁
只有首頁點開是開新標籤頁，其他基本是在當前頁跳轉

**Comment by xiaofeiTM233** [comment]
> 防止總是新開標籤頁
不新开标签页的后果是码了10分钟的字没了（
如果有人需要在当前页打开的话整个设置？因为B站默认点击是新开标签页，适应还是不习惯……

**Comment by hakadao** [comment]
這個後期做吧，因為改這個很多要調

> > 防止總是新開標籤頁
> 
> 不新开标签页的后果是码了10分钟的字没了（ 如果有人需要在当前页打开的话整个设置？因为B站默认点击是新开标签页，适应还是不习惯……
