### ISSUE TITLE
變更收藏夾左欄顏色

### ISSUE THREAD

**Issue by as1918575822** [hakadao/BewlyBewly#268]
![730CDC5477A6C688B093DD0639D9CE57](https://github.com/hakadao/BewlyBewly/assets/105956633/aaa0126f-5994-41b5-ac9e-e5cb776776d4)

**Comment by hakadao** [comment]
暫時沒能理解閣下的意思

**Comment by as1918575822** [comment]
> 暂时无法理解的意思

![image](https://github.com/hakadao/BewlyBewly/assets/105956633/7c2c3fd3-e2a8-49a3-9975-21e482f1fc94)

**Comment by hakadao** [comment]
是想鼠標滑過時加個背景色還是甚麼？

**Comment by as1918575822** [comment]
> 是想鼠标滑过时加个背景色还是什么？

能不能把那点灰的弄成白的？
