### ISSUE TITLE
suggestion：希望可以自定义显示哪些选项，及顺序。

### ISSUE THREAD

**Issue by 1551255004** [hakadao/BewlyBewly#269]
比如首页这里的个性推荐、正在关注、····
我想首先显示正在关注的，随后可以手动选择个性推荐，另外后边的订阅剧集则是我不需要的。
<img width="584" alt="Snipaste_2024-02-03_09-31-12" src="https://github.com/hakadao/BewlyBewly/assets/66911217/431206b5-4828-415b-beda-ba093e2f1a69">

另外还有侧边栏的按钮，这个到是可以进行排序，但目前不能取消某一个的显示，比如取消番剧。

**Comment by cloudflypeng** [comment]
is anyone doing this, i want do it

**Comment by hakadao** [comment]
> is anyone doing this, i want do it

if you wanna add this feature, please use the dev branch for implementation :)

**Comment by cloudflypeng** [comment]
![image](https://github.com/hakadao/BewlyBewly/assets/44285412/162b599e-4301-47b6-9343-4a819b8ef241)

It's coming soon

**Comment by cloudflypeng** [comment]
> > is anyone doing this, i want do it
> 
> if you wanna add this feature, please use the dev branch for implementation :)

I have completed it, waiting merge

**Comment by hakadao** [comment]
> ![image](https://private-user-images.githubusercontent.com/44285412/306142642-162b599e-4301-47b6-9343-4a819b8ef241.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTI0NDQsIm5iZiI6MTcwODQxMjE0NCwicGF0aCI6Ii80NDI4NTQxMi8zMDYxNDI2NDItMTYyYjU5OWUtNDMwMS00N2I2LTkzNDMtNGE4MTliOGVmMjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA2NTU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwODMyNDZhNzEzNDVhNGRjMDgwMjE2MDkyNzdjZGU0ZTFhNWU3NzBiMDRlMDc0ZTExMDU2Y2MzMTE0NjMzZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yx1uy2f0TYi0kvghFb2E7YBRV0hx3l1bkBuQgkXCPao)
> 
> It's coming soon

Could you remove the default home tab configuration? Just like the dock content configuration, the first tab will become the default tab on the homepage

**Comment by cloudflypeng** [comment]
> > ![image](https://private-user-images.githubusercontent.com/44285412/306142642-162b599e-4301-47b6-9343-4a819b8ef241.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTI0NDQsIm5iZiI6MTcwODQxMjE0NCwicGF0aCI6Ii80NDI4NTQxMi8zMDYxNDI2NDItMTYyYjU5OWUtNDMwMS00N2I2LTkzNDMtNGE4MTliOGVmMjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA2NTU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwODMyNDZhNzEzNDVhNGRjMDgwMjE2MDkyNzdjZGU0ZTFhNWU3NzBiMDRlMDc0ZTExMDU2Y2MzMTE0NjMzZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yx1uy2f0TYi0kvghFb2E7YBRV0hx3l1bkBuQgkXCPao)
> > It's coming soon
> 
> Default home tab configuration might not be important, just like the dock content configuration, the first tab will become the default tab on the homepage

completed it
