### ISSUE TITLE
关于搜索的个人建议

### ISSUE THREAD

**Issue by pgcoding1103** [hakadao/BewlyBewly#27]
有一个想法，就是希望可以将搜索后结果直接展示成脚本的样式，可以减少使用脚本后使用搜索时和官方样式的割裂感，也可以实现搜索时也有夜间模式，具体实现想法如下
if(输入有效关键词&按下搜索键‖点击搜索建议)
    将当前页面的内容替换成搜索内容
其他场景还是正常点击导航栏跳转

**Comment by hakadao** [comment]
其實想過做成全站適配的效果，其它頁面只是改css換配色，頂欄也用插件的頂欄
但是考慮到bilibili evolved的dark mode已經做得夠好了…
或者後面試着做一做吧

**Comment by Ccccpg** [comment]
发现这个脚本后，我去掉了其他脚本，感觉还是这个最符合我审美😂就是想着搜索样式也可以替换成脚本样式就更好了

**Comment by hakadao** [comment]
v0.7.0已實現

**Comment by Ccccpg** [comment]
> v0.7.0已實現

已经用上了，感谢更新🤩顺便反馈下问题和后续建议
问题
搜索框重复：
![Snipaste_2023-09-03_17-20-56.png](https://github.com/hakadao/BewlyBewly/assets/90168807/4c6294ab-c9ed-4b54-958e-6fae101990b1)

后续建议
⒈搜索结果不再进行新标签页的跳转，而是直接展示（个人想法：当点击搜索后，将搜索内容替换首页内容，此时导航栏的首页图标变成返回首页图标；当点击返回首页图标则返回首页，此时导航栏的返回首页图标变回首页图标，首页内容替换搜索内容）
⒉其他就是搜索结果的样式优化了，让其更符合脚本的风格！

**Comment by hakadao** [comment]
> > v0.7.0已實現
> 
> 已经用上了，感谢更新🤩顺便反馈下问题和后续建议
> 问题
> 搜索框重复：
> ![Snipaste_2023-09-03_17-20-56.png](https://github.com/hakadao/BewlyBewly/assets/90168807/4c6294ab-c9ed-4b54-958e-6fae101990b1)
> 
> 后续建议
> ⒈搜索结果不再进行新标签页的跳转，而是直接展示（个人想法：当点击搜索后，将搜索内容替换首页内容，此时导航栏的首页图标变成返回首页图标；当点击返回首页图标则返回首页，此时导航栏的返回首页图标变回首页图标，首页内容替换搜索内容）
> ⒉其他就是搜索结果的样式优化了，让其更符合脚本的风格！

原本b站搜尋頁面就是有兩個搜尋欄
另外第一個建議，是直接在搜尋頁顯示結果嗎？我是想在搜尋頁加入搜尋結果功能，但是是後期的工程，這樣就能直接不跳轉頁面顯示結果
第二個建議，原版b站搜尋結果頁不想做過多改動，最多只會適配深色模式

搜尋結果頁的話目前是不会做的，因為接下來主要是對做好的功能調整和測試
原b站搜尋結果樣式的話如果改動不是太大的話可以做，具體如何改良不知閣下能否給一些建議？

**Comment by Ccccpg** [comment]
> > > v0.7.0已實現
> > 
> > 
> > 已经用上了，感谢更新🤩顺便反馈下问题和后续建议
> > 问题
> > 搜索框重复：
> > ![Snipaste_2023-09-03_17-20-56.png](https://user-images.githubusercontent.com/90168807/265255022-4c6294ab-c9ed-4b54-958e-6fae101990b1.png)
> > 后续建议
> > ⒈搜索结果不再进行新标签页的跳转，而是直接展示（个人想法：当点击搜索后，将搜索内容替换首页内容，此时导航栏的首页图标变成返回首页图标；当点击返回首页图标则返回首页，此时导航栏的返回首页图标变回首页图标，首页内容替换搜索内容）
> > ⒉其他就是搜索结果的样式优化了，让其更符合脚本的风格！
> 
> 原本b站搜尋頁面就是有兩個搜尋欄 另外第一個建議，是直接在搜尋頁顯示結果嗎？我是想在搜尋頁加入搜尋結果功能，但是是後期的工程，這樣就能直接不跳轉頁面顯示結果 第二個建議，原版b站搜尋結果頁不想做過多改動，最多只會適配深色模式
> 
> 搜尋結果頁的話目前是不会做的，因為接下來主要是對做好的功能調整和測試 原b站搜尋結果樣式的話如果改動不是太大的話可以做，具體如何改良不知閣下能否給一些建議？

看了一下，B站原本只有一个搜索框，如图所示
![image](https://github.com/hakadao/BewlyBewly/assets/90168807/6204b76d-a9eb-46da-a9f7-204026f06b33)
“搜尋頁加入搜尋結果功能”感觉也可以，这样每个页面都有搜索框，感觉逻辑可以是搜索后统一跳转到搜索页显示搜索结果

对于搜索结果的样式建议:
1.其实我个人希望搜索结果样式（像视频卡片、布局、hover效果）跟首页效果保持一致就行了
2.还有就是原版的筛选的样式有个分隔线且略显扁平，感觉不太符合脚本的风格，这里说一下我对这个脚本风格的理解：视觉上主要是由阴影模糊、暗色模式下高光来区分层次，所以我觉得可以改成这样，如图所示
![image](https://github.com/hakadao/BewlyBewly/assets/90168807/b6b09fcb-3f72-4b14-8fd0-07bbe0dc0785)
不知道这算不算改动太大🤔

**Comment by hakadao** [comment]
视频卡片 hover效果 是可以跟回首頁的，我對b站頁面CSS不會做太大改動，因為之前寫過 amazing bilibili全站樣式的到現在都有陰影，日後可能淺色模式也會調整主題色，大的CSS改動就不怎麼想了
改主題色對b站如果更新樣式的話沒有太多影響，但是CSS調整整體設計的話到時候可能就是各種錯位+顏色不協調了

**Comment by hakadao** [comment]
视频卡片 hover效果 是可以跟回首頁的，我對b站頁面CSS不會做太大改動，因為之前寫過 amazing bilibili全站樣式的到現在都有陰影，日後可能淺色模式也會調整主題色，大的CSS改動就不怎麼想了
改主題色對b站如果更新樣式的話沒有太多影響，但是CSS調整整體設計的話到時候可能就是各種錯位+顏色不協調了

**Comment by hakadao** [comment]
v0.7.1做了調整
