### ISSUE TITLE
希望能增加自动宽屏的功能

### ISSUE THREAD

**Issue by Nat30** [hakadao/BewlyBewly#278]
现在每打开一个视频都需要手动去开启宽屏，另外播放器的播放条和操作按钮会延迟出现(先出现画面和声音，才出现播放条和操作按钮)

**Comment by starknt** [comment]
> 现在每打开一个视频都需要手动去开启宽屏，另外播放器的播放条和操作按钮会延迟出现(先出现画面和声音，才出现播放条和操作按钮)

这个应该会在后续版本中优化一下视频播放体验

**Comment by hakadao** [comment]
你可以試試這個，bewlybewly更多是操作上和介面的改變，原有b站功能改變不太考慮整合，況且別人做得更好
https://chromewebstore.google.com/detail/extension-for-bilibili-pl/ffoljpljalicgkljioegejmigkkkincm

**Comment by Nat30** [comment]
感谢回复

**Comment by Littleweisheit** [comment]
> 你可以試試這個，bewlybewly更多是操作上和介面的改變，原有b站功能改變不太考慮整合，況且別人做得更好 https://chromewebstore.google.com/detail/extension-for-bilibili-pl/ffoljpljalicgkljioegejmigkkkincm

这个没火狐的版本
