### ISSUE TITLE
专栏收藏夹及专栏目录bug反馈

### ISSUE THREAD

**Issue by PandaYuuHa** [hakadao/BewlyBewly#283]
1.暗色模式下，专栏收藏夹标题依旧为黑色，与背景接近看不清楚
![QQ截图20240210182100](https://github.com/hakadao/BewlyBewly/assets/63838456/34a90656-5b03-4936-889e-d68e88d38796)

2.专栏目录显示超出页面范围，并且当鼠标移动到标题栏区域(红框范围)时就会自动收起，导致无法点击上面的部分
![image](https://github.com/hakadao/BewlyBewly/assets/63838456/4353fab4-df90-4275-b977-083847fec89a)
![image](https://github.com/hakadao/BewlyBewly/assets/63838456/74406907-e43c-40c7-a809-df863473188c)

**Comment by hakadao** [comment]
已修復，後續小版本將更新

**Comment by hakadao** [comment]
v0.14.6 已修正
