### ISSUE TITLE
希望Dock栏能够在首页之外的其他页面（消息中心、视频播放页等）显示

### ISSUE THREAD

**Issue by HumanMus1c** [hakadao/BewlyBewly#284]
大哥新年好。使用了您的插件一段时间了。发现Dock栏只在首页显示。不知道是刻意而为还是出现了什么BUG呢。Dock栏这个设计我觉得非常好，希望后续可以支持在其他页面也也显示Dock栏。

**Comment by hakadao** [comment]
這個是刻意實現的，因為首頁和其他頁面的處理不怎麼相同
