### ISSUE TITLE
筆記字体不适应深色模式

### ISSUE THREAD

**Issue by KaitouKidgmh** [hakadao/BewlyBewly#285]
笔记处的字体在深色模式下还显示黑色 
![image](https://github.com/hakadao/BewlyBewly/assets/124412473/2031a62a-cb84-47d0-97d5-a738ade4adaf)

**Comment by hakadao** [comment]
有地址嗎

**Comment by KaitouKidgmh** [comment]
https://www.bilibili.com/opus/835111581331226656?spm_id_from=333.999.collection.opus.click

**Comment by hakadao** [comment]
這個問題已處理下個小版本將更新，不過話説如果在筆記中使用其他深色顏色作為字體顏色的話我可能處理不了
