### ISSUE TITLE
关于首页刷新问题

### ISSUE THREAD

**Issue by sperhmjj** [hakadao/BewlyBewly#29]
首页视频流确实足够多，但是没有刷新按钮，想要更新视频流显得很麻烦，建议加一个刷新功能，可以叠加在首页按钮上，从其他层级按一下首页是跳转过来，在首页层级上，再点击一下则是刷新，一个小小的建议~

**Comment by hakadao** [comment]
可以

**Comment by sperhmjj** [comment]
邮件收到啦，我会尽快查看的！谢谢你~

**Comment by hakadao** [comment]
v0.7.0已實現

**Comment by sperhmjj** [comment]
邮件收到啦，我会尽快查看的！谢谢你~
