### ISSUE TITLE
建议：视频卡片支持「反馈/我不想看」

### ISSUE THREAD

**Issue by cuiko** [hakadao/BewlyBewly#291]
be like:
![IMG_6636](https://github.com/hakadao/BewlyBewly/assets/33982919/4be2fea1-d18a-42d9-a721-a99114a6dccc)

**Comment by cuiko** [comment]
如果是和 [不喜歡推介影片功能](https://github.com/hakadao/BewlyBewly/issues/192#issue-2087991582) 重复的话，我就把 issue 关了

**Comment by hakadao** [comment]
> 如果是和 [不喜歡推介影片功能](https://github.com/hakadao/BewlyBewly/issues/192#issue-2087991582) 重复的话，我就把 issue 关了

這個可以一起實現的
