### ISSUE TITLE
[建议] 能否考虑一下Safari的插件

### ISSUE THREAD

**Issue by wwb011215** [hakadao/BewlyBewly#317]

**Comment by hakadao** [comment]
暫時沒有精力，把Firefox版做好再說

**Comment by msdurex** [comment]
> 暫時沒有精力，把Firefox版做好再說

Safari 需要点关爱，不然Safari做成付费版本上架MAS也行呀？

**Comment by hakadao** [comment]
Safari 需要点关爱(我指希望有人有空能幫我適配一下), 這不是錢不錢的問題

**Comment by hakadao** [comment]
> > 暫時沒有精力，把Firefox版做好再說
> 
> Safari 需要点关爱，不然Safari做成付费版本上架MAS也行呀？

Safari 需要点关爱(我指希望有人有空能幫我適配一下), 這不是錢不錢的問題
