### ISSUE TITLE
[产品建议] 关注的、正在开播的直播间列表

### ISSUE THREAD

**Issue by KevinCaoooooo** [hakadao/BewlyBewly#322]
希望可以在 Dock 或是主页的 Tab 上添加一个页面，显示自己关注的开播的直播间。

![Snipaste_2024-02-23_21-58-28](https://github.com/hakadao/BewlyBewly/assets/36534290/ed6b9aea-446a-4ecc-98b2-0b7607d21800)

**Comment by hakadao** [comment]
不打算整合直播頁功能
