### ISSUE TITLE
[BUG] 主页的收藏夹 Dock 只能显示每个收藏夹第一页的内容

### ISSUE THREAD

**Issue by KevinCaoooooo** [hakadao/BewlyBewly#323]
每个收藏夹只能显示前 20 个视频，正好是第一页的内容。我不知道是不是就这么设计的，反正先当 BUG 报上来了。

**Comment by hakadao** [comment]
能否給出具體分辨率大小，是否是熒幕太大了？

**Comment by KevinCaoooooo** [comment]
我的屏幕分辨率是 2880×1800，缩放 175%，网页本身没有缩放

**Comment by hakadao** [comment]
正常滑動到地下就能顯示其他頁內容的

**Comment by KevinCaoooooo** [comment]
你这么操作试一试：先进入一个收藏数 < 20 的收藏夹，鼠标滚轮向下滑动，等到加载图标消失后，再切换到一个收藏数 > 20 的收藏夹，这个时候再向下滑动就无法加载更多收藏内容了。

另外版本号：
![image](https://github.com/hakadao/BewlyBewly/assets/36534290/c56fec5d-a5f3-453d-9f13-dc518ccba582)

**Comment by hakadao** [comment]
> 你这么操作试一试：先进入一个收藏数 < 20 的收藏夹，鼠标滚轮向下滑动，等到加载图标消失后，再切换到一个收藏数 > 20 的收藏夹，这个时候再向下滑动就无法加载更多收藏内容了。
> 
> 另外版本号： ![image](https://private-user-images.githubusercontent.com/36534290/307673715-c56fec5d-a5f3-453d-9f13-dc518ccba582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzA3MjYsIm5iZiI6MTcwODkzMDQyNiwicGF0aCI6Ii8zNjUzNDI5MC8zMDc2NzM3MTUtYzU2ZmVjNWQtYTVmMy00NTNkLTlmMTMtZGM1MThjY2JhNTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA2NTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmODk5ZjVkMDJmZTRkMWYwZTg5YzAzMGVhZDYxYzQzY2VjMDE0NjNjMmEwNDBhZGQwYmZjODUwMzAxNGQ1NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uavONfkM-ljduDWAf1r5HBoriNTJ71aid0kpCwdlvYc)

好的, 之後出現問題希望提供一下問題實現的操作方式
