### ISSUE TITLE
Support high refresh rate mode

### ISSUE THREAD

**Issue by NeKoOuO** [hakadao/BewlyBewly#325]
The current visible is only 60fps, I hope to increase the refresh rate to 120fps or more

**Comment by hakadao** [comment]
I didn't limit the refresh rate to 60fps, it might be a browser problem (?)

**Comment by NeKoOuO** [comment]
> I didn't limit the refresh rate to 60fps, it might be a browser problem (?)

ohhh Okay... cause I don't use chrome or edge
