### ISSUE TITLE
可以加一个记录页面播放模式的功能吗

### ISSUE THREAD

**Issue by CloudSVC** [hakadao/BewlyBewly#329]
默认打开视频页面是这个但是我喜欢
![image](https://github.com/hakadao/BewlyBewly/assets/93499895/58e6a6f4-beb1-4c8b-84e3-cbfe9aaf4b32)
我喜欢下面的这个页面，我想让他保持每次打开页面都是这个样子播放
![image](https://github.com/hakadao/BewlyBewly/assets/93499895/78f366e3-62f7-4972-9aa4-f9e14f22ca00)

**Comment by CloudSVC** [comment]
宽屏模式，希望加载视频每次都是宽屏模式

**Comment by hakadao** [comment]
不會考慮實現，已經有現成的插件可以實現這個效果

https://chromewebstore.google.com/detail/哔哩哔哩bilibili播放器扩展/ffoljpljalicgkljioegejmigkkkincm?hl=zh-CN
