### ISSUE TITLE
非Chrome插件商店插件，无法启用

### ISSUE THREAD

**Issue by JingHai-Lingyun** [hakadao/BewlyBewly#33]
![image](https://github.com/hakadao/BewlyBewly/assets/109946426/c306b1f9-d0f0-482c-979b-42dd58851d82)

**Comment by hakadao** [comment]
是chrome瀏覽器嗎? 試試啓用 Developer mode (開發者模式)
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/92e262e1-dd18-4595-929d-49d4d8edb8fc)

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/hakadao/BewlyBewly/assets/109946426/5ebc5f40-30c0-4e83-86b3-da5f2210ddc2)
打开了

**Comment by JingHai-Lingyun** [comment]
另外 Edge 浏览器同样报不可信来源，不可启用
![image](https://github.com/hakadao/BewlyBewly/assets/109946426/f1507c58-aba9-488a-9f73-07248e47cf9e)
均是通过开发者模式加载 `.crx` 文件

**Comment by hakadao** [comment]
找到任意版本下載 extension.zip 並解壓
![Snipaste_2023-09-21_00-43-55.png](https://s2.loli.net/2023/09/21/A4NbUgrDR8i2yhP.png)
然後啓用開發者模式並且點擊`加载已解压的扩展程序入`，選取剛剛已解壓的檔案
![Snipaste_2023-09-21_00-49-04.png](https://s2.loli.net/2023/09/21/vOB71PzycT5r8su.png)

**Comment by JingHai-Lingyun** [comment]
好 插件可以用了
感谢
