### ISSUE TITLE
[BUG]某些界面未适配深色模式

### ISSUE THREAD

**Issue by 100pangci** [hakadao/BewlyBewly#330]
![image](https://github.com/hakadao/BewlyBewly/assets/63954871/853e0d3d-eb27-4bc2-92ce-27dd7fe339c7)
如图，此处特别关注对象推送视频未适配。
界面地址：https://message.bilibili.com/#/whisper/

![image](https://github.com/hakadao/BewlyBewly/assets/63954871/e0c9504b-e160-4de4-9667-6c0efd4f61c3)
合集与列表亦未适配
界面地址：https://space.bilibili.com/这里是uid/channel/series

浏览器版本：Chrome 121.0.6167.187
系统版本：Windows 10 专业工作站版 22H2
且本人有使用油猴脚本的习惯，已测试关闭后问题依旧。

**Comment by hakadao** [comment]
1. 這個是關注了up主就有推送嗎還是什麼, 暫時沒有看到
2. 我現在沒有別的b站號測試這個, 有合集的情況下我做了適配的
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/2f95dfdb-c47f-48b3-8104-3ba7092607ab)

**Comment by 100pangci** [comment]
> 1. 這個是關注了up主就有推送嗎還是什麼, 暫時沒有看到
> 2. 我現在沒有別的b站號測試這個, 有合集的情況下我做了適配的
>    ![image](https://private-user-images.githubusercontent.com/33394391/308045416-2f95dfdb-c47f-48b3-8104-3ba7092607ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODM0NjAsIm5iZiI6MTcwOTA4MzE2MCwicGF0aCI6Ii8zMzM5NDM5MS8zMDgwNDU0MTYtMmY5NWRmZGItYzQ3Zi00OGIzLTgxMDQtM2JhNzA5MjYwN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAxMTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NGJjZGRlMDU0MzllZmE4OGE5YzdjNDE0NmE2ZTI0MDA0YzA0MTJhYjdkZTUyMzI2OTJlNTFhMGM4ZWQ2NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ZihdVxw5Vai7cWbAuRzWEFYqcyM42sTUdnbCnMnfLs)

你好，是关注up的特别推送界面。
