### ISSUE TITLE
[BUG]搜索框用中文输入法输入单词回车不应该直接触发搜索

### ISSUE THREAD

**Issue by douseful** [hakadao/BewlyBewly#334]
有时候想中英文混输，输入英文回车后发现直接触发了搜索，建议只上屏对应英文。

**Comment by hakadao** [comment]
這個算bug吧,暫時不知道如何解決

**Comment by douseful** [comment]
找到个代码片段可以解决，我对 vue 不太熟悉，不知道这个方案咋样
[vue3中解决input输入中文过程回车触发enter事件](https://juejin.cn/post/7270343009790394420)
[vue playgroud](https://play.vuejs.org/#eNqlUz1PwzAQ/SuWF1oJpQNM0CK+OsAACBi9RMm1Dbi2ZV9KEYqEYGFgZ2RCYmJhQsC/4UNM/AUuDglUaishPCTOu+e7d++cE75iTDBIgS/wpotsYpA5wNQsCcVoSUCWKJNiW8WsxdCmsFhEIq0c0rNvtEsw0Qo8owYDUFhnrSV2UhAZ81BgrH+vQydMJdbq33nYhPzZpDoOQ4v/rtQJpRtfqheqWEJbIdi/VWFVmU6trFSvDtEKJViszZBRM/UKzn40NBvFBMh7+kDoGxkifE+i6VMWe8Ij6GkZg20J/nZ2+3rz/Pl0+XZ+/3F193728PJ4+vJw8fl0LXhxYPkQjmN9pAIS7M/8arLijM6SSKPAOJ6fxSjTQyW3QeKbjaoTPsvRkcudpBscOK3o0nl/igQJ2bNtfA7BF0q7BQ+l1EebHsvvx2yJRz2IDsfgB26YY4LvWHBgByB4FSNxXSB5ebi9twVD2lfBvo5TSewpwV1wWqa5xoK2muY+kocVz6vdIDssJqq779pDBOXKpnKhOTPzfMHpz1ub0vqP3Llg3p8TKuPZF29WP2M=)

```vue
<script setup>
    let inputEnd = true;
    const compositionend = (event) => {
      event.preventDefault();
      inputEnd = true;
    };
    const compositionstart = (event) => {
      event.preventDefault();
      inputEnd = false;
    };
    const handleEnter = (event) => {
      event.preventDefault(); 
      if(inputEnd){
         alert('end')
       }
    };
</script>

<template>
    <input
    placeholder="您好，想问点什么？"
    @keydown.enter="handleEnter"
    @compositionend="compositionend"
    @compositionstart="compositionstart"
    />
</template>
```

**Comment by hakadao** [comment]
十分感謝，今晚我試試

**Comment by hyoban** [comment]
也可以试试

![image](https://github.com/hakadao/BewlyBewly/assets/38493346/78b14924-6aff-40a7-accf-eb85bd7520da)

**Comment by hakadao** [comment]
> 也可以试试
> 
> ![image](https://private-user-images.githubusercontent.com/38493346/308599925-78b14924-6aff-40a7-accf-eb85bd7520da.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzQxMjUsIm5iZiI6MTcwOTEzMzgyNSwicGF0aCI6Ii8zODQ5MzM0Ni8zMDg1OTk5MjUtNzhiMTQ5MjQtNmFmZi00MGE3LWFjY2YtZWI4NWJkNzUyMGRhLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxNTIzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzA2NWM1YzY0YmFkZmQ4MTBhMzQ2NWU1ZDk0MmEwNjIwMjliNTgxOTkzOGI5NDVlY2M1YjgyYzBjY2M3YmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9voxcy6gWu0ONgs40TmPHi2SIvBRL4jBtfLbYq2D7xY)

十分感謝，這個方法特別好用
