### ISSUE TITLE
好像MomentsPop直播tab第一页有滚动条且不满10个滚到底会一直触发请求第一页然后覆盖原有数据

### ISSUE THREAD

**Issue by apades** [hakadao/BewlyBewly#34]
[录屏](https://www.awesomescreenshot.com/video/21013671?key=9075fbdc1e6e3de1f7933cd24a379021)

**Comment by hakadao** [comment]
改空內容bug時注意到了，到時候處理一下，謝謝提前

**Comment by hakadao** [comment]
v0.7.3版本已經修復
