### ISSUE TITLE
播放页面顶栏能不能固定

### ISSUE THREAD

**Issue by masirhh** [hakadao/BewlyBewly#35]
![image](https://github.com/hakadao/BewlyBewly/assets/39006170/7d9b4b39-7f71-4a4d-9e9a-5720fe45697f)
如图 播放页面的顶栏能不能固定，跟随屏幕移动后会挡住视频标题。

**Comment by masirhh** [comment]
![image](https://github.com/hakadao/BewlyBewly/assets/39006170/77e1196b-d010-46f7-9822-4d7a5151013a)
![image](https://github.com/hakadao/BewlyBewly/assets/39006170/ef5c02d0-7cf9-492f-8284-7058055726b4)

补一个 动态页面的配色好像不太优雅 关掉bg-color似乎要和谐一点

**Comment by hakadao** [comment]
原版b站頂欄就是固定的，BewlyBewly的頂欄只是將背景白色換成過渡背景色然後固定

**Comment by masirhh** [comment]
> 原版b站頂欄就是固定的，BewlyBewly的頂欄只是將背景白色換成過渡背景色然後固定

哦哦 好的

**Comment by hakadao** [comment]
> ![image](https://user-images.githubusercontent.com/39006170/270146671-77e1196b-d010-46f7-9822-4d7a5151013a.png) ![image](https://user-images.githubusercontent.com/39006170/270146752-ef5c02d0-7cf9-492f-8284-7058055726b4.png)
> 
> 补一个 动态页面的配色好像不太优雅 关掉bg-color似乎要和谐一点

這個我改一下
