### ISSUE TITLE
鼠标放在视频上预览，整个页面有概率会闪烁

### ISSUE THREAD

**Issue by WzxKB** [hakadao/BewlyBewly#350]
现象：把鼠标放在主页的视频上使用预览功能，也有有时候会闪烁，黑屏然后又亮起来，闪烁的时候视频会消失
不知道是不是我个别的，配置有问题

**Comment by hakadao** [comment]
能否提供一下视频

**Comment by hakadao** [comment]
我這裏暫時沒有重現這個問題抱歉
