### ISSUE TITLE
添加该插件后，b站播放视频会自动静音。

### ISSUE THREAD

**Issue by cccpism** [hakadao/BewlyBewly#356]
如题，添加该插件后，b站播放视频会自动静音，未添加该插件时不存在该问题，且检查过浏览器，相关权限已打开并且在其他平台上播放视频不会自动静音。

**Comment by hakadao** [comment]
暫時沒有試過，關閉再打開聲音之後播放還是不會有這種情況

**Comment by BlessNeo** [comment]
+1
