### ISSUE TITLE
历史记录查看更多bug

### ISSUE THREAD

**Issue by sssyc1** [hakadao/BewlyBewly#36]
当点击查看更多按钮时候，则会跳转到动态页面,并不会跳转到历史界面。
![b1](https://github.com/hakadao/BewlyBewly/assets/110219053/d5a62663-ce55-409f-9f28-39578fc5a228)
![b2](https://github.com/hakadao/BewlyBewly/assets/110219053/041e3546-a166-4977-93cc-f063c61b3ae8)

**Comment by hakadao** [comment]
這是特性，頂部的跳轉還是跳轉到原来b站的，dock才是bewlybewly介面的

**Comment by hakadao** [comment]
好吧我理解錯了不好意思，下版本改

**Comment by hakadao** [comment]
v0.8.0已修正
