### ISSUE TITLE
样式bug(Maybe)

### ISSUE THREAD

**Issue by jangufo** [hakadao/BewlyBewly#363]
当标题有一行和两行混排时，一个高，一个低。会出现对不齐的情况，底下的up名字，观看次数，弹幕数对不齐。而且鼠标移入阴影一行也比两行短一截。使我这个强迫症非常难受。。。
<img width="460" alt="PixPin_2024-03-05_13-45-46" src="https://github.com/hakadao/BewlyBewly/assets/110241287/7e09c5f7-d1d3-4060-99b1-923687e4de88">

我希望可以固定标题高度，让标题固定为两行的高度
（图片是我截了两次图，左边是贴图）我已经在谷歌插件页面反映过问题，可是并没有得到回复

**Comment by hakadao** [comment]
這不算bug,也不算設計上的失誤,純粹部分人的喜好
已經改了, 沒發版本. 話說其實 youtube 那邊都沒有這麼對齊, 其實真的有必要嗎?
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/65d1151c-ebd6-4f31-99ee-3b6af6340ac7)
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/f8942c2a-0507-40c8-9a99-8d58ed817943)

**Comment by akira0245** [comment]
更喜欢youtube跟原版这种啊… 单行标题中间空出来一块真的很奇怪
