### ISSUE TITLE
怎么将消息的小红点去掉呢？

### ISSUE THREAD

**Issue by yoke686** [hakadao/BewlyBewly#364]
我实在是不想看见这个消息提醒

**Comment by yoke686** [comment]
或者干脆把这个小铃铛按钮去掉就好了

**Comment by hakadao** [comment]
正常你在這個頁面所有配置關閉就可以了
https://message.bilibili.com/#/config

**Comment by yoke686** [comment]
> 正常你在这个页面所有配置关闭就可以了 https://message.bilibili.com/#/config

ok，虽然我是通过把所有消息删除了才解决的

**Comment by hakadao** [comment]
之後版本更新加了這個選項
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/de4c2ff8-24d6-4bf0-a4e9-48d298c6c70b)
