### ISSUE TITLE
在消息中心页顶部功能栏全部无反应

### ISSUE THREAD

**Issue by MuFeng086** [hakadao/BewlyBewly#37]
Bilibili Evolved插件已删并浏览器清缓存重启，在消息中心时顶栏所有按钮无法点击，光标在上面时也没有反馈。

**Comment by MuFeng086** [comment]
https://github.com/hakadao/BewlyBewly/assets/88829187/0b22fc9c-b9a7-4f62-955e-fbf7253512be

**Comment by hakadao** [comment]
這個我暫時沒能復現

**Comment by hakadao** [comment]
https://github.com/hakadao/BewlyBewly/assets/33394391/6a2d6a57-9612-4191-b46d-220c56eb4267

**Comment by flashorsink** [comment]
https://github.com/hakadao/BewlyBewly/assets/23011333/32adaf28-0eb9-430f-ad72-5602872cc407

**Comment by flashorsink** [comment]
同样的问题，插件版本0.7.3，浏览器是edge，使用zip压缩包安装的

**Comment by hakadao** [comment]
v0.8.0 調整了一下 `z-index` 應該沒有問題了
