### ISSUE TITLE
【建议】能不能将给稍后再看也增加一个悬停显示的功能，类似导航栏的收藏动态这些

### ISSUE THREAD

**Issue by torrowandyou** [hakadao/BewlyBewly#377]

**Comment by hakadao** [comment]
這個功能早有了，去chrome那邊下吧，edge可能還在審核
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/1de43b24-e579-4c2e-92a7-058bc388a91e)

**Comment by hakadao** [comment]
現在已經有了吧
<img width="452" alt="Snipaste_2024-03-11_00-13-19" src="https://github.com/hakadao/BewlyBewly/assets/33394391/30869e37-a137-4726-8b97-4e8f552bcc4d">
