### ISSUE TITLE
使用感受

### ISSUE THREAD

**Issue by WySen-Yeah** [hakadao/BewlyBewly#39]
修改之后的UI爆鲨bilibili原版UI，唯一不足的就是只支持首页，点开视频和其他页面之后落差好大

**Comment by hakadao** [comment]
確實全面適配才是最好的，但我真的沒有那麼多時間啊。。。。。。。。。。。。。。。。。。

**Comment by WySen-Yeah** [comment]
作者根据情况弄就行，我也只是提一下意见，既然作者有这个想法，我可以期待一下
