### ISSUE TITLE
［添加功能：设置默认启动页］自定义设置默认首页为搜索页

### ISSUE THREAD

**Issue by ghost4994** [hakadao/BewlyBewly#40]
![image](https://github.com/hakadao/BewlyBewly/assets/50790525/0c16e742-6a25-46a1-84ec-dd931b3a9945)
建议添加自定义设置：打开b站自动跳转此页面（感觉这个页面太好看了，另外相当于只把b站当作搜索工具使用

**Comment by hakadao** [comment]
是想設定啟動後的預設頁面嗎，是的話我改一下問題標題

**Comment by ghost4994** [comment]
是的是的！

**Comment by hakadao** [comment]
v0.8.0已實現
<img width="818" alt="Snipaste_2023-10-02_19-20-43" src="https://github.com/hakadao/BewlyBewly/assets/33394391/be13c6ba-b6bf-463a-bd89-2b2167bc9bac">
