### ISSUE TITLE
无法安装Firefox版

### ISSUE THREAD

**Issue by wxory** [hakadao/BewlyBewly#41]
下载最新release安装提示该扩展似乎已经损坏
通过https://addons.mozilla.org/zh-CN/developers/ 提供的自动化测试得到几个报错
![图片](https://github.com/hakadao/BewlyBewly/assets/87301486/3facfe9a-8ac3-4278-95a4-55c3d9aa4b00)
****
望修复

**Comment by hakadao** [comment]
對於Firefox那裡真的不熟，目前只是在chrome和edge測過
