### ISSUE TITLE
【建议】关于个性推荐页面的刷新

### ISSUE THREAD

**Issue by fung-hwang** [hakadao/BewlyBewly#419]
目前如果我想在浏览个性推荐时刷新推荐内容，流程是先“返回顶部”，后“刷新”（这两个操作同为右下角的控件）

是否可能增加一个控件动作，当点击左上角的“个性推荐”时，就可以返回顶部并刷新（类似于b站APP上的逻辑）。使得原先需要两步完成的动作合并为一步。

<img width="795" alt="Snipaste_2024-03-21_22-10-48" src="https://github.com/hakadao/BewlyBewly/assets/45532371/5f480cc7-f9a6-4617-ac60-74330da34dd9">

当前使用版本为v0.15.4，十分感谢BewlyBewly的开发者。

**Comment by hakadao** [comment]
我試試吧

**Comment by hakadao** [comment]
下版本將會實現

**Comment by fung-hwang** [comment]
感谢感谢

> 已實現，下版本將會有此特性
