### ISSUE TITLE
【深色适配】有几个界面未适配

### ISSUE THREAD

**Issue by 100pangci** [hakadao/BewlyBewly#421]
### 以下是无法导出链接的部分
![image](https://github.com/hakadao/BewlyBewly/assets/63954871/249b7833-e7b3-45c8-987f-15c15a2b00b3)
↑如图，当单击一个视频使用的音乐后，弹出的框框未适配深色模式
![image](https://github.com/hakadao/BewlyBewly/assets/63954871/9d2a38bb-cc97-4b4b-aeab-0e50a4c4c2b7)
![image](https://github.com/hakadao/BewlyBewly/assets/63954871/734e8555-f650-41fe-8d86-50030983de68)
↑给up主充电的界面未适配。一共有两种样式

### 以下是有链接的部分
https://www.bilibili.com/404
↑404界面未适配
https://www.bilibili.com/v/popular/all
↑热门未适配
https://www.bilibili.com/watchlater/#/list
↑稍后再看未适配
https://www.bilibili.com/v/virtual/
↑虚拟主播区，暗黑模式显示异常
https://show.bilibili.com/platform/home.html?msource=pc_web
↑会员购，应该还有人有电脑购物的习惯……

### 另外还有一些不涉及主站视频的界面，这些用的比较少，可忽略
比如说：[社区中心](https://www.bilibili.com/blackboard/activity-5zJxM3spoS.html)，[创作中心](https://member.bilibili.com/platform/home)，[公益](https://love.bilibili.com/)，[课堂](https://www.bilibili.com/cheese/?csource=common_hp_channelclass_icon)，[新歌热榜](https://music.bilibili.com/pc/music-center/)，[活动](https://www.bilibili.com/blackboard/activity-list.html)，[个人直播中心](https://link.bilibili.com/p/center/index#/user-center/my-info/operation)

**Comment by hakadao** [comment]
一般不影響視覺的頁面如深色模式下不會出現白字白背景我都懶得適配，稍候再看會調的之後

**Comment by 100pangci** [comment]
> 一般不影響視覺的頁面如深色模式下不會出現白字白背景我都懶得適配，稍候再看會調的之後

好的，谢谢

**Comment by hakadao** [comment]
現在做了稍後觀看和404頁面適應，其他感覺用到的頻率比較少先不做先了
