### ISSUE TITLE
关闭并重新打开后无法登录

### ISSUE THREAD

**Issue by klaybloom** [hakadao/BewlyBewly#422]
1.在开启插件情况下登录bilibili账号；
2.将插件设置为点击时可用；
3.点击后进入插件UI页面显示未登录，点击登录显示已登录正在跳转；
4.将站点权限修改为在bilibili.com上仍显示未登录且无法登录。

**Comment by hakadao** [comment]
沒看懂，bewlybewly沒有點擊時可用這個設定，可否錄製一段影片看看
