### ISSUE TITLE
【Feature Request】Bilibili-Evolved 两个侧边按钮适配选项

### ISSUE THREAD

**Issue by yeyouchuan** [hakadao/BewlyBewly#423]
BewlyBewly 深色模式时同时改变 Bilibili-Evolved 侧边悬浮圆球的颜色适配，使之更加契合深色模式主题，感谢！

![image](https://github.com/hakadao/BewlyBewly/assets/73737746/7e002ff8-d35e-498f-a1ba-946bff99b7b9)

**Comment by hakadao** [comment]
已經實現，下版本會有，不用適應選項直接會有
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/84054b6a-c6a7-41e7-86a9-caaed2c922ca)
