### ISSUE TITLE
外观设计的建议

### ISSUE THREAD

**Issue by zhonglixun** [hakadao/BewlyBewly#424]
![QQ图片20240322165051](https://github.com/hakadao/BewlyBewly/assets/126559946/eea262e1-81e2-44aa-a958-28551900f6da)
上面这个栏下拉的时候可以自动隐藏吗？还有能给侧栏外观一个新旧外观的开关吗？我还是喜欢以前那种

**Comment by hakadao** [comment]
佈局切換按鈕不打算隱藏, dock 不打算再做一個舊外觀的開關
