### ISSUE TITLE
建议：顶栏可见性兼容性

### ISSUE THREAD

**Issue by cocang** [hakadao/BewlyBewly#427]
目前顶栏可见性不能兼容Wider Bilibili这种播放器置顶的油猴样式脚本，也不能单独设置播放页的顶栏可见，导致会出现样式冲突
![image](https://github.com/hakadao/BewlyBewly/assets/3839918/a22b1293-d2a0-4ab8-824a-e038b4ba9f38)
还请修复兼容性，或者新增可以单独设置播放页的顶栏可见，谢谢

**Comment by hakadao** [comment]
其實我沒有太多精力維護相容其他腳本,或許去該腳本那邊說明一下問題看看
