### ISSUE TITLE
收藏页面的“播放全部”按钮希望加回来

### ISSUE THREAD

**Issue by g-mph** [hakadao/BewlyBewly#442]
原版B站这里有播放全部的按钮，现在没了，好难受
[https://s21.ax1x.com/2024/03/31/pFT7HKK.png](https://s21.ax1x.com/2024/03/31/pFT7HKK.png)

**Comment by hakadao** [comment]
這個一直都有啊
<img width="374" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/5676860f-51a9-4b5b-b186-507cf622d06b">

**Comment by g-mph** [comment]
@hakadao 你这个是哪里的界面，我说的是鼠标移到右上角收藏按钮的情况

**Comment by hakadao** [comment]
> @hakadao 你这个是哪里的界面，我说的是鼠标移到右上角收藏按钮的情况

一開始載入不到圖片,到時候加這個

**Comment by hakadao** [comment]
加了下版本解決
<img width="483" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/fd8aed9b-ebc7-425d-ae64-54eed4b4af34">
