### ISSUE TITLE
建议增加[已关注按钮和功能]，类似某脚本

### ISSUE THREAD

**Issue by TianyuanZhu-data** [hakadao/BewlyBewly#444]
建议增加已关注按钮和功能:实现随机推荐已关注博主的视频，而不是像动态按照时间倒序展示

以上功能灵感来自于一个油猴的b站脚本，效果如图，脚本地址为：https://greasyfork.org/zh-CN/scripts/443530-bilibili-app-recommend
![QQ截图20240331134524](https://github.com/hakadao/BewlyBewly/assets/64355101/ac54cd3f-3cfd-4e26-90ff-b6c4f3acb276)
![QQ截图20240331132203](https://github.com/hakadao/BewlyBewly/assets/64355101/8b419776-f6dd-4417-bccd-b4ca3f4c4a6b)

**Comment by hakadao** [comment]
不打算添加此功能，在「兼容性」有個「使用原版 Bilibili 首页」功能，打開就可以用原版首頁，這樣應該也可以用這個腳本
<img width="1018" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/59bad85d-f780-4cc3-aeff-ae822c355634">
