### ISSUE TITLE
热门视频划至底部后（再无数据），会一直刷新重复发起请求

### ISSUE THREAD

**Issue by angenin** [hakadao/BewlyBewly#445]
热门视频一直向下滚动，大概十多二十次后，B站的热门视频就会到达底部（可以看原B站的热门视频，到达底部后会显示”没有更多视频了“），但插件会一直刷新重复发起请求。

**Comment by hakadao** [comment]
這確實是個bug，我之前以為是可以無限捲動的所以沒有加判斷。。。

**Comment by hakadao** [comment]
已修正，下版本不再有這個問題
