### ISSUE TITLE
页面滚动时会出现卡顿

### ISSUE THREAD

**Issue by MosaicAccount** [hakadao/BewlyBewly#446]
您好，页面在滚动时会出现卡顿的情况，例如图片未出现或者整个页面卡住，等待两三秒后正常。已经加载出来的内容，在滚动的过程中也会出现这种情况。

**Comment by hakadao** [comment]
請嘗試關閉毛玻璃效果和禁用自定義背景和遮罩

**Comment by hakadao** [comment]
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/48fecb88-7d95-4c3d-904d-388b333a1705)
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/dca50c7e-07e3-4106-9f42-a8894df1dd9b)
