### ISSUE TITLE
[BUG]在视频页的顶部栏 历史记录中跳转错误

### ISSUE THREAD

**Issue by Xyyaua** [hakadao/BewlyBewly#45]
### 细节
随便打开一个视频，在顶部栏的历史记录中 任何一个视频跳转地址错误  
会变成 `www.bilibili.com/video/ + 当前视频av/bv号 + / + 历史记录的av/bv号`

### 可能的修复方案
把跳转改为 `www.bilibili.com/video/ + av/bv号`

**Comment by hakadao** [comment]
v0.8.0已修正
