### ISSUE TITLE
插件菜单能不能加个开关

### ISSUE THREAD

**Issue by CN-Tower** [hakadao/BewlyBewly#450]
类似下面这样，方便快捷开启和关闭插件。
![image](https://github.com/hakadao/BewlyBewly/assets/20727404/29c7b9c6-1d2a-410e-831a-ffe3017a8729)

**Comment by hakadao** [comment]
這個擴充功能可以做到，不打算加
https://chromewebstore.google.com/detail/extension-manager/gjldcdngmdknpinoemndlidpcabkggco
