### ISSUE TITLE
动态栏不保存滚动进度，不便于二次查看

### ISSUE THREAD

**Issue by SpinCheng** [hakadao/BewlyBewly#451]
BewlyBewly插件美观好用，希望做大做强！
有个小细节个人觉得可以优化，官方动态列表图标展开后，展示的动态列表可以保存滚动进度，这样便于我点开一个动态列表的视频后，再回到动态列表不用重新滚动到上次进度；
而BewlyBewly则是每次都会重置到顶部，不太方便，希望可以考虑官方原版的实现逻辑。

**Comment by hakadao** [comment]
後續調整吧這個

**Comment by hakadao** [comment]
下版本修復,已處理
