### ISSUE TITLE
malfunction

### ISSUE THREAD

**Issue by zahi-ko** [hakadao/BewlyBewly#459]
主页无法显示，关闭插件后恢复正常
![image](https://github.com/hakadao/BewlyBewly/assets/159024690/1fea716d-0b7d-4b32-bc4d-5a439090a2ab)

**Comment by hakadao** [comment]
版本號是v0.15.5嗎

**Comment by zahi-ko** [comment]
> 版本號是v0.15.5嗎

0.15.4

**Comment by zahi-ko** [comment]
> 版本號是v0.15.5嗎

谢谢，更新后问题解决（edge浏览器扩展商店最新版本号还是0.15.4）

**Comment by hakadao** [comment]
> > 版本號是v0.15.5嗎
> 
> 谢谢，更新后问题解决（edge浏览器扩展商店最新版本号还是0.15.4）

因爲edge審覈有點慢那邊
