### ISSUE TITLE
功能建议：能否增加一个首页展示列表内容大小的自定义设置

### ISSUE THREAD

**Issue by SuAdrenine** [hakadao/BewlyBewly#464]
开发者：
        您好！
        我用的13寸的mac，首页一行显示3个，一页显示不到2行，太难受了，能否增加一个列表内容大小自定义设置，感谢！
<img width="1202" alt="iShot_2024-04-02_22 17 37" src="https://github.com/hakadao/BewlyBewly/assets/13587388/6ba2f198-2ecf-47cc-bdd8-2bf4b3cc9d3f">

**Comment by hakadao** [comment]
嘗試在【系統設置】裏選擇【顯示】->【更多空間】
<img width="715" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/dc4fce6b-e2e6-4430-b9cb-aa4e432a31a2">

或嘗試在瀏覽器使用 command + 減號進行縮放以取得更多空間
