### ISSUE TITLE
是否有可能把视频发布时间转换成youtube类似的XX天/周/月/年前格式？

### ISSUE THREAD

**Issue by akira0245** [hakadao/BewlyBewly#469]
虽然知道B站返回的已经是字符串格式的绝对日期了，但是统一显示成相对日期看起来会舒适很多，如果作者也有同感是否可以考虑一下呢？

**Comment by hakadao** [comment]
現在就是啊
<img width="1214" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/c21e7b2c-9a44-4ced-91fa-58a97f15f3ce">

**Comment by akira0245** [comment]
不好意思，忘记说是app推荐模式下的日期了，pc这样确实很舒适

**Comment by hakadao** [comment]
我怎麼轉換啊這
<img width="936" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/5bc0174c-6011-43c7-bef9-9cbddb229849">
