### ISSUE TITLE
三个细节问题

### ISSUE THREAD

**Issue by 22Frederic** [hakadao/BewlyBewly#47]
当打开首页搜索框选项再关闭时，搜索页会有两个搜索框![屏幕截图 2023-10-03 213909.png](https://github.com/hakadao/BewlyBewly/assets/105597335/005995f3-626a-4591-a23f-1772e3c09046)

在首页搜索框背景的右侧，滚动条会占用空间，可以给一个关闭滚动条的选项![屏幕截图 2023-10-03 214029.png](https://github.com/hakadao/BewlyBewly/assets/105597335/a122b95a-3f61-440f-bae8-284c161519ac)

收藏页右侧的收藏夹栏是直角的，或许可以加一个圆角使视觉更统一（参考ios设置选项栏那种）![屏幕截图 2023-10-03 213801.png](https://github.com/hakadao/BewlyBewly/assets/105597335/0b6f41ae-bf5e-4204-9ff9-6aff1b3dd2b4)

**Comment by hakadao** [comment]
第二個捲動條佔用空間那個可能不能及時調整…
搜尋頁樣式是趕工做的程式碼大亂有空調整

**Comment by hakadao** [comment]
0.9.0這些問題應該都解決了
