### ISSUE TITLE
将`xxxx次播放 • x天前 • xxx弹幕`显示在同一行里

### ISSUE THREAD

**Issue by akira0245** [hakadao/BewlyBewly#470]
跟youtube类似，将`xxxx次播放 • x天前 • xxx弹幕`显示在同一行里
可以让页面更紧凑显示更多信息，也降低了单独显示一行capsule文本的带来的视觉上的复杂性

每个视频卡片下方2.5rem的margin也占据了额外的空间，感觉去掉也可以更紧凑美观，不知道此处是否还有其他的考量？

**Comment by hakadao** [comment]
在之後的版本會調整下邊的間距, 時間單獨放出來是有意爲之, 之後看看能怎麼改吧
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/5859c261-5e6c-4f2d-9540-1fa038f1d725)
