### ISSUE TITLE
右上角的按钮能不能设成自动新标签页打开

### ISSUE THREAD

**Issue by g-mph** [hakadao/BewlyBewly#471]
右上角的按钮能不能设成自动新标签页打开，原版是这样的，
现在总是不小心把在看的视频切掉了，鼠标中键不习惯

**Comment by g-mph** [comment]
或者至少给个选项

**Comment by hakadao** [comment]
不打算,主要想跟youtube那樣操作,可以嘗試前進後退返回頁面.
主頁打開新標籤頁還是新標籤頁打開的,已經很剋制了改得
