### ISSUE TITLE
在macOS的Edge上使用，Command+单击无法在在新标签页打开页面

### ISSUE THREAD

**Issue by NaiqiZheng** [hakadao/BewlyBewly#473]

**Comment by hakadao** [comment]
可以啊，是點哪裏不行

**Comment by NaiqiZheng** [comment]
> 可以啊，是點哪裏不行

顶栏里的动态、消息等，和首页的视频都不可以，只能右键打开新标签页

**Comment by hakadao** [comment]
沒有重現
https://github.com/hakadao/BewlyBewly/assets/33394391/8844ae10-663c-48cf-a988-366e9b6db0e0
