### ISSUE TITLE
有时候打开页面会被白色蒙上

### ISSUE THREAD

**Issue by thissensen** [hakadao/BewlyBewly#480]
我开启背景遮罩的，有时候遮罩层会覆盖在上面
个人猜测可能是页面加载太快的原因？每次出现这种情况，页面好像都是秒加载的
版本：0.15.5
![QQ截图20240406234807](https://github.com/hakadao/BewlyBewly/assets/43516619/61e12650-37d2-4922-9e67-71104b6ca675)

**Comment by hakadao** [comment]
有沒有用其他插件或腳本

**Comment by thissensen** [comment]
> 有没有使用其他插件或脚本
油猴无脚本，使用中的插件只有IDM、划词翻译、uBlock Origin。应当无影响才是。
我路由器用了Adguard Home进行了DNS加速，二次加载B站主页面的时候估计响应过快导致的。这种现象极少出现，一个月也才3-4次

**Comment by hakadao** [comment]
這個情況無法重現, 先保留着這個問題看看有沒有其他人有類似的情況

**Comment by hakadao** [comment]
現在新版本是 v0.16.4 嘗試更新之後再看看站是關閉了
