### ISSUE TITLE
右上角动态弹窗内容

### ISSUE THREAD

**Issue by Anonywp** [hakadao/BewlyBewly#483]
感觉大佬可以参考一下原版样式再改改？UP名称不醒目，上传了三个字感觉不是很有必要，标题名称最多三行配上右边对齐的缩略图，这样挺好，当然怎么改大佬说了算，总体来说还是很棒的，感谢大佬
![@P PYPZTOAX2_8KMZ(JK4(Q](https://github.com/hakadao/BewlyBewly/assets/19343677/1706d70d-01ae-4c09-a3a2-e27c8a7cf494)
![QQ截图20240407184540](https://github.com/hakadao/BewlyBewly/assets/19343677/513fe9db-d7ec-44e5-a8a7-5284336a795c)

**Comment by hakadao** [comment]
好像也是，有空改改

**Comment by hakadao** [comment]
調整過後的，下版本就有了，問題先關閉了如果有設計的建議可以繼續說明我會再次開啓問題
<img width="381" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/e9f37165-b949-4871-ac31-fdc4abed821a">
