### ISSUE TITLE
字体模糊

### ISSUE THREAD

**Issue by puppet680** [hakadao/BewlyBewly#49]
流程：首页 -> 打开设置，效果如下
![image](https://github.com/hakadao/BewlyBewly/assets/54428441/f5d4495a-cddc-4eeb-97d1-6af514ed53e1)

![image](https://github.com/hakadao/BewlyBewly/assets/54428441/d9c8f536-e468-4797-a9d3-a680c35d59bc)

**Comment by hakadao** [comment]
是用甚麼瀏覽器

**Comment by puppet680** [comment]
> 是用甚麼瀏覽器

Chrome 版本 117.0.5938.152

**Comment by hakadao** [comment]
暫時沒有重現，這應該是瀏覽器渲染問題

**Comment by starknt** [comment]
> 暫時沒有重現，這應該是瀏覽器渲染問題

应该是 transform 的问题，详细可看 https://github.com/chokcoco/iCSS/issues/160

**Comment by hakadao** [comment]
@starknt 感謝提供資源，但是我這裏沒法重現只能靠猜着改了

**Comment by starknt** [comment]
> @starknt 感謝提供資源，但是我這裏沒法重現只能靠猜着改了

![不发生模糊](https://github.com/hakadao/BewlyBewly/assets/64941905/94464994-77af-4a82-a8aa-e9b62856c24d)
![发生模糊](https://github.com/hakadao/BewlyBewly/assets/64941905/ab61992b-b666-4d43-ad29-672a6ca76638)

**Comment by puppet680** [comment]
BewlyBewly 0.13.0，字体不模糊了
