### ISSUE TITLE
建议: 增加选择打开首页显示某个页面选项

### ISSUE THREAD

**Issue by yyym-y** [hakadao/BewlyBewly#497]
建议增加进入哔哩哔哩官网的时候自定义显示主页面是原生页面还是搜索页面
换句话来说, 支持用户选择下面两个页面的其中一个作为打开 https://www.bilibili.com/ 显示的页面
页面一: 
![image](https://github.com/hakadao/BewlyBewly/assets/133961507/3e1fc2f0-2f90-457f-91b1-999cfa05b0ba)
页面二:
![image](https://github.com/hakadao/BewlyBewly/assets/133961507/4e6740c4-b538-48fb-8f52-635106bd7b7e)

感觉有人会比较喜欢将搜索作为主页面的(比如我~~~)

**Comment by hakadao** [comment]
你這樣配置不就可以了
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/60a69552-578d-49f2-8672-0f42316eba33)

**Comment by yyym-y** [comment]
明白了, 没发现有这个选项 >ᯅ<

**Comment by hakadao** [comment]
> 明白了, 没发现有这个选项 >ᯅ<

另外在設定那裏搜尋頁背景可以單獨設置，之後你可以在那裏不用遮罩效果

**Comment by yyym-y** [comment]
> > 明白了, 没发现有这个选项 >ᯅ<
> 
> 另外在设定那里搜索页背景可以单独设置，之后你可以在那里不用屏蔽效果

OK, 感谢作者大大

**Comment by hakadao** [comment]
> > > 明白了, 没发现有这个选项 >ᯅ<
> 
> > 
> 
> > 另外在设定那里搜索页背景可以单独设置，之后你可以在那里不用屏蔽效果
> 
> 
> 
> OK, 感谢作者大大

不用客氣，我弄完沒有時間說明怎麼使用我也有一定問題(⁰▿⁰)
