### ISSUE TITLE
开启宽屏模式 由评论区返回顶部时视频宽度突变

### ISSUE THREAD

**Issue by zhaobudaomingzi** [hakadao/BewlyBewly#498]
PS：我将录屏调成0.5倍速，可以看出开启宽屏模式后，刚刚由评论区返回顶部时，视频宽度会从普通宽度再迅速变回宽屏。猜测是下拉查看评论区（视频播放界面不显示后），扩展会默认视频为普通宽度，导致重新回到视频播放界面时需要反应时间切换宽屏

https://github.com/hakadao/BewlyBewly/assets/54617500/d5361a3a-f0d3-4f85-a664-bee7aef9cf92

**Comment by hakadao** [comment]
你先看看不用此擴充功能時b站是否也是這樣，bewlybewly 沒有調整過播放器
或者嘗試停用毛玻璃效果看看是否是電腦效能的問題

**Comment by hakadao** [comment]
沒有啓用 bewlybewly 情況下也是這樣
https://github.com/hakadao/BewlyBewly/assets/33394391/8bab0841-dcc3-445b-b41d-774a064970c1
