### ISSUE TITLE
希望可以调节鼠标悬停顶栏时的响应灵敏度

### ISSUE THREAD

**Issue by yihao0628** [hakadao/BewlyBewly#507]
![image](https://github.com/hakadao/BewlyBewly/assets/75688855/53cdfe29-568e-4654-a723-01974a367dfd)
例如悬浮鼠标到此处时，手块想滑到我的消息，有的时候界面会收回去

**Comment by akira0245** [comment]
往下滑的速度快 淡入动画还没结束时候会这样

**Comment by yihao0628** [comment]
是的，确实是这样，但是这个需求确实存在，所以希望有动画速度调节这样的选项

**Comment by hakadao** [comment]
不打算，動畫速度已經處理得很好了，過後不打算調整

**Comment by yihao0628** [comment]
> 不打算，動畫速度已經處理得很好了，過後不打算調整

动画确实做的很漂亮，但是能否优化一下操作手感呢？😢

**Comment by akira0245** [comment]
@hakadao 目前顶栏的问题是在动画未完成时候鼠标直接下移到气泡上会导致气泡收回，必须要刻意在顶栏图标上停顿一下等到动画完成才能下滑点击弹出气泡中的菜单项
![动画](https://github.com/hakadao/BewlyBewly/assets/33274390/e2bec3af-d25d-4870-9dc6-9495a0c79322)
