### ISSUE TITLE
希望点击动态和消息等页面可以打开新页面而不是刷新当前页面

### ISSUE THREAD

**Issue by autismhealer** [hakadao/BewlyBewly#508]
在主页中点击动态和消息是打开新页面，而在动态、播放视频、信息等页面中再点击动态信息等则是刷新当前页面，希望可以统一一下或者有相关设置。

**Comment by hjbzn136** [comment]
对，今天突然发现点击动态栏的视频会跳到一个新的b站主页出来。

**Comment by GGBondzzy** [comment]
用这个插件就是因为这个动态预览是原版的样子，但是点击动态消息再弹出一个当前页面已经变成一个稳定的BUG了

**Comment by hakadao** [comment]
> 用这个插件就是因为这个动态预览是原版的样子，但是点击动态消息再弹出一个当前页面已经变成一个稳定的BUG了

V0.16.2 已經修復了動態跳轉問題了

**Comment by hakadao** [comment]
這部分我都難以處理, 因爲我處理的是主頁中開其他頁面是新開標籤頁, 但是其他頁面就直接覆蓋當前頁
另外b站預設動不動就開新tab我也控制不了
