### ISSUE TITLE
在消息设置关闭消息提醒后主页仍然显示红点

### ISSUE THREAD

**Issue by Seayay** [hakadao/BewlyBewly#51]
![image](https://github.com/hakadao/BewlyBewly/assets/92374733/ad36a20c-dfe7-4c79-855e-978ec67ef91e)
![image](https://github.com/hakadao/BewlyBewly/assets/92374733/9de3ffd2-c849-492f-aa88-bf560fbe2dc0)

浏览器: Edge
版本: 0.8.0

**Comment by hakadao** [comment]
我回去試試吧

**Comment by hakadao** [comment]
0.9.0 問題已修正

**Comment by Seayay** [comment]
![image](https://github.com/hakadao/BewlyBewly/assets/92374733/9bc24225-e9c6-457d-bb42-2f33e311f411)
![image](https://github.com/hakadao/BewlyBewly/assets/92374733/2a02931e-1097-475d-9051-6ab7ea02f894)

升级到 0.9.2 后仍然出现此问题
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by hakadao** [comment]
尝试将收起未关注人消息设定开启

**Comment by Seayay** [comment]
![image](https://github.com/hakadao/BewlyBewly/assets/92374733/376bd2ca-7234-484e-ba36-7066f06da11a)


> 尝试将收起未关注人消息设定开启

**Comment by cuiko** [comment]
> ![image](https://private-user-images.githubusercontent.com/92374733/279414342-376bd2ca-7234-484e-ba36-7066f06da11a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NTQyMzEsIm5iZiI6MTcwMzY1MzkzMSwicGF0aCI6Ii85MjM3NDczMy8yNzk0MTQzNDItMzc2YmQyY2EtNzIzNC00ODRlLWJhMzYtNzA2NmYwNmRhMTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA1MTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNGE1ZGVhMmQxNjllZWQwOGJmYzA0ZTkyMDFhZGZlZThkMTljMWQ0NDZmOGY4OGJkYTViY2Y3MzU5ODM0N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rOlw-2x0sL7fkZ0gdRLkp2cGgVaoGOyUdCIa0AXkFEk)
> 
> > 尝试将收起未关注人消息设定开启

这个是阿 b 消息通知做得太频繁了，你看看「我的消息」那个 tab，你会发现有很多都是未读的，什么杂七杂八的消息都在里面，然后都给计数了
我刚刚全给叉掉后就不显示红点了

**Comment by hakadao** [comment]
新版本有這個選項可以完全關閉
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/799f01e9-a9e1-4216-b1dc-54592a849d16)
