### ISSUE TITLE
主页面小窗播放导致的页面闪烁以及鼠标光标消失

### ISSUE THREAD

**Issue by thissensen** [hakadao/BewlyBewly#516]
版本：0.16.1
浏览器内核：Chromium 102.0.5005.167
有背景图+遮罩
视频前半部分就是闪烁的情况，应该是鼠标悬停在窗口上进行播放时发生的
视频后半部分是，鼠标在小窗播放时会隐藏，这时候进行滚轮，鼠标并没有出现(原版没这问题)，要动一下鼠标才会出现
附上视频：https://pan.baidu.com/s/1MwciH-gev-iWykWs3BiDGQ?pwd=kyq8

**Comment by hakadao** [comment]
嘗試下關閉毛玻璃和禁用遮罩和背景，這部分應該是瀏覽器渲染受電腦效能影響了

**Comment by thissensen** [comment]
> 嘗試下關閉毛玻璃和禁用遮罩和背景，這部分應該是瀏覽器渲染受電腦效能影響了

我的电脑配置是5900x+3080，32G内存，不至于是电脑性能影响。我测试了，关闭毛玻璃还是会闪，使用内置壁纸也会闪，但是不使用壁纸似乎就不闪了。此外我还发现一个问题，当我在url框内输入http:后面的'/'符号时，会失去输入框焦点，导致无法输入'/'符号，希望可以一并解决

**Comment by hakadao** [comment]
目前這是瀏覽器渲染問題我無法處理，試試用其他瀏覽器如Firefox
