### ISSUE TITLE
Bug:右上角点击动态不会跳转到相关视频

### ISSUE THREAD

**Issue by kpl0111** [hakadao/BewlyBewly#517]
如图：
![PixPin_2024-04-12_10-19-37](https://github.com/hakadao/BewlyBewly/assets/73956723/12dca211-cca2-491a-b22f-6202fcca4799)
正常应该是跳转到这条动态界面，但是现在却不是这样，希望作者能尽快修复，谢谢！

**Comment by hakadao** [comment]
您好, 十分抱歉, 在 v0.16.2 版本已經修復了這個問題, 且已經上傳到了 chrome web store, 感謝你提出
