### ISSUE TITLE
[Bug反馈]首页右上角动态展开 点击视频进入的却是首页

### ISSUE THREAD

**Issue by siyue2016** [hakadao/BewlyBewly#519]
如题
![image](https://github.com/hakadao/BewlyBewly/assets/126215802/7124f227-7110-4933-9ebf-3f58dafbf53c)

![image](https://github.com/hakadao/BewlyBewly/assets/126215802/af9a109e-dc54-40f6-a699-b3317b41002a)

**Comment by MengNianxiaoyao** [comment]
请确保插件版本为最新版，目前最新版为0.16.2

**Comment by hakadao** [comment]
十分抱歉, v0.16.2 已修復這個問題, chrome web store 和 firefox addons 已經更新了, edge 可能要審覈, 十分抱歉
