### ISSUE TITLE
顶栏bug：在播放视频网页全屏时仍会显示顶栏（v0.80）

### ISSUE THREAD

**Issue by flashorsink** [hakadao/BewlyBewly#52]
番剧、电影都有这个bug，但普通的视频没有问题
![微信图片_20231014175706](https://github.com/hakadao/BewlyBewly/assets/23011333/b63f4dcc-74dc-48ba-aad0-8c02c786daf1)

**Comment by hakadao** [comment]
之前消息頁的頂欄調過就是為了處理這個問題的，現在暫時不知道怎麼解決

**Comment by hakadao** [comment]
v0.10.1已修復
