### ISSUE TITLE
Feat: 订阅剧集能分类横向展示吗？

### ISSUE THREAD

**Issue by djkloop** [hakadao/BewlyBewly#521]
有时候订阅的剧集很多，但是一个页面可能只显示某个剧集。
![image](https://github.com/hakadao/BewlyBewly/assets/21050914/66989216-c668-4611-b2af-ab703aa40af3)
如果是某个频道横向滚动布局是不是可以省很多位置，能加个按钮改成类似这种布局吗
![image](https://github.com/hakadao/BewlyBewly/assets/21050914/412a1fd1-caee-413a-8d84-bef1d1d46d50)

**Comment by hakadao** [comment]
感谢您的建议，这部分受b站接口返回的数据限制，做成这种效果有点麻烦，不过您提出的意见后续如果可能的话将尝试实现的
