### ISSUE TITLE
[BUG]:好像url带上一些参数的时候会导致插件不生效

### ISSUE THREAD

**Issue by mengdux** [hakadao/BewlyBewly#525]
### 环境

Microsoft Edge
Version 115.0.1866.1 (Official build) Dev (arm64)

### 问题描述

类似https://www.bilibili.com/?a=1，插件就不生效了，刚在有活动的直播间点击到b站首页发现带上了直播间的一些参数回到首页，然后插件就不生效了。

### 预期结果

~

**Comment by hakadao** [comment]
已修复，v0.16.5出来的话将解决，谢谢提出
