### ISSUE TITLE
细节问题：顶栏的搜索框在动态详情页显得突兀

### ISSUE THREAD

**Issue by flashorsink** [hakadao/BewlyBewly#53]
搜索框既不居中也不和边缘对齐，看着蛮怪的
![微信图片_20231014180419](https://github.com/hakadao/BewlyBewly/assets/23011333/ac45a5ec-30dc-41e1-b586-1121a0b0f13d)

**Comment by hakadao** [comment]
因為右邊也有內容導致search bar偏左，留在後面再考慮怎麼處理

**Comment by hakadao** [comment]
0.9.0已調整
