### ISSUE TITLE
[Feat]: 能添加对Safari浏览器的支持吗？

### ISSUE THREAD

**Issue by hwqchi** [hakadao/BewlyBewly#535]
如题，油猴脚本有Safari版本，对于该插件在技术上应该也是容易实现的，希望能够添加对Safari浏览器的支持。

**Comment by MengNianxiaoyao** [comment]
在规划中，具体进度可在`feat/support-safari`分支中查看commit记录，后续会提供最新提交的代码构建的插件

**Comment by hakadao** [comment]
1. 這不是油猴，這是瀏覽器擴充功能技術難度不同
2. apple developer一年要99usd，之前b站做過投票多數Safari用戶都不願意為擴充功能付費加上我薪資不是特別好所以不打算上架
3. safari支援已經實現，由於第二點問題我會考慮讓safari用家手動安裝bewly
4. 我對某些Safari用家有ptsd，之前幾則issues說得我好像故意不做Safari支援甚至有一條說macOS用家需要關愛此類情緒勒索問題（macOS同樣可以用chrome和firefox，我為愛發電被人無辜誣蔑我覺得我也需要關愛）

綜上，Safari支援會有，但是要本地安裝
我不考慮解決後續macOS用家提出安裝麻煩問題，這一點蘋果也有對應責任
我不想一個人吃下一坨屎還要被慷他人之慨的人說我不夠關愛他人
