### ISSUE TITLE
[BUG]: 右上侧动态列表异常

### ISSUE THREAD

**Issue by JorenBai** [hakadao/BewlyBewly#536]
### 环境

浏览器: Edge
浏览器版本: 123.0.2420.81
BewlyBewly 版本: 0.16.1

### 问题描述

本来一直有 #237  这个问题，但无伤大雅 不影响功能
今天突然发现动态指向的链接均为当前页面的URL，截图时浏览位置在网站首页，所以动态链接也为首页地址
![Snipaste_2024-04-12_19-23-03](https://github.com/hakadao/BewlyBewly/assets/13309787/e063c0a9-0812-4622-9028-2f48b6dadfe1)

### 预期结果

点击链接访问实际内容页面

**Comment by jangufo** [comment]
0.16.2没有这个问题，可能需要更新？我之前也有这个问题

**Comment by JorenBai** [comment]
> 0.16.2没有这个问题，可能需要更新？我之前也有这个问题

也许是？我看了一下 Edge 商店，目前未更新到 0.16.2 版本

**Comment by hakadao** [comment]
edge商店版本更新受審核速度影響，v0.16.4已經修復了

**Comment by JorenBai** [comment]
> 可以直接到[release](https://github.com/hakadao/BewlyBewly/releases)界面看啊

策略限制，只能官方商店
