### ISSUE TITLE
[BUG]:设置界面的开关按钮错位

### ISSUE THREAD

**Issue by discodyer** [hakadao/BewlyBewly#538]
### 环境

浏览器: Firefox
浏览器版本: 124.0.2
BewlyBewly 版本: 0.16.4
操作系统：Windows 11 专业版 23H2

### 问题描述

![图片](https://github.com/hakadao/BewlyBewly/assets/28340430/7d660f6f-9574-4669-b99e-1e3ea1b8e5d4)

如图所示，右侧开关按钮的圆形部分会出现错位bug，偏向右下角了一点点。

### 预期结果

按钮正常显示不出现错位现象

**Comment by hakadao** [comment]
這個問題我真不會處理，之後排查吧

**Comment by discodyer** [comment]
首先感谢您对这个问题的关注和回复。

我刚刚下载了最新版本的Chrome(123.0.6312.123)并且安装了0.16.4版本的BewlyBewly。我发现这个问题在Chrome中并不存在。可能是Firefox独有的问题。

**Comment by hakadao** [comment]
firefox樣式問題我目前無能爲力抱歉
