### ISSUE TITLE
[BUG]:部分界面按钮悬停 CSS 样式不符或丢失

### ISSUE THREAD

**Issue by SolitudeSun** [hakadao/BewlyBewly#539]
### 环境

系统: Windows 11 23H2
浏览器: Microsoft Edge
浏览器版本: 123.0.2420.81
BewlyBewly 版本: 0.16.1

### 问题描述

1. **在动态首页页面时，默认列表是已关注的 UP 主，此时悬停任意 UP 主，点击已关注按钮会取消关注，再次悬停则 hover 样式与主题色不符**

    <img width="796" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/f89df4c3-115f-4416-98c5-51953f764d35">

2. **在任意未关注的用户的主页时，此时悬停在关注按钮上，关注按钮的 hover 悬停样式丢失**

    <img width="967" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/252b47d3-49a5-4cc3-a3bf-89b49453eb02">

3. **在任意用户的主页时，点击收藏列表，列表内播放所有视频的按钮 hover 悬停样式丢失**

    <img width="959" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/5752fae9-3fe9-4d2d-8ed6-64605315c5a1">

4. **在电影页面时，点击评分，此时想写长评的文字主题色与主题色不符**

    <img width="877" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/2d4a9e02-f5c9-4395-8b3b-9fab1f08f2e2">

5. **能否增加对部分界面，例如番剧或电影介绍页面的支持**

    ![image](https://github.com/hakadao/BewlyBewly/assets/101030922/220e9b7a-5795-482d-961c-b7c2f48fee00)

### 预期结果

_已在最新版本 0.16.4 中测试，部分 bug 仍旧可以复现_
预期结果：解决部分样式错误或丢失
新页面：希望添加对部分页面的支持

**Comment by hakadao** [comment]
懸停樣式調整好了，4，5需求後期調整吧
暫時關注不了那麼多，後續有調整建議可以在這裏繼續討論，先關閉了

**Comment by SolitudeSun** [comment]
- 还有一处问题，视频收藏的勾选框、勾选框悬停、确认按钮悬停颜色也都不符 @hakadao 
    <img width="340" height="340" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/30c6cbcc-0960-48c6-8b4d-e34ce9b77bbf"><img width="340" height="340" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/acf80eef-b7a8-49e4-a9ac-e0457f9f81a3">

**Comment by hakadao** [comment]
去 #573 討論吧, 最後還是一個問題對應一個頁面的沒適配樣式地方
