### ISSUE TITLE
[BUG]: 设置界面展开下拉菜单，字体会模糊

### ISSUE THREAD

**Issue by Duck-Deng** [hakadao/BewlyBewly#541]
### 环境

浏览器: Firefox Dev
浏览器版本: 125.0b9
BewlyBewly 版本: 0.16.4

### 问题描述

设置界面展开下拉菜单，字体会模糊。
![图片](https://github.com/hakadao/BewlyBewly/assets/64295725/82b071df-0f5e-4224-a732-ffade3667dcb)
![图片](https://github.com/hakadao/BewlyBewly/assets/64295725/f0158b88-31c5-4b4c-98a7-9c60a539a88d)

这个问题似乎在firefox上独有，chrome上的字体渲染没有问题。另外，设置开关的样式错位可以被修复吗，这也是在firefox独有的bug

### 预期结果

字体应清晰、锐利的显示，而不应模糊。

**Comment by hakadao** [comment]
這些瀏覽器渲染問題不知道怎麼解決

**Comment by hakadao** [comment]
macOS firefox看沒有問題，是windows嗎
<img width="1800" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/117938c9-d831-4d47-8530-73214ac38a2b">
