### ISSUE TITLE
[BUG]:好像在火狐用不了

### ISSUE THREAD

**Issue by Duck15** [hakadao/BewlyBewly#545]
### 环境

浏览器: 火狐 国际版
浏览器版本: 124.0.2
BewlyBewly 版本:0.16.4

### 问题描述

![图片](https://github.com/hakadao/BewlyBewly/assets/95078036/87e7e019-b1c7-43e1-8872-0bf4671aaf5c)
如图，不显示登录（实际上已经登上了
还有视频流没得

### 预期结果

应该是显示出来的，这个插件在edge浏览器上工作正常

### 其他
还有一点：我的bewly是从 firefox 扩展商店 下载的
上面显示的更新时间和作者和这里一样

**Comment by mgqlfc** [comment]
同样问题，Firefox Nightly 126.0a1

**Comment by hakadao** [comment]
firefox的話要把這些權限都打開
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/3be5ac4d-4240-4429-8dc2-48b1990e88e6)

**Comment by Duck15** [comment]
> firefox的話要把這些權限都打開
> ![image](https://github.com/hakadao/BewlyBewly/assets/33394391/3be5ac4d-4240-4429-8dc2-48b1990e88e6)

非常感谢。firefox都没有提示这些。。
