### ISSUE TITLE
[BUG]:回到顶部后无法刷新内容

### ISSUE THREAD

**Issue by 000999888111** [hakadao/BewlyBewly#547]
### 环境

浏览器: Edge
浏览器版本: 123.0.2420.81
BewlyBewly 版本:  0.16.4

### 问题描述

设置隐藏顶栏后，在首页下滑超过一定距离后，点击回到顶部，此时顶栏会先出现随后隐藏，再次点击刷新会出现无法刷新内容且图标鬼畜的情况，但是点击Dock项可以刷新

**Comment by hakadao** [comment]
能否录制下视频

**Comment by hakadao** [comment]
哦知道了，如果首页内容没有加载完成的话点击刷新还是无效的，我做了限制防止过多请求b站接口导致b站以为是机器人误封原因
