### ISSUE TITLE
[suggestion] 添加不感興趣功能

### ISSUE THREAD

**Issue by JcLoveCode** [hakadao/BewlyBewly#548]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.107)
BewlyBewly 版本: (如 0.16.2)

### 问题描述

希望能保留原始b站的视频标题旁边 不感兴趣 的功能,对于不敢兴趣的视频可以点击.
不需要重新排序,当前已经加载的列表, 只需要保留遮罩表示这中视频已经被标识不感兴趣了.
这个对于个性话的页面定制很重要,
![image](https://github.com/hakadao/BewlyBewly/assets/42665711/63eaa3ec-e897-4a5d-ab00-8edb8651068b)

### 预期结果

![image](https://github.com/hakadao/BewlyBewly/assets/42665711/307cfe89-ff2a-4600-a3ff-eccb36359735)

**Comment by akira0245** [comment]
b站网页版自带的这个不感兴趣我记得只是个安慰剂按钮？没有实际用途

**Comment by hakadao** [comment]
可以先加個介面先（原本b站這裏點了實際上沒有發送任何請求）

**Comment by hakadao** [comment]
app端有不感興趣功能，那個是真的可以用着先
