### ISSUE TITLE
[BUG]: 通过顶栏悬停的动态>视频列表中，点击某个视频都会跳转到主页

### ISSUE THREAD

**Issue by aokisekiko** [hakadao/BewlyBewly#550]
### 环境

浏览器: Edge
浏览器版本 123.0.2420.81 
BewlyBewly 版本: 0.16.1

### 问题描述

在通过顶栏悬停后的动态>视频列表中，点击某个视频后，打开的页面都会跳转到bilibili首页，无论单击打开或鼠标右键选择在新标签页中打开
顶栏悬停>收藏夹无此问题
顶栏悬停>动态>直播无此问题
顶栏悬停>动态>专栏无此问题

### 预期结果

顶栏悬停>动态>视频列表中，点击某个视频能跳转到对应的视频

**Comment by laoshuikaixue** [comment]
遇到相同情况 并且无法正常加载动态

**Comment by CMJNB** [comment]
确实

**Comment by MengNianxiaoyao** [comment]
#517

**Comment by CMJNB** [comment]
是Edge商店未更新导致的

**Comment by aokisekiko** [comment]
从github下载安装更新了，感谢，应该是在商店发新版需要时间审核

在 2024年4月13日，19:05，CMJNB ***@***.***> 写道：

﻿

是Edge商店未更新导致的

**Comment by hakadao** [comment]
edge要一定時間審核，這速度比chrome和Firefox還漫長
<img width="1178" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/8d20af19-99ea-4edf-b6a7-363b61656a9d">
