### ISSUE TITLE
[BUG]: 顶部动态栏无法跳转/无法加载的问题

### ISSUE THREAD

**Issue by laoshuikaixue** [hakadao/BewlyBewly#551]
### 环境

浏览器: Edge
浏览器版本: 124.0.2478.27
BewlyBewly 版本: 插件商店版本 0.16.1

### 问题描述

![图片](https://github.com/hakadao/BewlyBewly/assets/79132480/09ab566d-fbc8-49f2-b002-450c26b5f0fd)

如图 顶部动态栏中 点击视频会跳转到主页 并且出现了无法加载动态的情况

### 预期结果

点击视频会跳转到对应视频

可以正常加载动态

**Comment by MengNianxiaoyao** [comment]
#517 ，issue重复不做回应

**Comment by laoshuikaixue** [comment]
> #517 ，issue重复不做回应

好的

**Comment by laoshuikaixue** [comment]
> #517 ，issue重复不做回应

Edge不更新了？

**Comment by hakadao** [comment]
> > #517 ，issue重复不做回应
> 
> Edge不更新了？

edge 更新受审核速度影响，可能解释的不太好我下次在issue模版说明清楚吧
