### ISSUE TITLE
【必看】插件更新说明

### ISSUE THREAD

**Issue by MengNianxiaoyao** [hakadao/BewlyBewly#552]
因Edge审核速度问题，插件版本会相较于Chrome和Release版本落后，所以最新版本修复的bug在Edge上未必能及时修正。所以当出现bug时，请先查看当前使用的插件版本并对比最新Release版本，然后搜索是否存在有相同问题的issue再进行报告。

重复和无意义的issue不仅降低了开发效率，也给开发者带来很大的心智负担，还给issue的处理和跟进带来了困难。为了减少无效issue对开发者进行干扰，当报告的issue存在相同内容时，我们将直接关闭，感谢理解。

如果你报告的问题在最新版确实存在，请重新提交一个新的issue并附上被关闭的issue链接，我们会进行问题跟进。

**Comment by hakadao** [comment]
感谢阁下帮忙解释，顺便放一下edge更新的审核截图吧，有时态度真不想那么强硬的但是edge那边审核说7个工作日又真的七个工作日
就非常难受，我们也控制不了审核速度的快慢

不过你可以在edge上通过chrome web store下载，不用管edge顶部的超大提示
实现快速更新

![image](https://github.com/hakadao/BewlyBewly/assets/33394391/d1d6597d-eece-4a4f-827c-51a5d9bae7d0)

**Comment by Rakau** [comment]
播放页面没有背景

**Comment by hakadao** [comment]
> 播放页面没有背景

目前只有首页可以设置背景，其他页面考虑到开发成本不提供背景设置，另外有问题请开新issue谢谢
