### ISSUE TITLE
[BUG]通知栏莫名999以及输入'/'符号焦点乱跳

### ISSUE THREAD

**Issue by thissensen** [hakadao/BewlyBewly#556]
### 环境

浏览器：Cent Browser 64位 5.1.1130.26（正式版本）
浏览器内核版本: Chromium 118.0.5993.159
BewlyBewly 版本: 0.16.4

### 问题描述

如图，莫名的999，昨天一次是页面挂着没动它，切回来一看999，今天是进一个视频上面显示999
![999截图](https://github.com/hakadao/BewlyBewly/assets/43516619/89d9d67e-b352-449c-b255-6f4f3825c6dd)

还有在我输入图片URL时，输到'/'符号，焦点就会跑到上面去，导致无法正确输入http链接
![异常焦点截图](https://github.com/hakadao/BewlyBewly/assets/43516619/4a6a6925-3fab-4bc2-9cd1-b691182383e8)

**Comment by hakadao** [comment]
好我去修复一下

**Comment by youwei828** [comment]
在页面中任何地方输入按下‘/’都会触发光标到searchInput @hakadao

**Comment by hakadao** [comment]
下版本修復
