### ISSUE TITLE
[BUG]画中画返回标签页异常

### ISSUE THREAD

**Issue by Biude** [hakadao/BewlyBewly#558]
### 环境

浏览器: (Edge)
浏览器版本: (123.0.2420.81)
BewlyBewly 版本: (0.16.4)

### 问题描述

停在视频页选择画中画后，选择返回标签页会在后台播放，需要刷新页面结束。如果在画中画点击×号可以正常结束
![`(A{Y@T{_S)XRMAPI9(_2TO](https://github.com/hakadao/BewlyBewly/assets/30528385/78e7c69d-101c-4263-9eed-cbea712f2128)
![~BHB _{SFEC_4$%N W)R5OQ](https://github.com/hakadao/BewlyBewly/assets/30528385/54e7f1b8-4914-4dc1-890a-3a30557b8636)
![U@D8$Y2D$_}I~3Y34N9TIIK](https://github.com/hakadao/BewlyBewly/assets/30528385/f5f77bc4-a3f2-459c-bccd-1b609b1c2178)

**Comment by hakadao** [comment]
這部份是瀏覽器自帶的功能，我改不了

**Comment by Biude** [comment]
ok，知道啦,大佬
