### ISSUE TITLE
[BUG]亮色模式下播放页的背景闪烁

### ISSUE THREAD

**Issue by Veikkkk** [hakadao/BewlyBewly#559]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.123)
BewlyBewly 版本: (如 0.16.4)

### 问题描述

亮色模式下，从网站任意位置点击视频卡片，打开播放页，背景会从黑色闪回白色。
播放页点击视频卡片，跳转到其他视频不会出现闪烁。

**Comment by hakadao** [comment]
下版本這種事情將會減緩
