### ISSUE TITLE
[bug]在搜索页面仍然会出现搜索框

### ISSUE THREAD

**Issue by Arsiendle** [hakadao/BewlyBewly#56]
[bug]在搜索页面仍然会出现搜索框,导致页面有两个搜索

**Comment by hakadao** [comment]
希望你提供一下版本號，觸發條件，圖，即使可能是之前的觸發方式我還是要知道是怎麼觸發的

**Comment by hakadao** [comment]
0.9.0已經修正，建議去chrome web store下載，審覈快一點 
第二個是原本b站在搜尋結果頁就是有兩個搜尋欄
https://chromewebstore.google.com/detail/bewlybewly/bbbiejemhfihiooipfcjmjmbfdmobobp

**Comment by hakadao** [comment]
之後考慮吧

**Comment by hakadao** [comment]
v0.10.1已處理
