### ISSUE TITLE
希望能加入调整暗色模式色深的功能

### ISSUE THREAD

**Issue by shibuyameltdown** [hakadao/BewlyBewly#560]
rt，现在的感觉太黑了，之前用隔壁bilibili envolved的rgb色值（34,34,34）感觉挺合适的
（话说为什么没找到enhancement 按钮）

**Comment by shibuyameltdown** [comment]
暂时用替换背景的方式解决了↓
https://p.sda1.dev/16/d2499546dba01d50a42fee23717cabb4/huise.png

**Comment by hakadao** [comment]
配色我自有自己的方案，不想跟別人的配色
