### ISSUE TITLE
[BUG]视频播放页面点击消息按钮后希望新打开标签页而不是在本页打开

### ISSUE THREAD

**Issue by Asakushen** [hakadao/BewlyBewly#561]
### 环境

浏览器: Microsoft Edge
浏览器版本: 123.0.2420.97 (正式版本) (64 位)
BewlyBewly 版本: 0.16.4

### 问题描述

希望在播放视频的页面，点击消息按钮是新打开标签页而不是在本页打开，这样会中断视频的播放，新打开标签页似乎也是官方的使用逻辑，更符合使用习惯即边看视频边看消息通知。
![image](https://github.com/hakadao/BewlyBewly/assets/74193315/afcc7683-8298-4c0c-9587-f5f8aea5c556)

### 预期结果

视频播放页面点击消息按钮打开新打开标签页，能够边看视频边看消息通知。

**Comment by hakadao** [comment]
可以嘗試按ctrl或中鍵打開新頁面，暫時不打算修改
