### ISSUE TITLE
Suggestion：能不能加入‘’对此内容不感兴趣‘’功能，方便调教个性推荐内容

### ISSUE THREAD

**Issue by CyunNaam** [hakadao/BewlyBewly#563]

**Comment by youwei828** [comment]
应该可以吧，看了一下api有点长，需要解析。可以看下这些文档《https://socialsisteryi.github.io/bilibili-API-collect/#%F0%9F%8D%B4%E7%9B%AE%E5%BD%95》有没有关于对此内容不感兴趣的api。

**Comment by hakadao** [comment]
https://github.com/hakadao/BewlyBewly/issues/548#issuecomment-2053563450

**Comment by hakadao** [comment]
b站网页不感兴趣没有实际用途
