### ISSUE TITLE
小屏状态下收藏按钮链接地址问题。

### ISSUE THREAD

**Issue by mingyue329** [hakadao/BewlyBewly#566]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.107)
BewlyBewly 版本: (如 0.16.2)

### 问题描述

小屏状态下收藏按钮链接地址问题。
![image](https://github.com/hakadao/BewlyBewly/assets/101497800/2a482182-1458-4ad6-9b73-e965fa742a8c)
![image](https://github.com/hakadao/BewlyBewly/assets/101497800/69b07ca1-25b3-4c6b-a562-83da26da8664)

**Comment by hakadao** [comment]
已修復新版本將更新
