### ISSUE TITLE
[BUG]右上角動態問題

### ISSUE THREAD

**Issue by vaz1306011** [hakadao/BewlyBewly#575]
### 环境

浏览器: Edge
浏览器版本: 123.0.2420.97
BewlyBewly 版本: 0.16.1

### 问题描述

右上角動態列表裡面關注的人更新的新視頻都會導向目前所在網頁
![image](https://github.com/hakadao/BewlyBewly/assets/50329983/a8997cc8-e110-492a-84d8-a774fe09eed5)
例如在首頁的話就會導向首頁
如果原本在看其他視頻也會導向原本在看的視頻網頁

**Comment by hakadao** [comment]
https://github.com/hakadao/BewlyBewly/issues/552#issuecomment-2053642669

**Comment by vaz1306011** [comment]
為什麼直接close掉了
