### ISSUE TITLE
[BUG] 主页 Tab 栏 "排行" 列表内，综艺分区下的视频未能成功加载

### ISSUE THREAD

**Issue by SolitudeSun** [hakadao/BewlyBewly#576]
### 环境

系统: Windows 11 23H2
浏览器: Microsoft Edge
浏览器版本: 123.0.2420.97
BewlyBewly 版本: 0.16.1

_已在最新版本 0.16.5 中测试，bug 仍旧可以复现_

### 如题，在主页 Tab 栏的 "排行" 列表内，综艺分区的视频出现了加载故障
![image](https://github.com/hakadao/BewlyBewly/assets/101030922/3ae43ed6-b257-4796-b2af-9ccc35f379b7)
### 其他分区内容都一切正常
![image](https://github.com/hakadao/BewlyBewly/assets/101030922/ca30016d-678d-47ad-aa74-6310507c83e8)

#### 恢复综艺分区视频显示

**Comment by hakadao** [comment]
已修復,後續版本將不再出現
