### ISSUE TITLE
Edge无法通过首页右侧动态栏进来视频播放界面[BUG]

### ISSUE THREAD

**Issue by yunfei-CMYK** [hakadao/BewlyBewly#577]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.107)
BewlyBewly 版本: (如 0.16.2)

### 问题描述

Edge无法通过首页右侧动态栏进来视频播放界面，会重新进入首页

**Comment by hakadao** [comment]
https://github.com/hakadao/BewlyBewly/issues/552
