### ISSUE TITLE
[BUG]首页动态中的视频点击后会跳转一个新的主页

### ISSUE THREAD

**Issue by umq34p99a3v8uqrpq984t** [hakadao/BewlyBewly#578]
### 环境

浏览器: edge
浏览器版本: 121.0.2277.112
BewlyBewly 版本: 0.06.1

### 问题描述

说不清楚，看视频吧

Uploading 2024-04-15 18-24-28.mp4…
[https://pan.huang1111.cn/s/6QAAsN](url)

**Comment by hakadao** [comment]
新版本早已修復, edge審覈問題導致遲遲沒有更新 #552
