### ISSUE TITLE
有一些个人想法和建议

### ISSUE THREAD

**Issue by runfall** [hakadao/BewlyBewly#58]
用了一段时间，感觉很不错，有一些想法建议

1.希望搜索页下滑滚轮可以滑到首页，这样会比首页使用搜索页模式会好很多

2.顶栏可见性希望改成下滑页面不显示，上滑页面显示出来

3.鼠标聚焦封面动画感觉挺不协调的，其实简单点没必要加动画或者最多把封面放大一点就行，显示一个稍后再看的标就行了（或者最好能像本来那样鼠标放封面上可以播放画面最好，不过感觉这样挺难吧？）

4.顶栏左边这几个 个性推荐 正在关注 热门视频 排行榜 位置看着也好奇怪呀，和整个顶栏不协调

**Comment by hakadao** [comment]
1. 之後首頁設定會加入調整搜尋頁模式高度，可以佔滿整頁，捲動後才顯示首頁內容
2. 這個特性已經記錄，會加的
3. 游標滑過播放影片卡片時播放畫面這個可以實現，不過之前一直在加功能導致這特性導致現在都沒有。滑過效果是抄twitch改的，這部分打算做特色一點，不想太過中規中矩
4. 設計靈感枯萎，暫時不知怎麼改

**Comment by runfall** [comment]
1.如果“調整搜尋頁模式高度，可以佔滿整頁，捲動後才顯示首頁內容”的话，启动页为首页时是直接显示首页内容 上滑才是搜索，还是直接显示搜索？想想倒不如取消首页显示搜索页模式，直接将搜索页设置为下滑直接进入首页

3.鼠标划过这个动画应该是用户体验最受影响的一个动画，在特色的同时其实没必要搞得太繁杂花哨，简约一点会更好（有一个点就是我会习惯直接通过这个封面动态动画来预览一下视频内容再决定是否点进去看，所以如果能保留这个动态效果就真的太好了）

4.将 个性推荐 正在关注 热门视频 排行榜 的位置上移让它们和搜索框保持一条线都行

**Comment by hakadao** [comment]
1. 我暫時不打算取消搜尋頁，不過後期會加上隱藏dock中的某些頁面的
3. 這個hover效果真不太想刪，或者調一下效果
4. 考慮到螢幕大小不同，同時放在一起不太容易，可能有些會超出無法顯示

**Comment by hakadao** [comment]
以上功能或改進都改了，先close了
