### ISSUE TITLE
是否会更新对Safari的支持

### ISSUE THREAD

**Issue by NozomiX1** [hakadao/BewlyBewly#582]
非常好看和实用的插件。
不过没有Safari版本的，将来会增加对Safari的支持吗？

**Comment by exgphe** [comment]
现在的feat/support-safari里面有兼容Safari的代码，可以手动编译：pnpm build完之后用pnpm convert-safari，然后在Xcode里面编译出Safari扩展。
我正在尝试编写能够自动发布Safari扩展的Github Action。
但是由于Safari扩展现在必须打包在一个macOS应用里，而对macOS App签名需要$99一年的开发者证书，我觉得在没有证书的情况下，即使能够自动发布Safari扩展了，也无法让普通用户能方便地安装上（要么每次启动Safari的时候都要修改Safari的设置允许未签名扩展，要么用户自行用codesign命令签名）。

**Comment by hakadao** [comment]
safari 支援不是問題，重要的還是 99 usd 每年費用上交 apple
b站做過調查大概 50% 人願意付費，投票總共50多個當25個願意
並且還是沒有統計能給出多少錢情況下，正常我如果可以也會做成買斷的。但是定價錢要考慮到是否能讓每個人接受到和能否抵銷 99 usd
目前我薪資不太好看，加上 safari 上也並不是多數 chrome 的擴充功能都有上架，之後只能是讓用戶手動簽名安裝

最後其實 safari 也不是 macOS 唯一瀏覽器，arc browser 也是一個不錯的選擇

**Comment by monako97** [comment]
我尝试打包了一个Safari扩展, 你或许可以试试

[BewlyBewly.zip](https://github.com/hakadao/BewlyBewly/files/15047525/BewlyBewly.zip)

**Comment by xianfei** [comment]
> 我尝试打包了一个Safari扩展, 你或许可以试试
> 
> [BewlyBewly.dmg.zip](https://github.com/hakadao/BewlyBewly/files/15047559/BewlyBewly.dmg.zip)

感谢，十分好用。
提一个小小的建议：加入`<meta name="theme-color" content="#f2f2f8">`来让Safari的顶栏变色，更好看（如下图）

JS实现代码：
```javascript
let themeColorMeta = document.createElement('meta');
themeColorMeta.name = 'theme-color';
document.head.appendChild(themeColorMeta);
themeColorMeta.content = color; // 此处换为背景色
```

<img width="1417" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/8101613/df017bcd-e0ee-4ed0-abf9-a253ee4cb22a">
