### ISSUE TITLE
是否可以对主页的视频加载进行优化

### ISSUE THREAD

**Issue by thissensen** [hakadao/BewlyBewly#583]
版本：0.16.5
如图，最下方一排经常只刷出1个视频，只有滚轮继续往下才会加载一排出来
![QQ截图20240415232600](https://github.com/hakadao/BewlyBewly/assets/43516619/f0ebf8e5-6a23-4d70-8ae0-5e7c7aafdfc9)

**Comment by hakadao** [comment]
我已經是做了沒有滑到底部就提前觸發更新了
