### ISSUE TITLE
【功能建议】bilibili官方新版主页已更新 “内容不感兴趣/不想看此UP主” 功能，希望插件这边也能添加这个功能

### ISSUE THREAD

**Issue by ahai64** [hakadao/BewlyBewly#584]
![image](https://github.com/hakadao/BewlyBewly/assets/148314633/3de3b438-c70c-495d-a651-8895fcf40fad)

**Comment by hakadao** [comment]
App 端有，web 端b站网页版就做了个ui没有发送任何请求也就是说没什么用，已经解答过很多个这样问题了
<img width="1027" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/b46f3f90-3b6d-468e-8797-c6e537abfde0">
<img width="419" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/b2d704e7-7bab-476f-9227-54bb07401481">

**Comment by ahai64** [comment]
刚刚进 DevTools 看了下现在 Web 端也会发送 post 请求了，并且 status 的值会根据选项变化。
