### ISSUE TITLE
在【正在关注】里无法看到up主发的动态视频

### ISSUE THREAD

**Issue by qq164004640** [hakadao/BewlyBewly#589]
### 环境

浏览器: (360极速浏览器X)
版本号：22.1.1090.64（64位）
内核版本：119.0.6045.160

### 问题描述

无法看到动态视频，只能在以前原版位置查看到
![Snipaste_2024-04-16_09-02-53](https://github.com/hakadao/BewlyBewly/assets/59138378/1d2c3d47-b259-4e43-8a2d-88dd84b2c7e0)

**Comment by hakadao** [comment]
b站接口沒有返回這些數據我也很絕望
