### ISSUE TITLE
v9.2edge无法安装

### ISSUE THREAD

**Issue by flashorsink** [hakadao/BewlyBewly#59]
浏览器edge，v9.2的zip拖入扩展提示：无法从以下源加载扩展: D:\Download\extension.zip. Could not unzip extension for install.
试了下v9.0是可以直接拖入安装的

**Comment by hakadao** [comment]
[extension.zip](https://github.com/hakadao/BewlyBewly/files/13185514/extension.zip)
試試這個

**Comment by flashorsink** [comment]
> [extension.zip](https://github.com/hakadao/BewlyBewly/files/13185514/extension.zip) 試試這個

这个可以
