### ISSUE TITLE
[BUG]在视频界面下的Dock栏中点击动态，还是会返回原视频

### ISSUE THREAD

**Issue by ryanvily** [hakadao/BewlyBewly#590]
### 环境

浏览器: Edge
浏览器版本: 125.0.2506.0 (正式版本) dev (64 位)
BewlyBewly 版本: [v0.16.5]

### 问题描述

在视频的界面下，点击Dock栏中的动态下滑页中的视频，会自动跳回原视频所在的页面，而不是所点击动态中目标视频界面！

**Comment by hakadao** [comment]
请看 #552
且问题已经重复 #578 #577 #575

**Comment by hakadao** [comment]
不是bug, 如果还是视频的话直接在当前页跳转不开新页面

**Comment by ryanvily** [comment]
是浏览器的问题，chrome没有问题

**Comment by hakadao** [comment]
> 是浏览器的问题，chrome没有问题
> 
> 

檢查一下edge的bewlybewly是不是最新版，還是與chrome版本弄混了

**Comment by ryanvily** [comment]
BewlyBewly是最新的了

**Comment by hakadao** [comment]
> BewlyBewly是最新的了
> 
> 

是顶栏的动态弹窗还是什么

**Comment by Yehhhhhhh** [comment]
我也有这个问题
Microsoft Edge
版本 123.0.2420.97 (正式版本) (64 位)
BewlyBewly 版本0.16.1
视频页面在Dock栏 鼠标放在动态上下方的窗口点击动态的视频后 会刷新当前视频页面但不会切换到点击的动态视频
在首页进行同样操作会打开一个新的页面 但这个新的页面还是首页

**Comment by hakadao** [comment]
閣下能否有進一步的說明或影片演示? 如果確定是舊版本的問題的話我先 close 了
