### ISSUE TITLE
[BUG] Nav top bar 动态视频点击后跳转主页，而并非视频页面

### ISSUE THREAD

**Issue by chuxu200328** [hakadao/BewlyBewly#593]
### 环境

浏览器: Edge
浏览器版本: 123.0.2420.97
BewlyBewly 版本: 0.61.1

### 问题描述

疑似moment.url缺失，导致打开空白窗口。
![image](https://github.com/hakadao/BewlyBewly/assets/20890965/6f2b9ca5-75e0-4381-b920-db1bf603b58e)

**Comment by hakadao** [comment]
请看 #552
重复 #578 #577 #551
