### ISSUE TITLE
[BUG]登录一段时间后首页没有内容

### ISSUE THREAD

**Issue by zanezii** [hakadao/BewlyBewly#596]
### 环境

浏览器: Chrome
浏览器版本:123.0.6312.59
BewlyBewly 版本: 0.16.1

### 问题描述

登录一段时间后，无法获取登录状态，首页无法获取任何推送；右上角重新登录后依然要求登录
![image](https://github.com/hakadao/BewlyBewly/assets/56388022/f40122fa-0122-4769-b842-574a351d2452)

插件报错：
![image](https://github.com/hakadao/BewlyBewly/assets/56388022/4f57f508-2d3d-4209-a039-a824d828f3e6)

**Comment by MengNianxiaoyao** [comment]
更新一下插件版本，你用的旧版

**Comment by hakadao** [comment]
新版本是 v0.16.5 你更新後看看
