### ISSUE TITLE
[BUG]主页中不同视频标题字体大小不一致

### ISSUE THREAD

**Issue by Yehhhhhhh** [hakadao/BewlyBewly#597]
### 环境

浏览器: Edge
浏览器版本: 123.0.2420.97 (正式版本) (64 位)
BewlyBewly 版本: 0.16.5

### 问题描述

**未开启扩展**
<img width="1275" alt="1" src="https://github.com/hakadao/BewlyBewly/assets/148741685/4fa7ee2a-2f02-4d57-8dc3-2e8a75f70d0b">
**开启扩展**
<img width="1275" alt="2" src="https://github.com/hakadao/BewlyBewly/assets/148741685/1cf170d7-e59d-4f14-9c2f-c0e95d9dbab5">

开启扩展时投稿、合集与列表字体也会比未开启扩展时大，但主页下方合集中字体又与未开启扩展时一致

### 预期结果

字体大小与未开启扩展时一致

**Comment by hakadao** [comment]
與  #365 其實同樣一個原因, 去那邊討論吧如果可以的話. 暫時不會解決這個
