### ISSUE TITLE
[BUG]无法显示B站内容

### ISSUE THREAD

**Issue by MiunaQwQ** [hakadao/BewlyBewly#598]
### 环境

浏览器: Firefox
浏览器版本: bewlybewly
BewlyBewly 版本: 0.16.5

### 问题描述

启用插件后大部分界面黑屏并显示未登录，点击登录按钮B站会显示已登录并跳转回当前页面，但还是会显示未登录。
其他侧边栏功能（番剧、历史、收藏）都无法使用。
![图片](https://github.com/hakadao/BewlyBewly/assets/84217789/f4133ce5-aecc-4995-88af-00ebd9e1803b)

**Comment by hakadao** [comment]
這是 firefox 獨有的特性, 可參考這個解決
https://github.com/hakadao/BewlyBewly/issues/545#issuecomment-2053352916
