### ISSUE TITLE
[BUG] 收藏的音乐在 `顶栏` 与 `Dock栏` 均不能正常跳转

### ISSUE THREAD

**Issue by SolitudeSun** [hakadao/BewlyBewly#606]
### 环境

浏览器: Microsoft Edge
浏览器版本: 123.0.2420.97
BewlyBewly 版本: 0.16.5

### 收藏的音乐在 `顶栏` 与 `Dock栏` 均不能正常跳转
> **BiliBili 有个播放音乐的区域，哔哩哔哩音乐，每首音乐可以正常`投币`、`收藏`、`评论`、`转发`，当收藏某首音乐时，**
> **BewlyBewly 插件在主页的 `Dock栏` 或 `顶栏` 中，点击收藏的音乐都不能正常跳转至 [https://www.bilibili.com/audio/](https://www.bilibili.com/audio/)**
> **并且导致收藏的样式也有部分错误，例如：用户头像不能正常显示导致文字错位**

<img width="400" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/3825a978-86f7-4d8c-80e2-4322b4fb543b"><img width="400" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/f36e5ea3-0935-4fb7-b040-a8b6dcf4adf8">

> **如图，上述链接点击后均跳转至如图如示的毫无相关的视频中，正常跳转的链接应如右下图所示**

<img width="400" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/1b437fd6-c7cd-4dc3-b392-4028455b2622"><img width="400" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/d5d931e0-178f-4043-86ef-bc40e99ac69d">

> **[音乐示例链接](https://www.bilibili.com/audio/au2546275)**

### 正常跳转收藏的音乐链接

**Comment by hakadao** [comment]
這裏up主的頭像（face）沒有返回
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/b47166fe-4e30-4666-b01f-522d6b6608b9)
