### ISSUE TITLE
建议：修改主页播放量和弹幕数量显示的方式

### ISSUE THREAD

**Issue by Potat0Servers** [hakadao/BewlyBewly#608]
目前首页的显示方式：xxx次（播放量） xxx弹幕
![image](https://github.com/hakadao/BewlyBewly/assets/66018299/14d4d6f6-b4f9-4328-8093-5c58c9295351)

这种显示方式不如b站原生的：*小电视符号*xxx（播放量） *弹幕符号*xxx（弹幕量）
![image](https://github.com/hakadao/BewlyBewly/assets/66018299/35f301e0-2023-40ac-8332-0718cdfc51d2)

后者更加直观

**Comment by hakadao** [comment]
不考慮改暫時
