### ISSUE TITLE
授权 access key 失败: 该版本已不支持当前功能，请升级新版本！

### ISSUE THREAD

**Issue by Doushabao233** [hakadao/BewlyBewly#61]
rt

![image](https://github.com/hakadao/BewlyBewly/assets/64591791/84c60177-10ea-4071-afdc-180f1188f8df)

版本v9.2

**Comment by hakadao** [comment]
目前暫時不知道怎麼解決，應該是b站那邊做了限制

**Comment by hakadao** [comment]
v0.10.3已解決
