### ISSUE TITLE
关于页面间距的建议

### ISSUE THREAD

**Issue by Suheisdead** [hakadao/BewlyBewly#62]
![image](https://github.com/hakadao/BewlyBewly/assets/105153810/b7d41d51-2d31-49c5-b5f3-e1c220008236)

1、左上角的四块和顶栏、第一行视频放在一起有点过于紧凑，希望能增加彼此的留白；
2、下面的视频间横行间距过窄（特别是鼠标悬停在视频上）而纵列间距过宽，两个放在一起形成对比就更明显了，希望能调整一下间距。

**Comment by hakadao** [comment]
这个之后根据实际情况调整，感谢提议

**Comment by hakadao** [comment]
v0.10.1 版本已經調了一下
