### ISSUE TITLE
原来的三个点的反馈按钮没了

### ISSUE THREAD

**Issue by Mathsword** [hakadao/BewlyBewly#620]
### 环境

浏览器: Edge
浏览器版本:124.0.2478.51 (正式版本) (64 位)
BewlyBewly 版本: (如 0.16.2)

### 问题描述

bilibili原来首页的视频标题右上角会有三个点，点击后会显示“内容不感兴趣/不想看此up主，但是用了插件后没有这个功能了

**Comment by hakadao** [comment]
https://github.com/hakadao/BewlyBewly/issues/584#issuecomment-2057400334
