### ISSUE TITLE
[BUG]界面显示异常

### ISSUE THREAD

**Issue by Lucas04-nhr** [hakadao/BewlyBewly#623]
### 环境

浏览器: Google Chrome
浏览器版本: 124.0.6367.61 (Official Build) (arm64) 
BewlyBewly 版本: 0.16.5

### 问题描述

界面切换为英文后，"For you（个性推荐）"界面的中文会显示为繁体，但是其余tab没有影响
<img width="1597" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/117806313/a16d3191-24ab-4d3e-aadb-621334847ead">
<img width="1532" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/117806313/4ec072b3-d4b1-4206-8bfc-ff3f30c68725">
附：本人也启用了Bilibili Evolved插件中的自定义字体功能，但是经过测试，该功能对于上述显示bug没有影响

### 预期结果

中文正常显示为简体

**Comment by hakadao** [comment]
判斷寫得不太好之前，其實繁體字是b站返回的，後續調整一下就可以了
