### ISSUE TITLE
建议：增加主页刷新按钮常驻选项

### ISSUE THREAD

**Issue by Alan-CRL** [hakadao/BewlyBewly#626]
我非常喜欢 [BewlyBewly](https://github.com/hakadao/BewlyBewly) 的界面设计，不过我想提出一个建议。

当我的屏幕较小时，或有其他需要时，我需要向下滑动才能看到主页全部内容，但是一旦向下滑动后，刷新按钮就会变为向上按钮，这使我很难受。我希望可以出一个选项让刷新按钮常驻，待向下滑动过后再出现一个新的按钮是向上，这样可以完美的解决问题。

最后由衷的感谢 [BewlyBewly](https://github.com/hakadao/BewlyBewly) 开发团队，希望可以解决我的问题。

**Comment by hakadao** [comment]
双击回到顶部或dock里的icon或首页左上脚的表情都可以实现刷新

**Comment by Alan-CRL** [comment]
我并不认为双击回到顶部可以解决我的问题，如下面视频中，我双击了回到顶部，不但没有刷新，还被迫回到了顶部，这应该是个问题。请注意，我不想被迫回到顶部，正如前面所说，我如果主页使用了搜索页样式，注定我想向下滑动一些才能观看视频，每次回到顶部后，还必须重新向下滑动，望改进。[附件视频](https://www.123pan.com/s/duk9-3idAd.html)

**Comment by Alan-CRL** [comment]
@hakadao 是在抱歉，关闭的 issues 你可能看不到我的评论，希望可以回复一下我的新想法

**Comment by hakadao** [comment]
你可以嘗試直接雙擊首頁的標籤

**Comment by Alan-CRL** [comment]
@hakadao 实在抱歉，我不是很理解你的意思。请注意，我不想被迫回到顶部，正如前面所说，我如果主页使用了搜索页样式，注定我想向下滑动一些才能观看视频，每次回到顶部后，还必须重新向下滑动。[附件视频](https://www.123pan.com/s/duk9-3idAd.html)

**Comment by hakadao** [comment]
> @hakadao 实在抱歉，我不是很理解你的意思。请注意，我不想被迫回到顶部，正如前面所说，我如果主页使用了搜索页样式，注定我想向下滑动一些才能观看视频，每次回到顶部后，还必须重新向下滑动。[附件视频](https://www.123pan.com/s/duk9-3idAd.html)

就是雙擊這裏實現不回到頂部刷新
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/825902e1-11d6-4814-af45-be68d80929c9)

**Comment by hakadao** [comment]
這個右下角的按鈕做出來的目的只是爲了直覺點操作，實際上不要這個按鈕也能實現back to top & refresh的操作
放多一個按鈕的話就有點擁擠多餘了

**Comment by Alan-CRL** [comment]
@hakadao 感谢耐心讲解，我的问题已经得到解决，由衷感谢您

**Comment by Alan-CRL** [comment]
@hakadao 接下来是建议部分，我还是希望可以在页面任意位置刷新，但**不会**回到顶部。正如您上面所说 点击 for you 按钮依旧会有一个向上滚动的操作。尽管我的需求有些奇怪，但是还是希望你们可以考虑。

**Comment by hakadao** [comment]
> @hakadao 接下来是建议部分，我还是希望可以在页面任意位置刷新，但**不会**回到顶部。正如您上面所说 点击 for you 按钮依旧会有一个向上滚动的操作。尽管我的需求有些奇怪，但是还是希望你们可以考虑。

我单独开个需求吧这个

**Comment by Alan-CRL** [comment]
@hakadao 万分感谢
