### ISSUE TITLE
[feature request] 动态页面移除右上角的社区中心图片 (t.bilibili.com)

### ISSUE THREAD

**Issue by neotpravlennoye** [hakadao/BewlyBewly#637]

**Comment by hakadao** [comment]
目前可以透過這個腳本實現
https://greasyfork.org/zh-CN/scripts/479861-bilibili-%E9%A1%B5%E9%9D%A2%E5%87%80%E5%8C%96%E5%A4%A7%E5%B8%88

BewlyBewly 不打算做太多對b站功能調整的東西，專注於研究頁面及操作重構
