### ISSUE TITLE
建议添加功能：链接均在当前页面打开的设置

### ISSUE THREAD

**Issue by Anyayay** [hakadao/BewlyBewly#64]
我想在设置中能有链接均在当前页面打开的开关，这样我就能将b站网页作为应用添加到桌面，而之后的操作不会再次跳转到浏览器

**Comment by hakadao** [comment]
之前試過，但是首頁推介的內容在跳轉頁面後不會像youtube一樣保存狀態，後面就沒有做了

**Comment by Anyayay** [comment]
> 之前試過，但是首頁推介的內容在跳轉頁面後不會像youtube一樣保存狀態，後面就沒有做了

还是建议做一下吧，可以在下面提示不会保存刚刚的推荐状态
因为我真的认为你的作品真的可以让我取代b站客户端

**Comment by starknt** [comment]
> 之前試過，但是首頁推介的內容在跳轉頁面後不會像youtube一樣保存狀態，後面就沒有做了

想要保存页面的状态感觉不太可能，因为B站和youtube的页面结构不同，B站的大部分功能都分布在不同的页面中。

**Comment by hakadao** [comment]
> > 之前試過，但是首頁推介的內容在跳轉頁面後不會像youtube一樣保存狀態，後面就沒有做了
> 
> 想要保存页面的状态感觉不太可能，因为B站和youtube的页面结构不同，B站的大部分功能都分布在不同的页面中。

我其實想過用iframe實現，但是發現是個巨坑。。。過後最多設置頂欄連結都在當前頁打開算了

**Comment by douseful** [comment]
非常期待这个功能，配合arc应该会很舒服。

**Comment by hakadao** [comment]
> 非常期待这个功能，配合arc应该会很舒服。

這個實現出來會有點問題的，比如返回時首頁狀態不能保存
