### ISSUE TITLE
顶部栏 Hover 收藏图标后弹出小窗中的收藏内容无法自动更新

### ISSUE THREAD

**Issue by yingyingyingqwq** [hakadao/BewlyBewly#65]
每次 Hover 的时候显示出来的小窗都会显示非常久之前的收藏内容，而不是最近的。
需要在小窗内切换到另一个收藏夹再切换回去才能正常显示内容。

**我确定我已经将插件更新到了Chrome插件商店的最新版本。**
**我亦已确定在此之前没有同样的 Issue 被提出。**

**Comment by yingyingyingqwq** [comment]
**使用的浏览器：**
Microsoft Edge | 114.0.1823.58 _(正式版本) (64 位)_
Chromium 版本 | 114.0.5735.134

**系统版本：**
Windows 11 22H2

**Comment by Seayay** [comment]
+1

Google Chrome
版本 121.0.6108.0（正式版本）canary （64 位）

**Comment by hakadao** [comment]
改了一下标题，应该就是想表达这个意思吧

**Comment by yingyingyingqwq** [comment]
只有收藏图标有此种情况，暂时在 动态、历史观看记录 未发现此种情况。

**Comment by hakadao** [comment]
v0.10.1 版本已修正
