### ISSUE TITLE
建议添加功能：Dock能跳转动态页

### ISSUE THREAD

**Issue by SilverB0w** [hakadao/BewlyBewly#66]
由于个人偏爱收看订阅的信息源，而非推送，因此只能跳转到「首页」这一点会挺难受的，希望作者能出：

1.Dock直接跳转动态页
2.启动页为「动态」页面

感谢。

BTW，设计很好看，孩子很喜欢。

**Comment by hakadao** [comment]
之後做會專門做一個動態頁的，dock的頁面目前只想是跳轉bewlybewly自己的頁面
