### ISSUE TITLE
主页视频div在鼠标快速滑动时显示异常

### ISSUE THREAD

**Issue by yingyingyingqwq** [hakadao/BewlyBewly#67]
在首页每个视频的div从底部（实际上是div下方的空位）向上快速滑动鼠标到中部会不断反复地播放Hover动画，导致div闪烁。
此异常非常容易复现。

**Comment by hakadao** [comment]
這個問題知道，暫時不知怎麼解決

**Comment by yingyingyingqwq** [comment]
感觉像是渲染器问题，应该没法怎么修。

**Comment by hakadao** [comment]
@yingyingyingqwq 下版本打算把這動畫刪了或用其他表現形式

**Comment by hakadao** [comment]
v0.12.0應該沒有了
