### ISSUE TITLE
个性化

### ISSUE THREAD

**Issue by huanlu233** [hakadao/BewlyBewly#70]
建议在设置中可以设置每个视频的间隔
![image](https://github.com/hakadao/BewlyBewly/assets/100133765/bff4003f-1dad-4969-ba41-dcb3d6a3bc4c)
不然一个页面看不完标题，或者图片

**Comment by hakadao** [comment]
這個調一下Windows縮放吧，顯示卡片個數是根據螢幕大小調整的
