### ISSUE TITLE
使用APP算法推荐时刷不出主页

### ISSUE THREAD

**Issue by xiaojiejieouo** [hakadao/BewlyBewly#71]
![image](https://github.com/hakadao/BewlyBewly/assets/78160136/35a860a5-b3bf-4f71-8a37-9c6da98e6560)
启用网页则能刷出来

**Comment by hakadao** [comment]
暫時沒有重現，這種情況是偶然還是經常？有沒有甚麼觸發條件

**Comment by xiaojiejieouo** [comment]
暫時未發現重現條件，頻率大概兩三天一次，如果頁面空白時從設定內把app算灋更改為網頁算灋時就能重繪出來貼片,如果您方便的情况下，我可以把我使用過程的視頻發到bilibili上

**Comment by hakadao** [comment]
有用其它插件嗎

**Comment by xiaojiejieouo** [comment]
是的，有adguard，油猴挿件等，但是我嘗試過關閉它們，仍舊不能重繪出主頁

**Comment by magicdawn** [comment]
我的推荐里番剧很多, 也会白屏

TypeError: Cannot use 'in' operator to search for 'avatar' in undefined
    at index.global.js:73:83736
    at Me (index.global.js:1:36474)
    at Proxy.<anonymous> (index.global.js:73:83608)
    at xa (index.global.js:1:26424)
    at pa.Q [as fn] (index.global.js:1:52059)
    at pa.run (index.global.js:1:14583)
    at A.update (index.global.js:1:52810)
    at Wn (index.global.js:1:23176)

```
author: "avatar"in g.mask ? g.mask.avatar.text : "",
"author-face": "avatar"in g.mask ? g.mask.avatar.cover : "",
mid: g.mask.avatar.up_id,
```

```json
{
  "card_type": "banner_ipad_v8",
  "card_goto": "banner",
  "args": {},
  "idx": 22,
  "track_id": "all_49.router-pegasus-1359033-76cf68d466-2w65p.1701851454078.482",
  "hash": "14656702573111666798",
  "banner_item": [
    {
      "id": 1414658,
      "title": "朱一龙追击离奇凶案，陷入“疯癫”",
      "image": "http://i0.hdslb.com/bfs/banner/0c1d559a5dd4587e33d438b3aa1534761be2ff5e.png",
      "hash": "2f4f75fb57cd6fe84398aec5e3595ce6",
      "uri": "https://www.bilibili.com/bangumi/play/ep790226",
      "request_id": "1701851454461q172a27a117a60q2604",
      "src_id": 4341,
      "is_ad_loc": true,
      "client_ip": "0.0.0.0",
      "server_type": 0,
      "resource_id": 4340,
      "index": 1,
      "cm_mark": 0
    },
    {
      "id": 0,
      "title": "1.5周年，上线领自选猎人！",
      "image": "https://i0.hdslb.com/bfs/sycp/creative_img/202312/5df772ab610d3935f593dd508ca04e30.jpg",
      "hash": "d4c9886f3f03ce6d3e1567afc529f059",
      "uri": "https://game.bilibili.com/sklr3/tsmj/h5?msource=1&source=trackadf_5a61ba3af1e847c282e64802383680be&gameID=5840",
      "request_id": "1701851454461q172a27a117a60q2604",
      "creative_id": 834862705376211000,
      "src_id": 4342,
      "is_ad": true,
      "is_ad_loc": true,
      "ad_cb": "",
      "show_url": "",
      "click_url": "",
      "client_ip": "0.0.0.0",
      "server_type": 1,
      "resource_id": 4340,
      "index": 2,
      "cm_mark": 1,
      "extra": {
        "use_ad_web_v2": false,
        "show_urls": [
          ""
        ],
        "click_urls": [
          ""
        ],
        "download_whitelist": [],
        "open_whitelist": [],
        "card": {
          "card_type": 0,
          "title": "1.5周年，上线领自选猎人！",
          "covers": [
            {
              "url": "https://i0.hdslb.com/bfs/sycp/creative_img/202312/5df772ab610d3935f593dd508ca04e30.jpg",
              "loop": 0,
              "image_height": 0,
              "image_width": 0,
              "gif_tag_show": false,
              "jump_url": "",
              "title": "",
              "desc": ""
            }
          ],
          "jump_url": "https://game.bilibili.com/sklr3/tsmj/h5?msource=1&source=trackadf_5a61ba3af1e847c282e64802383680be&gameID=5840",
          "desc": "",
          "callup_url": "",
          "long_desc": "",
          "ad_tag": "",
          "extra_desc": "",
          "universal_app": "",
          "duration": "",
          "adver": {
            "adver_id": 36,
            "adver_type": 3
          },
          "extreme_team_status": false,
          "support_transition": false,
          "under_player_interaction_style": 0,
          "referral_pop_active_time": 10000,
          "grade_denominator": 0,
          "star_level": 0,
          "live_booking_population_threshold": 0,
          "ori_mark_hidden": 0,
          "use_multi_cover": false,
          "custom_feedback_panels": [],
          "yellow_cart_pannel_pullup": 0,
          "yellow_cart_pannel_version": 0,
          "goods_item_id": 0,
          "story_interaction_style": 0,
          "videos": [],
          "download_area": 0,
          "goods_pannel_show": 0,
          "goods_panel_show": 0,
          "show_pop_window": 0,
          "ad_tag_style": {
            "type": 2,
            "text": "广告",
            "text_color": "#999999FF",
            "bg_border_color": "#999999FF",
            "bg_color": "#999999FF",
            "border_color": "#999999FF"
          },
          "feedback_panel": {
            "panel_type_text": "广告",
            "feedback_panel_detail": [],
            "toast": "将减少相似广告推荐",
            "close_rec_tips": "操作成功",
            "open_rec_tips": "将减少展示此类广告"
          },
          "fold_time": 0,
          "live_room_popularity": 0,
          "live_tag_show": false,
          "quality_infos": [],
          "dynamic_text": "1.5周年，上线领自选猎人！",
          "choose_button_list": [],
          "grade_level": 0,
          "anim_in_enable": 0,
          "underframe_card_style": 0,
          "live_auto_play": false
        },
        "report_time": 2000,
        "appstore_priority": 2,
        "sales_type": 31,
        "special_industry": false,
        "special_industry_tips": "",
        "preload_landingpage": 0,
        "share_info": {},
        "upzone_entrance_type": 0,
        "upzone_entrance_report_id": 0,
        "click_area": 0,
        "shop_id": 0,
        "up_mid": 0,
        "track_id": "pbaes.CspX-QTdpL9KncgQzc2-Mm95dCcjkiCMu_rZImtoRamUVs6HAt2-OkahIWbfCXCp3AEEQJumjTujzGtYp2o_mGkvHcGDlJ-F_zoRYV5W7QM=",
        "enable_store_direct_launch": 0,
        "enable_double_jump": false,
        "store_callup_card": false,
        "enable_h5_alert": false,
        "special_industry_style": 0,
        "macro_replace_priority": 1,
        "feedback_panel_style": 0,
        "ad_content_type": 0,
        "enable_h5_pre_load": 0,
        "hot_activity_id": 0,
        "product_id": 0,
        "landingpage_download_style": 2,
        "download_url_type": 0,
        "enable_auto_callup": 0,
        "top_live_stay_time_seconds": 0
      }
    },
    {
      "id": 1414730,
      "title": "投稿瓜分3W现金奖励",
      "image": "http://i0.hdslb.com/bfs/banner/ab4969fb8fe3062a2a89bbf0a563c8d1afd3b98f.jpg",
      "hash": "2d41f2a097c1633ae6b11fb23d55a142",
      "uri": "https://www.bilibili.com/blackboard/activity-AIaWvFlxWE.html",
      "request_id": "1701851454461q172a27a117a60q2604",
      "src_id": 4343,
      "is_ad_loc": true,
      "client_ip": "0.0.0.0",
      "server_type": 0,
      "resource_id": 4340,
      "index": 3,
      "cm_mark": 0
    }
  ]
}
```


和

```json
{
  "card_type": "large_cover_v1",
  "card_goto": "bangumi",
  "goto": "bangumi",
  "param": "342206",
  "cover": "http://i0.hdslb.com/bfs/bangumi/image/ea90ff4fc8cea3437b0e57d6535f3c4cba252d9c.jpg",
  "title": "一出好戏",
  "uri": "https://www.bilibili.com/bangumi/play/ep342206?goto=bangumi&report_flow_data=%7B%22flow_card_type%22%3A%22bangumi%22%2C%22flow_source%22%3A%22bangumi%22%7D&theme=movie&trackid=all_49.router-pegasus-1359033-76cf68d466-2w65p.1701851454078.482",
  "three_point": {
    "dislike_reasons": [
      {
        "id": 1,
        "name": "不感兴趣",
        "toast": "将减少相似内容推荐"
      }
    ]
  },
  "args": {},
  "idx": 21,
  "three_point_v2": [
    {
      "title": "不感兴趣",
      "type": "dislike",
      "id": 1
    }
  ],
  "track_id": "all_49.router-pegasus-1359033-76cf68d466-2w65p.1701851454078.482",
  "material_id": 9617,
  "dislike_report_data": "{\"material_id\":9617}",
  "report_flow_data": "{\"flow_card_type\":\"bangumi\",\"flow_source\":\"bangumi\"}",
  "avatar": {
    "cover": "http://i0.hdslb.com/bfs/bangumi/image/fffaa4070fd8c23a3490ef3eb91eda6be7d848e7.jpg",
    "type": 1
  },
  "cover_left_text_1": "953万",
  "cover_left_text_2": "23.1万",
  "cover_badge": "电影",
  "cover_badge_style": {
    "text": "电影",
    "text_color": "#FFFFFF",
    "bg_color": "#FB7299",
    "border_color": "#FB7299",
    "text_color_night": "#E5E5E5",
    "bg_color_night": "#BB5B76",
    "border_color_night": "#BB5B76",
    "bg_style": 1
  },
  "desc": "2018-08-10上映",
  "cover_left_icon_1": 1,
  "cover_left_icon_2": 4
}
```

目前发现这两种没有 mask

**Comment by hakadao** [comment]
> 我的推荐里番剧很多, 也会白屏
> 
> TypeError: Cannot use 'in' operator to search for 'avatar' in undefined at index.global.js:73:83736 at Me (index.global.js:1:36474) at Proxy. (index.global.js:73:83608) at xa (index.global.js:1:26424) at pa.Q [as fn] (index.global.js:1:52059) at pa.run (index.global.js:1:14583) at A.update (index.global.js:1:52810) at Wn (index.global.js:1:23176)
> 
> ```
> author: "avatar"in g.mask ? g.mask.avatar.text : "",
> "author-face": "avatar"in g.mask ? g.mask.avatar.cover : "",
> mid: g.mask.avatar.up_id,
> ```
> 
> ```json
> {
>   "card_type": "banner_ipad_v8",
>   "card_goto": "banner",
>   "args": {},
>   "idx": 22,
>   "track_id": "all_49.router-pegasus-1359033-76cf68d466-2w65p.1701851454078.482",
>   "hash": "14656702573111666798",
>   "banner_item": [
>     {
>       "id": 1414658,
>       "title": "朱一龙追击离奇凶案，陷入“疯癫”",
>       "image": "http://i0.hdslb.com/bfs/banner/0c1d559a5dd4587e33d438b3aa1534761be2ff5e.png",
>       "hash": "2f4f75fb57cd6fe84398aec5e3595ce6",
>       "uri": "https://www.bilibili.com/bangumi/play/ep790226",
>       "request_id": "1701851454461q172a27a117a60q2604",
>       "src_id": 4341,
>       "is_ad_loc": true,
>       "client_ip": "0.0.0.0",
>       "server_type": 0,
>       "resource_id": 4340,
>       "index": 1,
>       "cm_mark": 0
>     },
>     {
>       "id": 0,
>       "title": "1.5周年，上线领自选猎人！",
>       "image": "https://i0.hdslb.com/bfs/sycp/creative_img/202312/5df772ab610d3935f593dd508ca04e30.jpg",
>       "hash": "d4c9886f3f03ce6d3e1567afc529f059",
>       "uri": "https://game.bilibili.com/sklr3/tsmj/h5?msource=1&source=trackadf_5a61ba3af1e847c282e64802383680be&gameID=5840",
>       "request_id": "1701851454461q172a27a117a60q2604",
>       "creative_id": 834862705376211000,
>       "src_id": 4342,
>       "is_ad": true,
>       "is_ad_loc": true,
>       "ad_cb": "",
>       "show_url": "",
>       "click_url": "",
>       "client_ip": "0.0.0.0",
>       "server_type": 1,
>       "resource_id": 4340,
>       "index": 2,
>       "cm_mark": 1,
>       "extra": {
>         "use_ad_web_v2": false,
>         "show_urls": [
>           ""
>         ],
>         "click_urls": [
>           ""
>         ],
>         "download_whitelist": [],
>         "open_whitelist": [],
>         "card": {
>           "card_type": 0,
>           "title": "1.5周年，上线领自选猎人！",
>           "covers": [
>             {
>               "url": "https://i0.hdslb.com/bfs/sycp/creative_img/202312/5df772ab610d3935f593dd508ca04e30.jpg",
>               "loop": 0,
>               "image_height": 0,
>               "image_width": 0,
>               "gif_tag_show": false,
>               "jump_url": "",
>               "title": "",
>               "desc": ""
>             }
>           ],
>           "jump_url": "https://game.bilibili.com/sklr3/tsmj/h5?msource=1&source=trackadf_5a61ba3af1e847c282e64802383680be&gameID=5840",
>           "desc": "",
>           "callup_url": "",
>           "long_desc": "",
>           "ad_tag": "",
>           "extra_desc": "",
>           "universal_app": "",
>           "duration": "",
>           "adver": {
>             "adver_id": 36,
>             "adver_type": 3
>           },
>           "extreme_team_status": false,
>           "support_transition": false,
>           "under_player_interaction_style": 0,
>           "referral_pop_active_time": 10000,
>           "grade_denominator": 0,
>           "star_level": 0,
>           "live_booking_population_threshold": 0,
>           "ori_mark_hidden": 0,
>           "use_multi_cover": false,
>           "custom_feedback_panels": [],
>           "yellow_cart_pannel_pullup": 0,
>           "yellow_cart_pannel_version": 0,
>           "goods_item_id": 0,
>           "story_interaction_style": 0,
>           "videos": [],
>           "download_area": 0,
>           "goods_pannel_show": 0,
>           "goods_panel_show": 0,
>           "show_pop_window": 0,
>           "ad_tag_style": {
>             "type": 2,
>             "text": "广告",
>             "text_color": "#999999FF",
>             "bg_border_color": "#999999FF",
>             "bg_color": "#999999FF",
>             "border_color": "#999999FF"
>           },
>           "feedback_panel": {
>             "panel_type_text": "广告",
>             "feedback_panel_detail": [],
>             "toast": "将减少相似广告推荐",
>             "close_rec_tips": "操作成功",
>             "open_rec_tips": "将减少展示此类广告"
>           },
>           "fold_time": 0,
>           "live_room_popularity": 0,
>           "live_tag_show": false,
>           "quality_infos": [],
>           "dynamic_text": "1.5周年，上线领自选猎人！",
>           "choose_button_list": [],
>           "grade_level": 0,
>           "anim_in_enable": 0,
>           "underframe_card_style": 0,
>           "live_auto_play": false
>         },
>         "report_time": 2000,
>         "appstore_priority": 2,
>         "sales_type": 31,
>         "special_industry": false,
>         "special_industry_tips": "",
>         "preload_landingpage": 0,
>         "share_info": {},
>         "upzone_entrance_type": 0,
>         "upzone_entrance_report_id": 0,
>         "click_area": 0,
>         "shop_id": 0,
>         "up_mid": 0,
>         "track_id": "pbaes.CspX-QTdpL9KncgQzc2-Mm95dCcjkiCMu_rZImtoRamUVs6HAt2-OkahIWbfCXCp3AEEQJumjTujzGtYp2o_mGkvHcGDlJ-F_zoRYV5W7QM=",
>         "enable_store_direct_launch": 0,
>         "enable_double_jump": false,
>         "store_callup_card": false,
>         "enable_h5_alert": false,
>         "special_industry_style": 0,
>         "macro_replace_priority": 1,
>         "feedback_panel_style": 0,
>         "ad_content_type": 0,
>         "enable_h5_pre_load": 0,
>         "hot_activity_id": 0,
>         "product_id": 0,
>         "landingpage_download_style": 2,
>         "download_url_type": 0,
>         "enable_auto_callup": 0,
>         "top_live_stay_time_seconds": 0
>       }
>     },
>     {
>       "id": 1414730,
>       "title": "投稿瓜分3W现金奖励",
>       "image": "http://i0.hdslb.com/bfs/banner/ab4969fb8fe3062a2a89bbf0a563c8d1afd3b98f.jpg",
>       "hash": "2d41f2a097c1633ae6b11fb23d55a142",
>       "uri": "https://www.bilibili.com/blackboard/activity-AIaWvFlxWE.html",
>       "request_id": "1701851454461q172a27a117a60q2604",
>       "src_id": 4343,
>       "is_ad_loc": true,
>       "client_ip": "0.0.0.0",
>       "server_type": 0,
>       "resource_id": 4340,
>       "index": 3,
>       "cm_mark": 0
>     }
>   ]
> }
> ```
> 
> 和
> 
> ```json
> {
>   "card_type": "large_cover_v1",
>   "card_goto": "bangumi",
>   "goto": "bangumi",
>   "param": "342206",
>   "cover": "http://i0.hdslb.com/bfs/bangumi/image/ea90ff4fc8cea3437b0e57d6535f3c4cba252d9c.jpg",
>   "title": "一出好戏",
>   "uri": "https://www.bilibili.com/bangumi/play/ep342206?goto=bangumi&report_flow_data=%7B%22flow_card_type%22%3A%22bangumi%22%2C%22flow_source%22%3A%22bangumi%22%7D&theme=movie&trackid=all_49.router-pegasus-1359033-76cf68d466-2w65p.1701851454078.482",
>   "three_point": {
>     "dislike_reasons": [
>       {
>         "id": 1,
>         "name": "不感兴趣",
>         "toast": "将减少相似内容推荐"
>       }
>     ]
>   },
>   "args": {},
>   "idx": 21,
>   "three_point_v2": [
>     {
>       "title": "不感兴趣",
>       "type": "dislike",
>       "id": 1
>     }
>   ],
>   "track_id": "all_49.router-pegasus-1359033-76cf68d466-2w65p.1701851454078.482",
>   "material_id": 9617,
>   "dislike_report_data": "{\"material_id\":9617}",
>   "report_flow_data": "{\"flow_card_type\":\"bangumi\",\"flow_source\":\"bangumi\"}",
>   "avatar": {
>     "cover": "http://i0.hdslb.com/bfs/bangumi/image/fffaa4070fd8c23a3490ef3eb91eda6be7d848e7.jpg",
>     "type": 1
>   },
>   "cover_left_text_1": "953万",
>   "cover_left_text_2": "23.1万",
>   "cover_badge": "电影",
>   "cover_badge_style": {
>     "text": "电影",
>     "text_color": "#FFFFFF",
>     "bg_color": "#FB7299",
>     "border_color": "#FB7299",
>     "text_color_night": "#E5E5E5",
>     "bg_color_night": "#BB5B76",
>     "border_color_night": "#BB5B76",
>     "bg_style": 1
>   },
>   "desc": "2018-08-10上映",
>   "cover_left_icon_1": 1,
>   "cover_left_icon_2": 4
> }
> ```
> 
> 目前发现这两种没有 mask

感謝你提供的情況，我知道怎麼改了

**Comment by hakadao** [comment]
改了一下問題，這個問題應該不只是edge上有的，今晚我改，儘量出新版本

**Comment by xiaojiejieouo** [comment]
十分感謝你（們）的付出，再次表示感謝.

**Comment by hakadao** [comment]
v0.12.0已修正

**Comment by xiaojiejieouo** [comment]
十分感谢!~
