### ISSUE TITLE
不能悬停播放

### ISSUE THREAD

**Issue by wonbya** [hakadao/BewlyBewly#74]
安装插件后鼠标悬停播放视频失效

**Comment by hakadao** [comment]
甚麼版本的

**Comment by wonbya** [comment]
> 甚麼版本的

0.11.0,更新0.12.0后可以用了。edge加载项的插件没有更新

**Comment by hakadao** [comment]
@wonbya edge 商店審核速度的問題，這個我無法處理，以後直接去chrome商店那裡下吧
