### ISSUE TITLE
【Bug】适应其他页面样式功能开启后，在历史记录界面时间轴标签显示有问题

### ISSUE THREAD

**Issue by MengNianxiaoyao** [hakadao/BewlyBewly#77]
![image](https://github.com/hakadao/BewlyBewly/assets/103258286/b1b6295c-ea37-4a05-b2b1-9bb90ec26b0d)
![image](https://github.com/hakadao/BewlyBewly/assets/103258286/85d42225-b2d7-48e9-94e6-a3f110be7cda)
应该要加选择器将包含`active`的选出来单独加`color: #fff`

**Comment by hakadao** [comment]
好的，過後調整下
