### ISSUE TITLE
topbar 和 dock 都展示了历史记录和收藏

### ISSUE THREAD

**Issue by cuiko** [hakadao/BewlyBewly#80]
想问下这个设计是出于什么考量
![image](https://github.com/hakadao/BewlyBewly/assets/33982919/0300f830-6288-40d7-9ca7-16e7705b456e)

**Comment by hakadao** [comment]
之前bewlybewly只有首頁，頂欄還是保留舊的b站頁面連結，其他頁面是後期加的

**Comment by cuiko** [comment]
> 之前bewlybewly只有首頁，頂欄還是保留舊的b站頁面連結，其他頁面是後期加的

这个地方有计划调整嘛？还是说暂时不动呢？

**Comment by hakadao** [comment]
到時候會是考慮頂欄點擊的話是打開側欄新頁面

**Comment by cuiko** [comment]
> 到時候會是考慮頂欄點擊的話是打開側欄新頁面

期待，我先关闭了
