### ISSUE TITLE
优化建议：topbar 动态列表的视频支持添加到稍后再看

### ISSUE THREAD

**Issue by cuiko** [hakadao/BewlyBewly#81]
原版是支持这个的
after bewlybewly:
![image](https://github.com/hakadao/BewlyBewly/assets/33982919/ea726fc8-ede7-455c-9f95-f86f43d978ec)
before bewlybewly:
![image](https://github.com/hakadao/BewlyBewly/assets/33982919/68caef93-2167-47a5-80f3-1ce34ced8f1d)

**Comment by hakadao** [comment]
v0.13.0 已實現
