### ISSUE TITLE
【Bug】使用插件的顶栏会导致部分专栏打开失败

### ISSUE THREAD

**Issue by MengNianxiaoyao** [hakadao/BewlyBewly#83]
错误的专栏链接
![image](https://github.com/hakadao/BewlyBewly/assets/103258286/eed4eae5-c32f-4b4c-a4bd-7737f01245c6)
正确的专栏链接
![image](https://github.com/hakadao/BewlyBewly/assets/103258286/0501244f-3eca-4d09-ab98-c87987cafdf7)

**Comment by MengNianxiaoyao** [comment]
四个专栏，两个链接是错的，是不是api获取信息的时候就错了

**Comment by MengNianxiaoyao** [comment]
看了下api给出的参数，发现出错的专栏用的都是oid，应该要改成cid为0的时候才用oid

**Comment by MengNianxiaoyao** [comment]
#84 已修复

**Comment by hakadao** [comment]
非常感謝，上班沒有時間開發，感謝閣下這段時間付出，稍後我看看再合併

**Comment by MengNianxiaoyao** [comment]
最新的代码构建出来，打开专栏是白的，但鼠标按住拖动能拖动里面的东西

**Comment by hakadao** [comment]
> 最新的代码构建出来，打开专栏是白的，但鼠标按住拖动能拖动里面的东西

我知道怎麼回事了，一會提交修正

**Comment by hakadao** [comment]
> 最新的代码构建出来，打开专栏是白的，但鼠标按住拖动能拖动里面的东西

已修正
