### ISSUE TITLE
优化：专栏界面适配

### ISSUE THREAD

**Issue by MengNianxiaoyao** [hakadao/BewlyBewly#87]
![image](https://github.com/hakadao/BewlyBewly/assets/103258286/8a0b8d5e-42ea-467d-80c6-4994b1ba9970)

**Comment by hakadao** [comment]
這個先不做，下個版本做，不要增加工作量

**Comment by MengNianxiaoyao** [comment]
> 這個先不做，下個版本做，不要增加工作量

确实，issue先挂着，把代码重构完再做吧

**Comment by hakadao** [comment]
v0.14.0已實現
