### ISSUE TITLE
几点建议和想法

### ISSUE THREAD

**Issue by longshensanjie** [hakadao/BewlyBewly#91]
用了一段时间，感觉很不错，已经是每天都在使用的形状啦，给作者比心，但还是有一些优化建议和想法，希望插件能做的更好

1.收藏页面偶尔会有视频失效的情况出现，如果失效的比较多需要一个个去取消收藏比较麻烦，希望有个批量一键取消失效视频的功能

2.主页的个性推荐视频当中总会推荐一些可能自己不想看的视频，希望能有类似b站移动端我不想看减少类似视频推荐功能的按钮，按钮样式可以就像现在视频列表右上角稍后再看即可

3.另外是比较私人的视频播放页习惯问题，作者可以酌情看心情判断，我日常使用习惯是此插件加上Bilibili Evolved脚本的屏蔽视频右边推荐视频列表使用的，看视频的时候不太喜欢右侧的推荐列表，这个如果能提供播放页的直接设置我就可以不用其他脚本辅助使用了

4.最后是插件暂时没涉及到的直播模块，个人其实上b站也有很大的时间是在看直播，如果能有一个类似视频播放页一样的简洁干净的直播样式就是太好啦，加点直播设置自动原画什么的小功能设置就很完美了，至此基本上就不需要其他脚本的任何功能，就一个插件就解决我的所有需求了

以上就是暂时的想法和建议，非常感谢作者的辛苦付出，希望看到这些建议不会让你有坏心情，年末了，也祝作者新年快乐！

**Comment by hakadao** [comment]
1. 收藏頁面完善功能要放在後期做
2. 個性推介取消不想看內容只有移動端推介可以實現
3. 淨化功能放後期
4. 直播板塊我不怎麼看直播，也不知道做些什麼功能，其實我不想做成萬金油那種，留些空間給其他人發揮吧

**Comment by longshensanjie** [comment]
ok，感谢作者的回复，之前提到的1和3点都已经了解

1. 关于第二点个性推荐pc端无法实现的话，如果替换成仅仅是点击不想看让视频在首页消失是否可行，甚至更进一步允许用户自定义屏蔽关键字视频和up，将推荐交给用户自定义，当然这只是一个想法，是否可行或者合适或是否必要全看你的判断

2. 再就是直播模块，其实我的想法也很简单，就是希望点开直播页面也能有一个和你设计的视频播放页一样简单干净的直播页面即可，主要是比较喜欢你对播放页面的那种简单感觉的设计，也不需要做其他的很多功能，就这样就好，使用起来也有一种整体统一设计风格的感觉，至于我之前说的那些直播设置自动原画那些小功能确实没有必要，理解你不想做成万金油的初衷

**Comment by MengNianxiaoyao** [comment]
1. 自定义屏蔽关键字视频和up功能可以实现，但有可能会影响性能（首页加载卡顿、滑动卡顿之类的）
2. 直播界面留下必要的组件，其它可以删了，再统一一下风格

**Comment by hakadao** [comment]
功能方面我是想已有實現擴充功能、插件的話我不會再做，bewlybewly主要是想在b站操作上調整和改進的
