### ISSUE TITLE
视频选集无法选中

### ISSUE THREAD

**Issue by puppet680** [hakadao/BewlyBewly#96]
![无标题](https://github.com/hakadao/BewlyBewly/assets/54428441/e133cd43-7f8c-4a3c-83f2-193dd38961ba)

![image](https://github.com/hakadao/BewlyBewly/assets/54428441/55199577-ee9e-4278-aaaa-17d240db59b5)
关闭css  .w-full 样式恢复正常

**Comment by MengNianxiaoyao** [comment]
侧边栏的上一级div挡住的，移除掉看看

**Comment by hakadao** [comment]
er回去改

**Comment by hakadao** [comment]
v0.13.1已修正，你可以直接下載這裏的 extension.zip 手動安裝
或等待chrome那邊更新
https://github.com/hakadao/BewlyBewly/releases/tag/v0.13.1
